;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_cputc
	.import		_printf
	.import		_putchar
	.export		_myprint
	.export		_main

.segment	"RODATA"

L0176:
	.byte	$0D,$50,$55,$54,$43,$48,$41,$52,$20,$43,$59,$43,$4C,$45,$53,$3A
	.byte	$20,$25,$55,$0D,$00
L015E:
	.byte	$0D,$4D,$59,$50,$52,$49,$4E,$54,$20,$43,$59,$43,$4C,$45,$53,$3A
	.byte	$20,$25,$55,$0D,$00
L0144:
	.byte	$0D,$50,$52,$49,$4E,$54,$46,$20,$43,$59,$43,$4C,$45,$53,$3A,$20
	.byte	$25,$55,$0D,$00
L012B:
	.byte	$0D,$43,$50,$55,$54,$43,$20,$43,$59,$43,$4C,$45,$53,$3A,$20,$25
	.byte	$55,$0D,$00
L013A:
	.byte	$41,$00
L0154	:=	L013A+0

; ---------------------------------------------------------------
; void __near__ myprint (unsigned char, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_myprint: near

.segment	"CODE"

	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     tosumulax
	jsr     pushax
	ldx     #$04
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	jmp     L010C
L010A:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$04
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
L010C:	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jne     L010A
	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp6
	ldx     #$DC
	lda     #$04
	jsr     pushax
	ldx     #$DC
	lda     #$05
	jsr     pushax
	ldx     #$DC
	lda     #$0E
	jsr     pushax
	jsr     _clrscr
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$11
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$0A
	jsr     staxysp
	lda     #$41
	jsr     _cputc
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$08
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tossubax
	ldy     #$06
	jsr     staxysp
	lda     #<(L012B)
	ldx     #>(L012B)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$11
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$0A
	jsr     staxysp
	lda     #<(L013A)
	ldx     #>(L013A)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$08
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tossubax
	ldy     #$06
	jsr     staxysp
	lda     #<(L0144)
	ldx     #>(L0144)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$11
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$0A
	jsr     staxysp
	lda     #$00
	jsr     pusha
	lda     #<(L0154)
	ldx     #>(L0154)
	jsr     _myprint
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$08
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tossubax
	ldy     #$06
	jsr     staxysp
	lda     #<(L015E)
	ldx     #>(L015E)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$FF
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$11
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$0A
	jsr     staxysp
	ldx     #$00
	lda     #$41
	jsr     _putchar
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$08
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tossubax
	ldy     #$06
	jsr     staxysp
	lda     #<(L0176)
	ldx     #>(L0176)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldy     #$0C
	jsr     addysp
	rts

.endproc

