;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_cbm_open
	.import		_cbm_close
	.import		_cbm_read
	.import		_cbm_write
	.import		_printf
	.import		_malloc
	.import		_free
	.export		_objects
	.export		_object_count
	.export		_save_model
	.export		_parse_model_data
	.export		_load_object
	.export		_objectstateprint

.segment	"DATA"

_object_count:
	.word	$0000

.segment	"RODATA"

L0152:
	.byte	$D4,$4F,$54,$41,$4C,$20,$4D,$45,$4D,$4F,$52,$59,$20,$55,$53,$45
	.byte	$44,$20,$42,$59,$20,$41,$4C,$4C,$20,$4F,$42,$4A,$45,$43,$54,$53
	.byte	$3A,$20,$25,$55,$20,$42,$59,$54,$45,$53,$0D,$00
L011A:
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D
	.byte	$2D,$2D,$2D,$2D,$2D,$2D,$2D,$2D,$0D,$00
L0117:
	.byte	$C9,$C4,$20,$20,$DD,$20,$D0,$4F,$49,$4E,$54,$53,$20,$DD,$20,$D4
	.byte	$52,$49,$53,$20,$DD,$20,$42,$59,$54,$45,$53,$0D,$00
L0148:
	.byte	$25,$33,$44,$20,$DD,$20,$25,$36,$44,$20,$DD,$20,$25,$35,$44,$20
	.byte	$DD,$20,$25,$31,$30,$55,$0D,$00
L0114:
	.byte	$CF,$42,$4A,$45,$43,$54,$20,$4C,$49,$53,$54,$3A,$0D,$00

.segment	"BSS"

_file_buffer:
	.res	1024,$00
_objects:
	.res	128,$00

; ---------------------------------------------------------------
; int __near__ save_model (__near__ const unsigned char *, unsigned int, __near__ struct $anon-struct-0017 *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_save_model: near

.segment	"BSS"

L000A:
	.res	2,$00
L000C:
	.res	2,$00
L000E:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	sta     L000A
	stx     L000A+1
	ldx     #$00
	lda     #$01
	sta     L000C
	stx     L000C+1
	ldy     #$01
	jsr     ldaxysp
	jsr     bnegax
	jne     L0010
	ldy     #$01
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     bnegax
	jne     L0010
	ldy     #$01
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     bnegax
	jne     L0010
	ldx     #$00
	lda     #$00
	jeq     L0011
L0010:	ldx     #$00
	lda     #$01
L0011:	jeq     L000F
	ldx     #$00
	lda     #$00
	jmp     L0009
L000F:	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$05
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldx     #$00
	lda     #$00
	sta     L000E
	stx     L000E+1
L001B:	lda     L000E
	ldx     L000E+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     ldauidx
	jsr     tosultax
	jne     L001E
	jmp     L001C
L001E:	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax6
	jsr     tosaddax
	ldy     #$01
	jsr     ldaxidx
	ldx     #$00
	ldx     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax6
	jsr     tosaddax
	ldy     #$01
	jsr     ldaxidx
	cpx     #$80
	txa
	ldx     #$00
	bcc     L002C
	dex
L002C:	ldx     #$00
	ldx     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax6
	jsr     tosaddax
	ldy     #$03
	jsr     ldaxidx
	ldx     #$00
	ldx     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax6
	jsr     tosaddax
	ldy     #$03
	jsr     ldaxidx
	cpx     #$80
	txa
	ldx     #$00
	bcc     L0036
	dex
L0036:	ldx     #$00
	ldx     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax6
	jsr     tosaddax
	ldy     #$05
	jsr     ldaxidx
	ldx     #$00
	ldx     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax6
	jsr     tosaddax
	ldy     #$05
	jsr     ldaxidx
	cpx     #$80
	txa
	ldx     #$00
	bcc     L0040
	dex
L0040:	ldx     #$00
	ldx     #$00
	ldy     #$00
	jsr     staspidx
	lda     L000E
	ldx     L000E+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000E
	stx     L000E+1
	lda     regsave
	ldx     regsave+1
	jmp     L001B
L001C:	ldx     #$00
	lda     #$00
	sta     L000E
	stx     L000E+1
L0041:	lda     L000E
	ldx     L000E+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$05
	jsr     ldauidx
	jsr     tosultax
	jne     L0044
	jmp     L0042
L0044:	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax3
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax3
	jsr     tosaddax
	ldy     #$01
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	lda     L000A
	ldx     L000A+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000A
	stx     L000A+1
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L000E
	ldx     L000E+1
	jsr     mulax3
	jsr     tosaddax
	ldy     #$02
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	lda     L000E
	ldx     L000E+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L000E
	stx     L000E+1
	lda     regsave
	ldx     regsave+1
	jmp     L0041
L0042:	lda     L000C
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	lda     L000C
	jsr     pusha
	ldy     #$08
	jsr     ldaxysp
	jsr     _cbm_open
	cmp     #$00
	jsr     boolne
	jeq     L0052
	ldx     #$00
	lda     #$00
	jmp     L0009
L0052:	lda     L000C
	jsr     pusha
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	jsr     pushax
	lda     L000A
	ldx     L000A+1
	jsr     pushax
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	jsr     tossubax
	jsr     _cbm_write
	jsr     pushax
	lda     L000A
	ldx     L000A+1
	jsr     pushax
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	jsr     tossubax
	jsr     tosneax
	jeq     L0059
	lda     L000C
	jsr     _cbm_close
	ldx     #$00
	lda     #$00
	jmp     L0009
L0059:	lda     L000C
	jsr     _cbm_close
	ldx     #$00
	lda     #$01
	jmp     L0009
L0009:	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ parse_model_data (__near__ unsigned char *, __near__ struct $anon-struct-0017 *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_model_data: near

.segment	"BSS"

L0067:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldx     #$00
	lda     #$00
	sta     L0067
	stx     L0067+1
L0068:	lda     L0067
	ldx     L0067+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     ldauidx
	jsr     tosultax
	jne     L006B
	jmp     L0069
L006B:	ldy     #$01
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0067
	ldx     L0067+1
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$01
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$00
	jsr     staxspidx
	ldy     #$02
	ldx     #$00
	lda     #$02
	jsr     addeqysp
	ldy     #$01
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0067
	ldx     L0067+1
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$01
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$02
	jsr     staxspidx
	ldy     #$02
	ldx     #$00
	lda     #$02
	jsr     addeqysp
	ldy     #$01
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0067
	ldx     L0067+1
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$01
	jsr     ldauidx
	tax
	lda     #$00
	jsr     tosorax
	ldy     #$04
	jsr     staxspidx
	ldy     #$02
	ldx     #$00
	lda     #$02
	jsr     addeqysp
	lda     L0067
	ldx     L0067+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L0067
	stx     L0067+1
	lda     regsave
	ldx     regsave+1
	jmp     L0068
L0069:	ldx     #$00
	lda     #$00
	sta     L0067
	stx     L0067+1
L0088:	lda     L0067
	ldx     L0067+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$05
	jsr     ldauidx
	jsr     tosultax
	jne     L008B
	jmp     L0089
L008B:	ldy     #$01
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L0067
	ldx     L0067+1
	jsr     mulax3
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$04
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L0067
	ldx     L0067+1
	jsr     mulax3
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$04
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$00
	jsr     ldauidx
	ldy     #$01
	jsr     staspidx
	ldy     #$01
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L0067
	ldx     L0067+1
	jsr     mulax3
	jsr     tosaddax
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$04
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	ldy     #$00
	jsr     ldauidx
	ldy     #$02
	jsr     staspidx
	lda     L0067
	ldx     L0067+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L0067
	stx     L0067+1
	lda     regsave
	ldx     regsave+1
	jmp     L0088
L0089:	jsr     incsp4
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ load_object (__near__ const unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_object: near

.segment	"BSS"

L009A:
	.res	2,$00
L009B:
	.res	2,$00
L009C:
	.res	2,$00
L009E:
	.res	2,$00

.segment	"CODE"

	jsr     pusha
	ldx     #$00
	lda     #$02
	sta     L009C
	stx     L009C+1
	lda     _object_count
	ldx     _object_count+1
	cmp     #$40
	txa
	sbc     #$00
	bvs     L00A1
	eor     #$80
L00A1:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L009F
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L009F:	lda     L009C
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	lda     L009C
	jsr     pusha
	ldy     #$05
	jsr     ldaxysp
	jsr     _cbm_open
	cmp     #$00
	jsr     boolne
	jeq     L00A3
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L00A3:	lda     L009C
	jsr     pusha
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     _cbm_read
	sta     L009E
	stx     L009E+1
	lda     L009E
	ldx     L009E+1
	cmp     #$04
	txa
	sbc     #$00
	bvc     L00B1
	eor     #$80
L00B1:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L00AF
	lda     L009C
	jsr     _cbm_close
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L00AF:	ldx     #$00
	lda     #$06
	jsr     _malloc
	sta     L009A
	stx     L009A+1
	lda     L009A
	ldx     L009A+1
	jsr     bnegax
	jeq     L00B8
	lda     L009C
	jsr     _cbm_close
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L00B8:	lda     L009A
	ldx     L009A+1
	jsr     pushax
	ldx     #$00
	lda     _file_buffer+2
	ldy     #$04
	jsr     staspidx
	lda     L009A
	ldx     L009A+1
	jsr     pushax
	ldx     #$00
	lda     _file_buffer+3
	ldy     #$05
	jsr     staspidx
	lda     L009A
	ldx     L009A+1
	jsr     pushax
	lda     L009A
	ldx     L009A+1
	ldy     #$04
	jsr     ldauidx
	jsr     mulax6
	jsr     _malloc
	ldy     #$00
	jsr     staxspidx
	lda     L009A
	ldx     L009A+1
	jsr     pushax
	lda     L009A
	ldx     L009A+1
	ldy     #$05
	jsr     ldauidx
	jsr     mulax3
	jsr     _malloc
	ldy     #$02
	jsr     staxspidx
	lda     L009A
	ldx     L009A+1
	ldy     #$01
	jsr     ldaxidx
	jsr     bnegax
	jne     L00CA
	lda     L009A
	ldx     L009A+1
	ldy     #$03
	jsr     ldaxidx
	jsr     bnegax
	jne     L00CA
	ldx     #$00
	lda     #$00
	jeq     L00CB
L00CA:	ldx     #$00
	lda     #$01
L00CB:	jeq     L00C9
	lda     L009A
	ldx     L009A+1
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L00CC
	lda     L009A
	ldx     L009A+1
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
L00CC:	lda     L009A
	ldx     L009A+1
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L00D0
	lda     L009A
	ldx     L009A+1
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
L00D0:	lda     L009A
	ldx     L009A+1
	jsr     _free
	lda     L009C
	jsr     _cbm_close
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L00C9:	lda     L009C
	jsr     pusha
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	jsr     pushax
	ldx     #$04
	lda     #$00
	jsr     _cbm_read
	sta     L009E
	stx     L009E+1
	lda     L009C
	jsr     _cbm_close
	lda     #<(_file_buffer)
	ldx     #>(_file_buffer)
	jsr     pushax
	lda     L009A
	ldx     L009A+1
	jsr     _parse_model_data
	ldx     #$00
	lda     #$11
	jsr     _malloc
	sta     L009B
	stx     L009B+1
	lda     L009B
	ldx     L009B+1
	jsr     bnegax
	jeq     L00E6
	lda     L009A
	ldx     L009A+1
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L009A
	ldx     L009A+1
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
	lda     L009A
	ldx     L009A+1
	jsr     _free
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L00E6:	lda     L009B
	ldx     L009B+1
	jsr     pushax
	lda     L009A
	ldx     L009A+1
	ldy     #$04
	jsr     ldauidx
	jsr     mulax6
	jsr     _malloc
	ldy     #$02
	jsr     staxspidx
	lda     L009B
	ldx     L009B+1
	ldy     #$03
	jsr     ldaxidx
	jsr     bnegax
	jeq     L00F2
	lda     L009B
	ldx     L009B+1
	jsr     _free
	lda     L009A
	ldx     L009A+1
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L009A
	ldx     L009A+1
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
	lda     L009A
	ldx     L009A+1
	jsr     _free
	ldx     #$FF
	lda     #$FF
	jmp     L0099
L00F2:	lda     L009B
	ldx     L009B+1
	jsr     pushax
	lda     L009A
	ldx     L009A+1
	ldy     #$00
	jsr     staxspidx
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxspidx
	ldy     #$06
	jsr     staxspidx
	ldy     #$04
	jsr     staxspidx
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0E
	jsr     staxspidx
	ldy     #$0C
	jsr     staxspidx
	ldy     #$0A
	jsr     staxspidx
	lda     L009B
	ldx     L009B+1
	jsr     pushax
	ldx     #$00
	lda     _object_count
	ldy     #$10
	jsr     staspidx
	lda     _object_count
	ldx     _object_count+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     _object_count
	stx     _object_count+1
	lda     regsave
	ldx     regsave+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	jsr     pushax
	lda     L009B
	ldx     L009B+1
	ldy     #$00
	jsr     staxspidx
	lda     _object_count
	ldx     _object_count+1
	jsr     decax1
	jmp     L0099
L0099:	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ objectstateprint (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_objectstateprint: near

.segment	"BSS"

L010E:
	.res	2,$00
L0110:
	.res	2,$00
L0111:
	.res	2,$00

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     L010E
	stx     L010E+1
	ldx     #$00
	lda     #$00
	sta     L0111
	stx     L0111+1
	lda     #<(L0114)
	ldx     #>(L0114)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     #<(L0117)
	ldx     #>(L0117)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     #<(L011A)
	ldx     #>(L011A)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	sta     L0110
	stx     L0110+1
L011C:	lda     L0110
	ldx     L0110+1
	jsr     pushax
	lda     _object_count
	ldx     _object_count+1
	jsr     tosultax
	jne     L011F
	jmp     L011D
L011F:	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     bnegax
	jeq     L0125
	jmp     L011E
L0125:	ldx     #$00
	lda     #$00
	sta     L0111
	stx     L0111+1
	lda     #$11
	clc
	adc     L0111
	sta     L0111
	bcc     L012C
	inc     L0111+1
L012C:	ldx     L0111+1
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L012D
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     mulax6
	clc
	adc     L0111
	sta     L0111
	txa
	adc     L0111+1
	sta     L0111+1
	tax
	lda     L0111
L012D:	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L013F
	lda     #$06
	clc
	adc     L0111
	sta     L0111
	bcc     L0138
	inc     L0111+1
L0138:	ldx     L0111+1
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L0139
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     mulax6
	clc
	adc     L0111
	sta     L0111
	txa
	adc     L0111+1
	sta     L0111+1
	tax
	lda     L0111
L0139:	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L013F
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     mulax3
	clc
	adc     L0111
	sta     L0111
	txa
	adc     L0111+1
	sta     L0111+1
	tax
	lda     L0111
L013F:	lda     L0111
	ldx     L0111+1
	clc
	adc     L010E
	sta     L010E
	txa
	adc     L010E+1
	sta     L010E+1
	tax
	lda     L010E
	lda     #<(L0148)
	ldx     #>(L0148)
	jsr     pushax
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$10
	jsr     ldauidx
	jsr     pushax
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0110
	ldx     L0110+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     L0111
	ldx     L0111+1
	jsr     pushax
	ldy     #$0A
	jsr     _printf
L011E:	inc     L0110
	bne     L0124
	inc     L0110+1
L0124:	lda     L0110
	ldx     L0110+1
	jmp     L011C
L011D:	lda     #<(L0152)
	ldx     #>(L0152)
	jsr     pushax
	lda     L010E
	ldx     L010E+1
	jsr     pushax
	ldy     #$04
	jsr     _printf
	rts

.endproc

