;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_tgi_static_stddrv
	.import		_tgi_install
	.import		_tgi_uninstall
	.import		_tgi_init
	.import		_tgi_clear
	.import		_tgi_setcolor
	.import		_tgi_line
	.import		_printf
	.import		_malloc
	.import		_free
	.import		__heapmemavail
	.import		_cosine
	.import		_sine
	.import		_objects
	.import		_save_model
	.import		_load_object
	.import		_objectstateprint
	.import		_object_count
	.export		_transformed
	.export		_sort_list
	.export		_foreground_box
	.export		_total_faces
	.export		_rotX
	.export		_rotY
	.export		_rotZ
	.export		_torroid_points
	.export		_torroid_faces_tri
	.export		_pyramid_points
	.export		_pyramid_tris
	.export		_rotate_x
	.export		_rotate_y
	.export		_rotate_z
	.export		_sort_scene
	.export		_delay
	.export		_fill_triangle
	.export		_render_scene
	.export		_add_to_scene
	.export		_main

.segment	"DATA"

_torroid_points:
	.word	$003C
	.word	$0000
	.word	$0000
	.word	$0028
	.word	$0014
	.word	$0000
	.word	$0014
	.word	$0000
	.word	$0000
	.word	$0028
	.word	$FFEC
	.word	$0000
	.word	$002A
	.word	$0000
	.word	$002A
	.word	$001C
	.word	$000E
	.word	$001C
	.word	$000E
	.word	$0000
	.word	$000E
	.word	$001C
	.word	$FFF2
	.word	$001C
	.word	$0000
	.word	$0000
	.word	$003C
	.word	$0000
	.word	$0014
	.word	$0028
	.word	$0000
	.word	$0000
	.word	$0014
	.word	$0000
	.word	$FFEC
	.word	$0028
	.word	$FFD6
	.word	$0000
	.word	$002A
	.word	$FFE4
	.word	$000E
	.word	$001C
	.word	$FFF2
	.word	$0000
	.word	$000E
	.word	$FFE4
	.word	$FFF2
	.word	$001C
	.word	$FFC4
	.word	$0000
	.word	$0000
	.word	$FFD8
	.word	$0014
	.word	$0000
	.word	$FFEC
	.word	$0000
	.word	$0000
	.word	$FFD8
	.word	$FFEC
	.word	$0000
	.word	$FFD6
	.word	$0000
	.word	$FFD6
	.word	$FFE4
	.word	$000E
	.word	$FFE4
	.word	$FFF2
	.word	$0000
	.word	$FFF2
	.word	$FFE4
	.word	$FFF2
	.word	$FFE4
	.word	$0000
	.word	$0000
	.word	$FFC4
	.word	$0000
	.word	$0014
	.word	$FFD8
	.word	$0000
	.word	$0000
	.word	$FFEC
	.word	$0000
	.word	$FFEC
	.word	$FFD8
	.word	$002A
	.word	$0000
	.word	$FFD6
	.word	$001C
	.word	$000E
	.word	$FFE4
	.word	$000E
	.word	$0000
	.word	$FFF2
	.word	$001C
	.word	$FFF2
	.word	$FFE4
	.res	96,$00
_torroid_faces_tri:
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$00
	.byte	$05
	.byte	$04
	.byte	$01
	.byte	$02
	.byte	$06
	.byte	$01
	.byte	$06
	.byte	$05
	.byte	$02
	.byte	$03
	.byte	$07
	.byte	$02
	.byte	$07
	.byte	$06
	.byte	$03
	.byte	$00
	.byte	$04
	.byte	$03
	.byte	$04
	.byte	$07
	.byte	$04
	.byte	$05
	.byte	$09
	.byte	$04
	.byte	$09
	.byte	$08
	.byte	$05
	.byte	$06
	.byte	$0A
	.byte	$05
	.byte	$0A
	.byte	$09
	.byte	$06
	.byte	$07
	.byte	$0B
	.byte	$06
	.byte	$0B
	.byte	$0A
	.byte	$07
	.byte	$04
	.byte	$08
	.byte	$07
	.byte	$08
	.byte	$0B
	.byte	$08
	.byte	$09
	.byte	$0D
	.byte	$08
	.byte	$0D
	.byte	$0C
	.byte	$09
	.byte	$0A
	.byte	$0E
	.byte	$09
	.byte	$0E
	.byte	$0D
	.byte	$0A
	.byte	$0B
	.byte	$0F
	.byte	$0A
	.byte	$0F
	.byte	$0E
	.byte	$0B
	.byte	$08
	.byte	$0C
	.byte	$0B
	.byte	$0C
	.byte	$0F
	.byte	$0C
	.byte	$0D
	.byte	$11
	.byte	$0C
	.byte	$11
	.byte	$10
	.byte	$0D
	.byte	$0E
	.byte	$12
	.byte	$0D
	.byte	$12
	.byte	$11
	.byte	$0E
	.byte	$0F
	.byte	$13
	.byte	$0E
	.byte	$13
	.byte	$12
	.byte	$0F
	.byte	$0C
	.byte	$10
	.byte	$0F
	.byte	$10
	.byte	$13
	.byte	$10
	.byte	$11
	.byte	$15
	.byte	$10
	.byte	$15
	.byte	$14
	.byte	$11
	.byte	$12
	.byte	$16
	.byte	$11
	.byte	$16
	.byte	$15
	.byte	$12
	.byte	$13
	.byte	$17
	.byte	$12
	.byte	$17
	.byte	$16
	.byte	$13
	.byte	$10
	.byte	$14
	.byte	$13
	.byte	$14
	.byte	$17
	.byte	$14
	.byte	$15
	.byte	$19
	.byte	$14
	.byte	$19
	.byte	$18
	.byte	$15
	.byte	$16
	.byte	$1A
	.byte	$15
	.byte	$1A
	.byte	$19
	.byte	$16
	.byte	$17
	.byte	$1B
	.byte	$16
	.byte	$1B
	.byte	$1A
	.byte	$17
	.byte	$14
	.byte	$18
	.byte	$17
	.byte	$18
	.byte	$1B
	.byte	$18
	.byte	$19
	.byte	$1D
	.byte	$18
	.byte	$1D
	.byte	$1C
	.byte	$19
	.byte	$1A
	.byte	$1E
	.byte	$19
	.byte	$1E
	.byte	$1D
	.byte	$1A
	.byte	$1B
	.byte	$1F
	.byte	$1A
	.byte	$1F
	.byte	$1E
	.byte	$1B
	.byte	$18
	.byte	$1C
	.byte	$1B
	.byte	$1C
	.byte	$1F
	.byte	$1C
	.byte	$1D
	.byte	$01
	.byte	$1C
	.byte	$01
	.byte	$00
	.byte	$1D
	.byte	$1E
	.byte	$02
	.byte	$1D
	.byte	$02
	.byte	$01
	.byte	$1E
	.byte	$1F
	.byte	$03
	.byte	$1E
	.byte	$03
	.byte	$02
	.byte	$1F
	.byte	$1C
	.byte	$00
	.byte	$1F
	.byte	$00
	.byte	$03
_pyramid_points:
	.word	$0000
	.word	$0014
	.word	$0000
	.word	$FFEC
	.word	$FFEC
	.word	$FFEC
	.word	$0014
	.word	$FFEC
	.word	$FFEC
	.word	$0014
	.word	$FFEC
	.word	$0014
	.word	$FFEC
	.word	$FFEC
	.word	$0014
_pyramid_tris:
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$03
	.byte	$02
	.byte	$00
	.byte	$04
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$04
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$01
	.byte	$03
	.byte	$04

.segment	"RODATA"

L0516:
	.byte	$D0,$D2,$D9,$CD,$20,$4C,$4F,$41,$44,$45,$44,$3A,$20,$25,$44,$20
	.byte	$50,$54,$53,$20,$25,$44,$20,$54,$52,$49,$53,$2C,$20,$25,$55,$CB
	.byte	$C2,$20,$46,$52,$45,$45,$0D,$00
L0543	:=	L0516+5
L0534	:=	L0516+5
L0525	:=	L0516+5
L0654:
	.byte	$0D,$0D,$41,$4C,$4C,$4F,$43,$20,$42,$45,$46,$4F,$52,$45,$20,$43
	.byte	$4C,$45,$41,$4E,$20,$25,$55,$3A,$20,$25,$55,$20,$42,$59,$54,$45
	.byte	$53,$0D,$00
L050A:
	.byte	$C6,$41,$49,$4C,$45,$44,$20,$54,$4F,$20,$53,$41,$56,$45,$20,$54
	.byte	$4F,$52,$52,$4F,$49,$44,$20,$4D,$4F,$44,$45,$4C,$2E,$0D,$00
L0506:
	.byte	$D3,$D5,$C3,$C3,$C5,$D3,$D3,$3A,$20,$54,$4F,$52,$52,$4F,$49,$44
	.byte	$20,$4D,$4F,$44,$45,$4C,$20,$53,$41,$56,$45,$44,$2E,$0D,$00
L04FB:
	.byte	$C6,$41,$49,$4C,$45,$44,$20,$54,$4F,$20,$53,$41,$56,$45,$20,$50
	.byte	$59,$52,$41,$4D,$49,$44,$20,$4D,$4F,$44,$45,$4C,$2E,$0D,$00
L04F7:
	.byte	$D3,$D5,$C3,$C3,$C5,$D3,$D3,$3A,$20,$D0,$59,$52,$41,$4D,$49,$44
	.byte	$20,$4D,$4F,$44,$45,$4C,$20,$53,$41,$56,$45,$44,$2E,$0D,$00
L04CF:
	.byte	$CF,$55,$54,$20,$4F,$46,$20,$4D,$45,$4D,$4F,$52,$59,$20,$46,$4F
	.byte	$52,$20,$54,$4F,$52,$52,$4F,$49,$44,$0D,$00
L04C4:
	.byte	$CF,$55,$54,$20,$4F,$46,$20,$4D,$45,$4D,$4F,$52,$59,$20,$46,$4F
	.byte	$52,$20,$50,$59,$52,$41,$4D,$49,$44,$0D,$00
L0668:
	.byte	$41,$4C,$4C,$4F,$43,$20,$41,$46,$54,$45,$52,$20,$25,$55,$3A,$20
	.byte	$25,$55,$20,$42,$59,$54,$45,$53,$0D,$00
L05E3:
	.byte	$4C,$4F,$41,$44,$45,$44,$3A,$20,$25,$44,$20,$50,$54,$53,$20,$25
	.byte	$44,$20,$54,$52,$49,$53,$0D,$00
L05B9	:=	L05E3+0
L04EC:
	.byte	$C2,$45,$47,$49,$4E,$4E,$49,$4E,$47,$20,$53,$41,$56,$45,$20,$54
	.byte	$45,$53,$54,$0D,$00
L05F3:
	.byte	$52,$55,$4E,$4E,$49,$4E,$47,$20,$31,$53,$54,$20,$41,$4C,$4C,$4F
	.byte	$43,$00
L057F:
	.byte	$D4,$C5,$D3,$D4,$20,$D0,$C1,$D3,$D3,$C5,$C4,$0D,$00
L0579:
	.byte	$D2,$C5,$CE,$C4,$C5,$D2,$D3,$C3,$C5,$CE,$C5,$0D,$00
L0583:
	.byte	$D4,$C5,$D3,$D4,$20,$C6,$C1,$C9,$CC,$C5,$C4,$0D,$00
L0501:
	.byte	$D4,$CF,$D2,$D2,$CF,$C9,$C4,$2C,$D0,$2C,$D7,$00
L052E:
	.byte	$D4,$CF,$D2,$D2,$CF,$C9,$C4,$2C,$D0,$2C,$D2,$00
L051F	:=	L052E+0
L05CA	:=	L052E+0
L053D	:=	L052E+0
L0575:
	.byte	$D3,$CF,$D2,$D4,$D3,$C3,$C5,$CE,$C5,$0D,$00
L059E:
	.byte	$D0,$D2,$D9,$CD,$2C,$D0,$2C,$D2,$00
L04F2:
	.byte	$D0,$D2,$D9,$CD,$2C,$D0,$2C,$D7,$00
L0510	:=	L059E+0
L0670:
	.byte	$C5,$58,$49,$54,$45,$44,$0D,$00

.segment	"BSS"

_transformed:
	.res	288,$00
_sort_list:
	.res	9196,$00
_foreground_box:
	.res	8,$00
_total_faces:
	.res	1,$00
_rotX:
	.res	2,$00
_rotY:
	.res	2,$00
_rotZ:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ rotate_x (__near__ int *, __near__ int *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_x: near

.segment	"BSS"

L0252:
	.res	4,$00
L0254:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0252
	stx     L0252+1
	ldy     sreg
	sty     L0252+2
	ldy     sreg+1
	sty     L0252+3
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0254
	stx     L0254+1
	ldy     sreg
	sty     L0254+2
	ldy     sreg+1
	sty     L0254+3
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	cpx     #$80
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0258
	ldy     #$00
	ldx     #$01
	lda     #$68
	jsr     addeqysp
L0258:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     L0252+3
	sta     sreg+1
	lda     L0252+2
	sta     sreg
	ldx     L0252+1
	lda     L0252
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0254+3
	sta     sreg+1
	lda     L0254+2
	sta     sreg
	ldx     L0254+1
	lda     L0254
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0262
	dey
L0262:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     L0252+3
	sta     sreg+1
	lda     L0252+2
	sta     sreg
	ldx     L0252+1
	lda     L0252
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0254+3
	sta     sreg+1
	lda     L0254+2
	sta     sreg
	ldx     L0254+1
	lda     L0254
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0269
	dey
L0269:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_y (__near__ int *, __near__ int *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_y: near

.segment	"BSS"

L026B:
	.res	4,$00
L026D:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L026B
	stx     L026B+1
	ldy     sreg
	sty     L026B+2
	ldy     sreg+1
	sty     L026B+3
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L026D
	stx     L026D+1
	ldy     sreg
	sty     L026D+2
	ldy     sreg+1
	sty     L026D+3
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	cpx     #$80
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0271
	ldy     #$00
	ldx     #$01
	lda     #$68
	jsr     addeqysp
L0271:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     L026B+3
	sta     sreg+1
	lda     L026B+2
	sta     sreg
	ldx     L026B+1
	lda     L026B
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L026D+3
	sta     sreg+1
	lda     L026D+2
	sta     sreg
	ldx     L026D+1
	lda     L026D
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L027B
	dey
L027B:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     L026D+3
	sta     sreg+1
	lda     L026D+2
	sta     sreg
	ldx     L026D+1
	lda     L026D
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L026B+3
	sta     sreg+1
	lda     L026B+2
	sta     sreg
	ldx     L026B+1
	lda     L026B
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0282
	dey
L0282:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_z (__near__ int *, __near__ int *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_z: near

.segment	"BSS"

L0284:
	.res	4,$00
L0286:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0284
	stx     L0284+1
	ldy     sreg
	sty     L0284+2
	ldy     sreg+1
	sty     L0284+3
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0286
	stx     L0286+1
	ldy     sreg
	sty     L0286+2
	ldy     sreg+1
	sty     L0286+3
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	cpx     #$80
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L028A
	ldy     #$00
	ldx     #$01
	lda     #$68
	jsr     addeqysp
L028A:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     L0284+3
	sta     sreg+1
	lda     L0284+2
	sta     sreg
	ldx     L0284+1
	lda     L0284
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0286+3
	sta     sreg+1
	lda     L0286+2
	sta     sreg
	ldx     L0286+1
	lda     L0286
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0294
	dey
L0294:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     L0284+3
	sta     sreg+1
	lda     L0284+2
	sta     sreg
	ldx     L0284+1
	lda     L0284
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0286+3
	sta     sreg+1
	lda     L0286+2
	sta     sreg
	ldx     L0286+1
	lda     L0286
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L029B
	dey
L029B:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ sort_scene (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sort_scene: near

.segment	"BSS"

L029D:
	.res	1,$00
L029E:
	.res	1,$00
L029F:
	.res	1,$00
L02A0:
	.res	19,$00

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     L029D
L02A1:	ldx     #$00
	lda     L029D
	jsr     pushax
	ldx     #$00
	lda     _total_faces
	jsr     decax1
	jsr     tosultax
	jne     L02A4
	jmp     L02A2
L02A4:	ldx     #$00
	lda     #$00
	sta     L029F
	ldx     #$00
	lda     #$00
	sta     L029E
L02AB:	ldx     #$00
	lda     L029E
	jsr     pushax
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     L029D
	jsr     tossubax
	jsr     decax1
	jsr     tosultax
	jne     L02AE
	jmp     L02AC
L02AE:	ldx     #$00
	lda     L029E
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$11
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L029E
	jsr     incax1
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$11
	jsr     ldaxidx
	jsr     tosltax
	jeq     L02AD
	lda     #<(L02A0)
	ldx     #>(L02A0)
	jsr     pushax
	ldx     #$00
	lda     L029E
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     _memcpy
	ldx     #$00
	lda     L029E
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     L029E
	jsr     incax1
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     _memcpy
	ldx     #$00
	lda     L029E
	jsr     incax1
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     #<(L02A0)
	ldx     #>(L02A0)
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     _memcpy
	ldx     #$00
	lda     #$01
	sta     L029F
L02AD:	ldx     #$00
	inc     L029E
	lda     L029E
	jmp     L02AB
L02AC:	ldx     #$00
	lda     L029F
	jsr     bnega
	jeq     L02A3
	jmp     L02A2
L02A3:	ldx     #$00
	inc     L029D
	lda     L029D
	jmp     L02A1
L02A2:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ delay (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay: near

.segment	"BSS"

L02C6:
	.res	2,$00
L02C7:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldx     #$00
	lda     #$00
	sta     L02C6
	stx     L02C6+1
L02C8:	lda     L02C6
	ldx     L02C6+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosultax
	jne     L02CB
	jmp     L02C9
L02CB:	lda     L02C6
	ldx     L02C6+1
	jsr     mulax3
	jsr     shrax1
	sta     L02C7
	stx     L02C7+1
	inc     L02C6
	bne     L02D0
	inc     L02C6+1
L02D0:	lda     L02C6
	ldx     L02C6+1
	jmp     L02C8
L02C9:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fill_triangle (int, int, int, int, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_triangle: near

.segment	"BSS"

L02D4:
	.res	2,$00
L02D5:
	.res	2,$00
L02D6:
	.res	2,$00
L02D7:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosgtax
	jeq     L02D8
	ldy     #$09
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	ldy     #$05
	jsr     ldaxysp
	ldy     #$08
	jsr     staxysp
	lda     L02D4
	ldx     L02D4+1
	ldy     #$04
	jsr     staxysp
	ldy     #$0B
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	ldy     #$07
	jsr     ldaxysp
	ldy     #$0A
	jsr     staxysp
	lda     L02D4
	ldx     L02D4+1
	ldy     #$06
	jsr     staxysp
L02D8:	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosgtax
	jeq     L02E6
	ldy     #$09
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	ldy     #$01
	jsr     ldaxysp
	ldy     #$08
	jsr     staxysp
	lda     L02D4
	ldx     L02D4+1
	ldy     #$00
	jsr     staxysp
	ldy     #$0B
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$0A
	jsr     staxysp
	lda     L02D4
	ldx     L02D4+1
	ldy     #$02
	jsr     staxysp
L02E6:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosgtax
	jeq     L02F4
	ldy     #$05
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	ldy     #$01
	jsr     ldaxysp
	ldy     #$04
	jsr     staxysp
	lda     L02D4
	ldx     L02D4+1
	ldy     #$00
	jsr     staxysp
	ldy     #$07
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$06
	jsr     staxysp
	lda     L02D4
	ldx     L02D4+1
	ldy     #$02
	jsr     staxysp
L02F4:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     toseqax
	jeq     L0302
	jmp     L0305
L0302:	ldy     #$09
	jsr     ldaxysp
	sta     L02D7
	stx     L02D7+1
L0304:	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosleax
	jne     L0307
	jmp     L0305
L0307:	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosltax
	jeq     L030D
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D5
	stx     L02D5+1
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D6
	stx     L02D6+1
	jmp     L031B
L030D:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     toseqax
	jeq     L031C
	ldy     #$07
	jsr     ldaxysp
	sta     L02D5
	stx     L02D5+1
	jmp     L0320
L031C:	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D5
	stx     L02D5+1
L0320:	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D6
	stx     L02D6+1
L031B:	lda     L02D5
	ldx     L02D5+1
	jsr     pushax
	lda     L02D7
	ldx     L02D7+1
	jsr     pushax
	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	lda     L02D7
	ldx     L02D7+1
	jsr     _tgi_line
	inc     L02D7
	bne     L030C
	inc     L02D7+1
L030C:	lda     L02D7
	ldx     L02D7+1
	jmp     L0304
L0305:	ldy     #$0C
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ render_scene (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_render_scene: near

.segment	"BSS"

L0333:
	.res	1,$00

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     L0333
L0334:	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     _total_faces
	jsr     tosultax
	jne     L0337
	jmp     L0335
L0337:	lda     #$00
	jsr     _tgi_setcolor
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$07
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$0B
	jsr     ldaxidx
	jsr     _fill_triangle
	lda     #$01
	jsr     _tgi_setcolor
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$07
	jsr     ldaxidx
	jsr     _tgi_line
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$07
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$0B
	jsr     ldaxidx
	jsr     _tgi_line
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0333
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     _tgi_line
	ldx     #$00
	inc     L0333
	lda     L0333
	jmp     L0334
L0335:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ add_to_scene (__near__ struct $anon-struct-0018 *, int, int, int, int, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_to_scene: near

.segment	"BSS"

L0369:
	.res	1,$00
L036A:
	.res	2,$00
L036B:
	.res	2,$00
L036C:
	.res	2,$00
L036D:
	.res	2,$00
L036E:
	.res	2,$00
L036F:
	.res	2,$00
L0370:
	.res	2,$00
L0371:
	.res	2,$00
L0372:
	.res	2,$00
L0373:
	.res	2,$00
L0374:
	.res	2,$00
L0375:
	.res	2,$00
L0376:
	.res	2,$00
L0377:
	.res	2,$00
L0378:
	.res	2,$00
L0379:
	.res	2,$00
L037A:
	.res	2,$00
L037B:
	.res	2,$00
L037C:
	.res	2,$00
L037D:
	.res	2,$00
L037E:
	.res	2,$00
L037F:
	.res	4,$00
L0380:
	.res	4,$00
L0381:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0370
	stx     L0370+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0371
	stx     L0371+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0D
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0372
	stx     L0372+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0D
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0373
	stx     L0373+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0374
	stx     L0374+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0375
	stx     L0375+1
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0376
	stx     L0376+1
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0377
	stx     L0377+1
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0378
	stx     L0378+1
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0379
	stx     L0379+1
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L037A
	stx     L037A+1
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L037B
	stx     L037B+1
	ldx     #$00
	lda     #$00
	sta     L0369
L03A6:	ldx     #$00
	lda     L0369
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     tosultax
	jne     L03A9
	jmp     L03A7
L03A9:	ldy     #$0D
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax6
	jsr     tosaddax
	ldy     #$01
	jsr     ldaxidx
	sta     L036A
	stx     L036A+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax6
	jsr     tosaddax
	ldy     #$03
	jsr     ldaxidx
	sta     L036B
	stx     L036B+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax6
	jsr     tosaddax
	ldy     #$05
	jsr     ldaxidx
	sta     L036C
	stx     L036C+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036C
	ldx     L036C+1
	sta     L036F
	stx     L036F+1
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0371
	ldx     L0371+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0370
	ldx     L0370+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03BF
	dey
L03BF:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0370
	ldx     L0370+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0371
	ldx     L0371+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03C4
	dey
L03C4:	sty     sreg+1
	sta     L036C
	stx     L036C+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036C
	ldx     L036C+1
	sta     L036F
	stx     L036F+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0373
	ldx     L0373+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0372
	ldx     L0372+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03CD
	dey
L03CD:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0373
	ldx     L0373+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0372
	ldx     L0372+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03D2
	dey
L03D2:	sty     sreg+1
	sta     L036C
	stx     L036C+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0375
	ldx     L0375+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0374
	ldx     L0374+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03DB
	dey
L03DB:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0374
	ldx     L0374+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0375
	ldx     L0375+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03E0
	dey
L03E0:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	clc
	adc     L036A
	sta     L036A
	txa
	adc     L036A+1
	sta     L036A+1
	tax
	lda     L036A
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$07
	jsr     ldaxidx
	clc
	adc     L036B
	sta     L036B
	txa
	adc     L036B+1
	sta     L036B+1
	tax
	lda     L036B
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$09
	jsr     ldaxidx
	clc
	adc     L036C
	sta     L036C
	txa
	adc     L036C+1
	sta     L036C+1
	tax
	lda     L036C
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036C
	ldx     L036C+1
	sta     L036F
	stx     L036F+1
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0377
	ldx     L0377+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0376
	ldx     L0376+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03EF
	dey
L03EF:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0376
	ldx     L0376+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0377
	ldx     L0377+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03F4
	dey
L03F4:	sty     sreg+1
	sta     L036C
	stx     L036C+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036C
	ldx     L036C+1
	sta     L036F
	stx     L036F+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0379
	ldx     L0379+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0378
	ldx     L0378+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03FD
	dey
L03FD:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     pusheax
	lda     L0379
	ldx     L0379+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0378
	ldx     L0378+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0402
	dey
L0402:	sty     sreg+1
	sta     L036C
	stx     L036C+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L037B
	ldx     L037B+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L037A
	ldx     L037A+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L040B
	dey
L040B:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L037A
	ldx     L037A+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L037B
	ldx     L037B+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0410
	dey
L0410:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	lda     L036A
	ldx     L036A+1
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxspidx
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	lda     L036B
	ldx     L036B+1
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$02
	jsr     staxspidx
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	lda     L036C
	ldx     L036C+1
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$04
	jsr     staxspidx
	ldx     #$00
	inc     L0369
	lda     L0369
	jmp     L03A6
L03A7:	ldx     #$00
	lda     #$00
	sta     L0369
L041A:	ldx     #$00
	lda     L0369
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     tosultax
	jne     L041D
	jmp     L041B
L041D:	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax3
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     mulax6
	jsr     tosaddax
	sta     L037C
	stx     L037C+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax3
	jsr     tosaddax
	ldy     #$01
	jsr     ldauidx
	jsr     mulax6
	jsr     tosaddax
	sta     L037D
	stx     L037D+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0369
	jsr     mulax3
	jsr     tosaddax
	ldy     #$02
	jsr     ldauidx
	jsr     mulax6
	jsr     tosaddax
	sta     L037E
	stx     L037E+1
	lda     L037D
	ldx     L037D+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	sta     L037F
	stx     L037F+1
	ldy     sreg
	sty     L037F+2
	ldy     sreg+1
	sty     L037F+3
	lda     L037D
	ldx     L037D+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	sta     L0380
	stx     L0380+1
	ldy     sreg
	sty     L0380+2
	ldy     sreg+1
	sty     L0380+3
	lda     L037D
	ldx     L037D+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	sta     L0381
	stx     L0381+1
	ldy     sreg
	sty     L0381+2
	ldy     sreg+1
	sty     L0381+3
	lda     L0381+3
	sta     sreg+1
	lda     L0381+2
	sta     sreg
	ldx     L0381+1
	lda     L0381
	lda     sreg+1
	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0442
	ldx     #$00
	lda     _total_faces
	ldx     #$00
	lda     #$01
	jne     L0441
L0442:	ldx     #$00
	lda     #$00
	jeq     L0443
L0441:	ldx     #$00
	lda     #$01
L0443:	jeq     L041C
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	ldy     #$02
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037D
	ldx     L037D+1
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037D
	ldx     L037D+1
	ldy     #$03
	jsr     ldaxidx
	ldy     #$06
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037E
	ldx     L037E+1
	ldy     #$01
	jsr     ldaxidx
	ldy     #$08
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037E
	ldx     L037E+1
	ldy     #$03
	jsr     ldaxidx
	ldy     #$0A
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$05
	jsr     ldaxidx
	jsr     axlong
	jsr     tosaddeax
	jsr     pusheax
	lda     L037E
	ldx     L037E+1
	ldy     #$05
	jsr     ldaxidx
	jsr     axlong
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$03
	jsr     tosdiveax
	ldy     #$10
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$10
	jsr     ldauidx
	ldy     #$12
	jsr     staspidx
	ldx     #$00
	lda     _total_faces
	inc     _total_faces
L041C:	ldx     #$00
	inc     L0369
	lda     L0369
	jmp     L041A
L041B:	ldy     #$0E
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L0460:
	.res	2,$00
L0461:
	.res	2,$00
L0462:
	.res	2,$00
L0463:
	.res	2,$00
L0464:
	.res	2,$00
L0465:
	.res	2,$00
L0466:
	.res	2,$00
L0468:
	.res	2,$00
L0469:
	.res	2,$00
L046B:
	.res	2,$00
L046D:
	.res	2,$00
L046F:
	.res	2,$00
L0470:
	.res	2,$00
L0472:
	.res	2,$00
L0474:
	.res	2,$00
L0476:
	.res	2,$00
L0478:
	.res	2,$00
L047A:
	.res	2,$00
L047C:
	.res	6,$00
L047D:
	.res	6,$00
L047E:
	.res	17,$00
L047F:
	.res	17,$00
L0480:
	.res	17,$00
L0482:
	.res	288,$00
L0484:
	.res	192,$00
L0485:
	.res	6,$00
L0486:
	.res	17,$00
L0488:
	.res	288,$00
L048A:
	.res	192,$00
L048B:
	.res	6,$00

.segment	"CODE"

	ldx     #$00
	lda     #$01
	sta     L0466
	stx     L0466+1
	ldx     #$00
	lda     #$5A
	sta     L0469
	stx     L0469+1
	ldx     #$00
	lda     #$2D
	sta     L046B
	stx     L046B+1
	ldx     #$00
	lda     #$00
	sta     L046D
	stx     L046D+1
	ldx     #$4E
	lda     #$20
	sta     L0470
	stx     L0470+1
	ldx     #$00
	lda     #$00
	sta     L0472
	stx     L0472+1
	ldx     #$00
	lda     #$00
	sta     L0474
	stx     L0474+1
	ldx     #$00
	lda     #$00
	sta     L0476
	stx     L0476+1
	ldx     #$00
	lda     #$00
	sta     L0478
	stx     L0478+1
	ldx     #$00
	lda     #$00
	sta     L047A
	stx     L047A+1
	lda     #<(_torroid_points)
	ldx     #>(_torroid_points)
	sta     L047C
	stx     L047C+1
	lda     #<(_torroid_faces_tri)
	ldx     #>(_torroid_faces_tri)
	sta     L047C+2
	stx     L047C+2+1
	ldx     #$00
	lda     #$20
	sta     L047C+4
	ldx     #$00
	lda     #$40
	sta     L047C+5
	lda     #<(_pyramid_points)
	ldx     #>(_pyramid_points)
	sta     L047D
	stx     L047D+1
	lda     #<(_pyramid_tris)
	ldx     #>(_pyramid_tris)
	sta     L047D+2
	stx     L047D+2+1
	ldx     #$00
	lda     #$05
	sta     L047D+4
	ldx     #$00
	lda     #$06
	sta     L047D+5
	lda     #<(L047C)
	ldx     #>(L047C)
	sta     L047E
	stx     L047E+1
	ldx     #$FF
	lda     #$D8
	sta     L047E+4
	stx     L047E+4+1
	ldx     #$00
	lda     #$00
	sta     L047E+6
	stx     L047E+6+1
	ldx     #$00
	lda     #$00
	sta     L047E+8
	stx     L047E+8+1
	ldx     #$00
	lda     #$00
	sta     L047E+10
	stx     L047E+10+1
	ldx     #$00
	lda     #$00
	sta     L047E+12
	stx     L047E+12+1
	ldx     #$00
	lda     #$00
	sta     L047E+14
	stx     L047E+14+1
	ldx     #$00
	lda     #$00
	sta     L047E+16
	lda     L0474
	ldx     L0474+1
	sta     L047E+2
	stx     L047E+2+1
	lda     #<(L047D)
	ldx     #>(L047D)
	sta     L047F
	stx     L047F+1
	ldx     #$00
	lda     #$00
	sta     L047F+4
	stx     L047F+4+1
	ldx     #$00
	lda     #$00
	sta     L047F+6
	stx     L047F+6+1
	ldx     #$00
	lda     #$00
	sta     L047F+8
	stx     L047F+8+1
	ldx     #$00
	lda     #$5A
	sta     L047F+10
	stx     L047F+10+1
	ldx     #$00
	lda     #$00
	sta     L047F+12
	stx     L047F+12+1
	ldx     #$00
	lda     #$00
	sta     L047F+14
	stx     L047F+14+1
	ldx     #$00
	lda     #$01
	sta     L047F+16
	ldx     #$00
	lda     L047D+4
	jsr     mulax6
	jsr     _malloc
	sta     L0476
	stx     L0476+1
	lda     L0476
	ldx     L0476+1
	jsr     bnegax
	jeq     L04C1
	lda     #<(L04C4)
	ldx     #>(L04C4)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$01
	jmp     L045F
L04C1:	lda     L0476
	ldx     L0476+1
	sta     L047F+2
	stx     L047F+2+1
	ldx     #$00
	lda     L047C+4
	jsr     mulax6
	jsr     _malloc
	sta     L0474
	stx     L0474+1
	lda     L0474
	ldx     L0474+1
	jsr     bnegax
	jeq     L04CC
	lda     #<(L04CF)
	ldx     #>(L04CF)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$01
	jmp     L045F
L04CC:	lda     L0474
	ldx     L0474+1
	sta     L047E+2
	stx     L047E+2+1
	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
	jsr     _tgi_init
	jsr     _tgi_clear
	ldx     #$00
	lda     #$00
	sta     _total_faces
	lda     #<(L047F)
	ldx     #>(L047F)
	jsr     pushax
	ldx     #$00
	lda     #$82
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     pushax
	lda     L0469
	ldx     L0469+1
	jsr     pushax
	lda     L046B
	ldx     L046B+1
	jsr     pushax
	lda     L046D
	ldx     L046D+1
	jsr     _add_to_scene
	jsr     _sort_scene
	jsr     _render_scene
	lda     L047F+2
	ldx     L047F+2+1
	jsr     _free
	lda     L047E+2
	ldx     L047E+2+1
	jsr     _free
	jsr     _tgi_clear
	jsr     _tgi_uninstall
	jsr     _clrscr
	lda     #<(L04EC)
	ldx     #>(L04EC)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$08
	sta     L0468
	stx     L0468+1
	lda     #<(L04F2)
	ldx     #>(L04F2)
	jsr     pushax
	lda     L0468
	ldx     L0468+1
	jsr     pushax
	lda     #<(L047D)
	ldx     #>(L047D)
	jsr     _save_model
	stx     tmp1
	ora     tmp1
	jeq     L04F0
	lda     #<(L04F7)
	ldx     #>(L04F7)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L04F9
L04F0:	lda     #<(L04FB)
	ldx     #>(L04FB)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	sta     L0466
	stx     L0466+1
L04F9:	lda     #<(L0501)
	ldx     #>(L0501)
	jsr     pushax
	lda     L0468
	ldx     L0468+1
	jsr     pushax
	lda     #<(L047C)
	ldx     #>(L047C)
	jsr     _save_model
	stx     tmp1
	ora     tmp1
	jeq     L04FF
	lda     #<(L0506)
	ldx     #>(L0506)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L0508
L04FF:	lda     #<(L050A)
	ldx     #>(L050A)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	sta     L0466
	stx     L0466+1
L0508:	lda     #<(L0510)
	ldx     #>(L0510)
	jsr     pushax
	lda     L0468
	jsr     _load_object
	sta     L0464
	stx     L0464+1
	lda     L0464
	ldx     L0464+1
	txa
	jsr     boolge
	jeq     L0513
	lda     #<(L0516)
	ldx     #>(L0516)
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0513:	lda     #<(L051F)
	ldx     #>(L051F)
	jsr     pushax
	lda     L0468
	jsr     _load_object
	sta     L0464
	stx     L0464+1
	lda     L0464
	ldx     L0464+1
	txa
	jsr     boolge
	jeq     L0522
	lda     #<(L0525)
	ldx     #>(L0525)
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0522:	lda     #<(L052E)
	ldx     #>(L052E)
	jsr     pushax
	lda     L0468
	jsr     _load_object
	sta     L0464
	stx     L0464+1
	lda     L0464
	ldx     L0464+1
	txa
	jsr     boolge
	jeq     L0531
	lda     #<(L0534)
	ldx     #>(L0534)
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0531:	lda     #<(L053D)
	ldx     #>(L053D)
	jsr     pushax
	lda     L0468
	jsr     _load_object
	sta     L0464
	stx     L0464+1
	lda     L0464
	ldx     L0464+1
	txa
	jsr     boolge
	jeq     L0540
	lda     #<(L0543)
	ldx     #>(L0543)
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0540:	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
	jsr     _tgi_init
	jsr     _tgi_clear
	ldx     #$00
	lda     #$00
	sta     _total_faces
	ldx     #$00
	lda     #$00
	sta     L0463
	stx     L0463+1
L0550:	lda     L0463
	ldx     L0463+1
	jsr     pushax
	lda     _object_count
	ldx     _object_count+1
	jsr     tosltax
	jne     L0553
	jmp     L0551
L0553:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$04
	jsr     staxspidx
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$06
	jsr     staxspidx
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxspidx
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$5A
	ldy     #$0A
	jsr     staxspidx
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0C
	jsr     staxspidx
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0E
	jsr     staxspidx
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$82
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     pushax
	lda     L0469
	ldx     L0469+1
	jsr     pushax
	lda     L046B
	ldx     L046B+1
	jsr     pushax
	lda     L046D
	ldx     L046D+1
	jsr     _add_to_scene
	inc     L0463
	bne     L0558
	inc     L0463+1
L0558:	lda     L0463
	ldx     L0463+1
	jmp     L0550
L0551:	lda     #<(L0575)
	ldx     #>(L0575)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     _sort_scene
	lda     #<(L0579)
	ldx     #>(L0579)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     _render_scene
	lda     L0466
	ora     L0466+1
	jeq     L057C
	lda     #<(L057F)
	ldx     #>(L057F)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L0581
L057C:	lda     #<(L0583)
	ldx     #>(L0583)
	jsr     pushax
	ldy     #$02
	jsr     _printf
L0581:	ldx     #$00
	lda     #$00
	sta     L0462
	stx     L0462+1
	ldx     #$00
	lda     #$02
	sta     L0461
	stx     L0461+1
	ldx     #$00
	lda     #$00
	sta     L0460
	stx     L0460+1
	jmp     L058D
L058B:	inc     L0462
	bne     L0591
	inc     L0462+1
L0591:	lda     L0462
	ldx     L0462+1
	jsr     _tgi_clear
	jsr     _tgi_uninstall
	ldx     #$00
	lda     #$00
	sta     L0460
	stx     L0460+1
L0594:	lda     L0460
	ldx     L0460+1
	jsr     pushax
	lda     L0461
	ldx     L0461+1
	jsr     tosltax
	jne     L0597
	jmp     L0595
L0597:	lda     #<(L059E)
	ldx     #>(L059E)
	jsr     pushax
	lda     L0468
	jsr     _load_object
	sta     L0464
	stx     L0464+1
	lda     L0464
	ldx     L0464+1
	txa
	jsr     boolge
	jeq     L05A1
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0460
	ldx     L0460+1
	jsr     pushax
	ldx     #$00
	lda     #$1E
	jsr     tosmulax
	jsr     pushax
	ldx     #$FF
	lda     #$B0
	jsr     tosaddax
	ldy     #$04
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0460
	ldx     L0460+1
	jsr     pushax
	ldx     #$00
	lda     #$16
	jsr     tosmulax
	ldy     #$06
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0460
	ldx     L0460+1
	jsr     aslax4
	jsr     aslax1
	ldy     #$08
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0A
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0C
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0E
	jsr     staxspidx
	lda     #<(L05B9)
	ldx     #>(L05B9)
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	ldy     #$06
	jsr     _printf
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$82
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     pushax
	lda     L0469
	ldx     L0469+1
	jsr     pushax
	lda     L046B
	ldx     L046B+1
	jsr     pushax
	lda     L046D
	ldx     L046D+1
	jsr     _add_to_scene
L05A1:	lda     #<(L05CA)
	ldx     #>(L05CA)
	jsr     pushax
	lda     L0468
	jsr     _load_object
	sta     L0464
	stx     L0464+1
	lda     L0464
	ldx     L0464+1
	txa
	jsr     boolge
	jeq     L0596
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$28
	ldy     #$04
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L0460
	ldx     L0460+1
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     tosmulax
	ldy     #$06
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0A
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0C
	jsr     staxspidx
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0E
	jsr     staxspidx
	lda     #<(L05E3)
	ldx     #>(L05E3)
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	ldy     #$06
	jsr     _printf
	lda     L0464
	ldx     L0464+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$82
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     pushax
	lda     L0469
	ldx     L0469+1
	jsr     pushax
	lda     L046B
	ldx     L046B+1
	jsr     pushax
	lda     L046D
	ldx     L046D+1
	jsr     _add_to_scene
L0596:	lda     L0460
	ldx     L0460+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L0460
	stx     L0460+1
	lda     regsave
	ldx     regsave+1
	jmp     L0594
L0595:	lda     #<(L05F3)
	ldx     #>(L05F3)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$4E
	lda     #$20
	sta     L0470
	stx     L0470+1
	jmp     L05F9
L05F7:	lda     L0470
	ldx     L0470+1
	jsr     _malloc
	sta     L046F
	stx     L046F+1
	lda     L046F
	ora     L046F+1
	jeq     L05FE
	lda     L046F
	ldx     L046F+1
	jsr     _free
	jmp     L05F8
L05FE:	lda     L0470
	sec
	sbc     #$00
	sta     L0470
	lda     L0470+1
	sbc     #$04
	sta     L0470+1
	tax
	lda     L0470
L05F9:	lda     L0470
	ldx     L0470+1
	cmp     #$01
	txa
	sbc     #$04
	lda     #$00
	ldx     #$00
	rol     a
	jne     L05F7
L05F8:	ldx     #$00
	lda     #$00
	sta     L0463
	stx     L0463+1
L0604:	lda     L0463
	ldx     L0463+1
	jsr     pushax
	lda     _object_count
	ldx     _object_count+1
	jsr     tosltax
	jne     L0607
	jmp     L0605
L0607:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L0606
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldy     #$05
	jsr     ldaxidx
	ldy     #$0F
	jsr     incaxy
	ldy     #$04
	jsr     staxspidx
L0606:	inc     L0463
	bne     L060C
	inc     L0463+1
L060C:	lda     L0463
	ldx     L0463+1
	jmp     L0604
L0605:	jsr     _objectstateprint
	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
	jsr     _tgi_init
	jsr     _tgi_clear
	jsr     _sort_scene
	jsr     _render_scene
	ldx     #$00
	lda     #$00
	sta     L0463
	stx     L0463+1
L061A:	lda     L0463
	ldx     L0463+1
	jsr     pushax
	lda     _object_count
	ldx     _object_count+1
	jsr     tosltax
	jne     L061D
	jmp     L061B
L061D:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     bnegax
	jeq     L0623
	jmp     L061C
L0623:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L0626
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxspidx
L0626:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L062F
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L0632
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxspidx
L0632:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L063B
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxspidx
L063B:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxspidx
L062F:	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxspidx
L061C:	inc     L0463
	bne     L0622
	inc     L0463+1
L0622:	lda     L0463
	ldx     L0463+1
	jmp     L061A
L061B:	ldx     #$00
	lda     #$00
	sta     _object_count
	stx     _object_count+1
	lda     L0472
	ldx     L0472+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L0472
	stx     L0472+1
	lda     regsave
	ldx     regsave+1
	lda     #<(L0654)
	ldx     #>(L0654)
	jsr     pushax
	lda     L0472
	ldx     L0472+1
	jsr     pushax
	lda     L0470
	ldx     L0470+1
	jsr     pushax
	ldy     #$06
	jsr     _printf
	ldx     #$4E
	lda     #$20
	sta     L0470
	stx     L0470+1
	jmp     L065C
L065A:	lda     L0470
	ldx     L0470+1
	jsr     _malloc
	sta     L046F
	stx     L046F+1
	lda     L046F
	ora     L046F+1
	jeq     L0661
	lda     L046F
	ldx     L046F+1
	jsr     _free
	jmp     L065B
L0661:	lda     L0470
	sec
	sbc     #$00
	sta     L0470
	lda     L0470+1
	sbc     #$04
	sta     L0470+1
	tax
	lda     L0470
L065C:	lda     L0470
	ldx     L0470+1
	cmp     #$01
	txa
	sbc     #$04
	lda     #$00
	ldx     #$00
	rol     a
	jne     L065A
L065B:	lda     #<(L0668)
	ldx     #>(L0668)
	jsr     pushax
	lda     L0472
	ldx     L0472+1
	jsr     pushax
	lda     L0470
	ldx     L0470+1
	jsr     pushax
	ldy     #$06
	jsr     _printf
L058D:	lda     L0470
	ldx     L0470+1
	cmp     #$01
	txa
	sbc     #$04
	lda     #$00
	ldx     #$00
	rol     a
	jne     L058B
	ldx     #$00
	lda     #$00
	sta     $00C6
	jsr     _tgi_uninstall
	lda     #<(L0670)
	ldx     #>(L0670)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	jmp     L045F
L045F:	rts

.endproc

