;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_cputs
	.import		_snprintf
	.export		_print_status
	.export		_init_acia
	.export		_main

.segment	"RODATA"

L0149:
	.byte	$D7,$41,$49,$54,$49,$4E,$47,$20,$46,$4F,$52,$20,$23,$23,$23,$20
	.byte	$54,$4F,$20,$53,$54,$41,$52,$54,$20,$52,$45,$43,$4F,$52,$44,$49
	.byte	$4E,$47,$2E,$2E,$2E,$00
L01BE:
	.byte	$C2,$55,$46,$46,$45,$52,$20,$4F,$56,$45,$52,$46,$4C,$4F,$57,$21
	.byte	$20,$D2,$45,$53,$45,$54,$54,$49,$4E,$47,$2E,$00
L0175:
	.byte	$D2,$45,$43,$4F,$52,$44,$49,$4E,$47,$20,$53,$54,$41,$52,$54,$45
	.byte	$44,$2E,$2E,$2E,$00
L0145:
	.byte	$D3,$57,$49,$46,$54,$4C,$49,$4E,$4B,$20,$D2,$D8,$20,$C4,$45,$4D
	.byte	$4F,$0D,$0A,$00
L01A8:
	.byte	$C3,$4F,$55,$4E,$54,$3A,$20,$25,$55,$20,$43,$48,$41,$52,$53,$00
L0196:
	.byte	$D2,$45,$43,$45,$49,$56,$45,$44,$3A,$00
L0179	:=	L0149+37
L01C2	:=	L0149+37
L014D	:=	L0149+37

.segment	"BSS"

_recv_buffer:
	.res	256,$00
_count_str:
	.res	40,$00

; ---------------------------------------------------------------
; void __near__ print_status (__near__ const unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_status: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     tosumulax
	jsr     pushax
	jsr     decsp1
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
L010C:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$28
	jsr     boolult
	jne     L010F
	jmp     L010D
L010F:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	cmp     #$00
	jsr     booleq
	jeq     L0114
	jmp     L010D
L0114:	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldx     #$04
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	ldy     #$00
	jsr     staspidx
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldx     #$D8
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$15
	ldy     #$00
	jsr     staspidx
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$00
	sta     (sp),y
	pla
	jmp     L010C
L010D:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	cmp     #$28
	jsr     boolult
	jne     L0125
	jmp     L0123
L0125:	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldx     #$04
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$20
	ldy     #$00
	jsr     staspidx
	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	ldx     #$D8
	lda     #$00
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$15
	ldy     #$00
	jsr     staspidx
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$00
	sta     (sp),y
	pla
	jmp     L010D
L0123:	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ init_acia (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_acia: near

.segment	"CODE"

	ldx     #$00
	lda     #$0B
	sta     $DE02
	ldx     #$00
	lda     #$0C
	sta     $DE03
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	lda     #$00
	jsr     pushax
	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #$00
	jsr     pusha
	jsr     _clrscr
	lda     #<(L0145)
	ldx     #>(L0145)
	jsr     _cputs
	jsr     _init_acia
	lda     #<(L0149)
	ldx     #>(L0149)
	jsr     pushax
	lda     #$16
	jsr     _print_status
	lda     #<(L014D)
	ldx     #>(L014D)
	jsr     pushax
	lda     #$17
	jsr     _print_status
	jmp     L01BB
L0150:	ldx     #$00
	lda     $DE01
	ldx     #$00
	and     #$08
	stx     tmp1
	ora     tmp1
	jeq     L0159
	ldx     #$00
	lda     #$01
	jmp     L015B
L0159:	ldx     #$00
	lda     #$00
L015B:	ldx     #$00
	ldy     #$08
	sta     (sp),y
	ldy     #$08
	lda     (sp),y
	jeq     L01BB
	ldx     #$00
	lda     $DE00
	ldy     #$07
	sta     (sp),y
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	cmp     #$1C
	jsr     booleq
	jeq     L0163
	jmp     L01BB
L0163:	ldy     #$00
	ldx     #$00
	lda     (sp),y
	jsr     bnega
	jeq     L0165
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	cmp     #$23
	jsr     booleq
	jeq     L0167
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$02
	sta     (sp),y
	pla
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	cmp     #$03
	jsr     booleq
	jeq     L016A
	ldx     #$00
	lda     #$01
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$05
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
	lda     #<(L0175)
	ldx     #>(L0175)
	jsr     pushax
	lda     #$16
	jsr     _print_status
	lda     #<(L0179)
	ldx     #>(L0179)
	jsr     pushax
	lda     #$17
	jsr     _print_status
L016A:	jmp     L017C
L0167:	ldx     #$00
	lda     #$00
	ldy     #$02
	sta     (sp),y
L017C:	jmp     L01BB
L0165:	ldy     #$06
	jsr     ldaxysp
	cpx     #$00
	bne     L0182
	cmp     #$FF
L0182:	jsr     boolult
	jeq     L0180
	ldy     #$06
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$05
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	clc
	adc     #<(_recv_buffer)
	tay
	txa
	adc     #>(_recv_buffer)
	tax
	tya
	jsr     pushax
	ldy     #$09
	ldx     #$00
	lda     (sp),y
	ldy     #$00
	jsr     staspidx
	ldy     #$04
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$03
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
L0180:	ldy     #$07
	ldx     #$00
	lda     (sp),y
	cmp     #$24
	jsr     booleq
	jeq     L0187
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	pha
	clc
	adc     #$01
	ldy     #$01
	sta     (sp),y
	pla
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	cmp     #$03
	jsr     booleq
	jeq     L018A
	ldx     #$00
	lda     #$03
	ldy     #$05
	jsr     subeqysp
	ldy     #$06
	jsr     ldaxysp
	cmp     #$00
	txa
	sbc     #$01
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L018E
	ldx     #$00
	lda     #$FF
	ldy     #$05
	jsr     staxysp
L018E:	lda     #<(_recv_buffer)
	ldx     #>(_recv_buffer)
	ldy     #$05
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staspidx
	lda     #<(L0196)
	ldx     #>(L0196)
	jsr     pushax
	lda     #$16
	jsr     _print_status
	jsr     decsp2
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0199:	ldy     #$01
	jsr     ldaxysp
	jsr     axulong
	cmp     #$50
	txa
	sbc     #$C3
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	jsr     boolult
	jne     L019B
	jmp     L019A
L019B:	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0199
L019A:	jsr     incsp2
	lda     #<(_recv_buffer)
	ldx     #>(_recv_buffer)
	jsr     pushax
	lda     #$16
	jsr     _print_status
	lda     #<(_count_str)
	ldx     #>(_count_str)
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	lda     #<(L01A8)
	ldx     #>(L01A8)
	jsr     pushax
	ldy     #$0A
	jsr     ldaxysp
	jsr     pushax
	ldy     #$08
	jsr     _snprintf
	lda     #<(_count_str)
	ldx     #>(_count_str)
	jsr     pushax
	lda     #$17
	jsr     _print_status
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$05
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$03
	jsr     staxysp
L018A:	jmp     L01B8
L0187:	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
L01B8:	ldy     #$06
	jsr     ldaxysp
	cmp     #$FF
	txa
	sbc     #$00
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L01BB
	lda     #<(L01BE)
	ldx     #>(L01BE)
	jsr     pushax
	lda     #$16
	jsr     _print_status
	lda     #<(L01C2)
	ldx     #>(L01C2)
	jsr     pushax
	lda     #$17
	jsr     _print_status
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$05
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	lda     #$00
	ldy     #$02
	sta     (sp),y
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (sp),y
L01BB:	jmp     L0150
	ldx     #$00
	lda     #$00
	jmp     L013D
L013D:	ldy     #$09
	jsr     addysp
	rts

.endproc

