;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_cputs
	.export		_start_seq
	.export		_init_acia
	.export		_send_string
	.export		_main

.segment	"RODATA"

_start_seq:
	.byte	$23
	.byte	$00
L0128:
	.byte	$D3,$57,$49,$46,$54,$CC,$49,$4E,$4B,$20,$D4,$D8,$3A,$20,$D3,$45
	.byte	$4E,$44,$49,$4E,$47,$20,$54,$45,$53,$54,$20,$50,$41,$54,$54,$45
	.byte	$52,$4E,$2E,$2E,$2E,$0D,$0A,$00
L0138:
	.byte	$D3,$54,$41,$52,$54,$20,$50,$41,$54,$54,$45,$52,$4E,$20,$53,$45
	.byte	$4E,$54,$2E,$2E,$2E,$0D,$0A,$00
L013E:
	.byte	$54,$45,$53,$54,$20,$50,$48,$52,$41,$53,$45,$20,$53,$45,$4E,$54
	.byte	$2E,$2E,$2E,$0D,$0A,$00
L013B:
	.byte	$D4,$C5,$D3,$D4,$20,$D0,$C8,$D2,$C1,$D3,$C5,$00
L0144:
	.byte	$45,$4E,$44,$2E,$2E,$2E,$0D,$0A,$00
L0147:
	.byte	$C4,$4F,$4E,$45,$2E,$0D,$0A,$00
L0141:
	.byte	$24,$24,$24,$00
L012C:
	.byte	$41,$00
L0135:
	.byte	$23,$00
L012F	:=	L0135+0
L0132	:=	L0135+0

; ---------------------------------------------------------------
; void __near__ init_acia (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_acia: near

.segment	"CODE"

	lda     #$0B
	sta     $DE02
	lda     #$0C
	sta     $DE03
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ send_string (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_send_string: near

.segment	"CODE"

	jsr     pushax
	jmp     L0116
L0114:	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	jsr     stax0sp
	ldy     #$00
	lda     (regsave),y
	sta     $DE00
	jsr     decsp2
	ldx     #$00
	txa
	jsr     stax0sp
L011C:	jsr     ldax0sp
	cmp     #$58
	txa
	sbc     #$1B
	bvc     L0123
	eor     #$80
L0123:	bpl     L011D
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L011C
L011D:	jsr     incsp2
L0116:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0114
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _clrscr
	lda     #<(L0128)
	ldx     #>(L0128)
	jsr     _cputs
	jsr     _init_acia
	lda     #<(L012C)
	ldx     #>(L012C)
	jsr     _send_string
	lda     #<(L012F)
	ldx     #>(L012F)
	jsr     _send_string
	lda     #<(L0132)
	ldx     #>(L0132)
	jsr     _send_string
	lda     #<(L0135)
	ldx     #>(L0135)
	jsr     _send_string
	lda     #<(L0138)
	ldx     #>(L0138)
	jsr     _cputs
	lda     #<(L013B)
	ldx     #>(L013B)
	jsr     _send_string
	lda     #<(L013E)
	ldx     #>(L013E)
	jsr     _cputs
	lda     #<(L0141)
	ldx     #>(L0141)
	jsr     _send_string
	lda     #<(L0144)
	ldx     #>(L0144)
	jsr     _cputs
	lda     #<(L0147)
	ldx     #>(L0147)
	jsr     _cputs
L014E:	jmp     L014E

.endproc

