;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_clrscr
	.import		_tgi_static_stddrv
	.import		_tgi_install
	.import		_tgi_uninstall
	.import		_tgi_init
	.import		_tgi_clear
	.import		_tgi_setcolor
	.import		_tgi_line
	.import		_printf
	.import		_malloc
	.import		_free
	.import		__heapmemavail
	.import		_cosine
	.import		_sine
	.import		_objects
	.import		_save_model
	.import		_load_object
	.import		_objectstateprint
	.import		_object_count
	.export		_transformed
	.export		_sort_list
	.export		_foreground_box
	.export		_total_faces
	.export		_rotX
	.export		_rotY
	.export		_rotZ
	.export		_torroid_points
	.export		_torroid_faces_tri
	.export		_pyramid_points
	.export		_pyramid_tris
	.export		_rotate_x
	.export		_rotate_y
	.export		_rotate_z
	.export		_sort_scene
	.export		_delay
	.export		_fill_triangle
	.export		_render_scene
	.export		_add_to_scene
	.export		_main

.segment	"DATA"

_torroid_points:
	.word	$003C
	.word	$0000
	.word	$0000
	.word	$0028
	.word	$0014
	.word	$0000
	.word	$0014
	.word	$0000
	.word	$0000
	.word	$0028
	.word	$FFEC
	.word	$0000
	.word	$002A
	.word	$0000
	.word	$002A
	.word	$001C
	.word	$000E
	.word	$001C
	.word	$000E
	.word	$0000
	.word	$000E
	.word	$001C
	.word	$FFF2
	.word	$001C
	.word	$0000
	.word	$0000
	.word	$003C
	.word	$0000
	.word	$0014
	.word	$0028
	.word	$0000
	.word	$0000
	.word	$0014
	.word	$0000
	.word	$FFEC
	.word	$0028
	.word	$FFD6
	.word	$0000
	.word	$002A
	.word	$FFE4
	.word	$000E
	.word	$001C
	.word	$FFF2
	.word	$0000
	.word	$000E
	.word	$FFE4
	.word	$FFF2
	.word	$001C
	.word	$FFC4
	.word	$0000
	.word	$0000
	.word	$FFD8
	.word	$0014
	.word	$0000
	.word	$FFEC
	.word	$0000
	.word	$0000
	.word	$FFD8
	.word	$FFEC
	.word	$0000
	.word	$FFD6
	.word	$0000
	.word	$FFD6
	.word	$FFE4
	.word	$000E
	.word	$FFE4
	.word	$FFF2
	.word	$0000
	.word	$FFF2
	.word	$FFE4
	.word	$FFF2
	.word	$FFE4
	.word	$0000
	.word	$0000
	.word	$FFC4
	.word	$0000
	.word	$0014
	.word	$FFD8
	.word	$0000
	.word	$0000
	.word	$FFEC
	.word	$0000
	.word	$FFEC
	.word	$FFD8
	.word	$002A
	.word	$0000
	.word	$FFD6
	.word	$001C
	.word	$000E
	.word	$FFE4
	.word	$000E
	.word	$0000
	.word	$FFF2
	.word	$001C
	.word	$FFF2
	.word	$FFE4
	.res	96,$00
_torroid_faces_tri:
	.byte	$00
	.byte	$01
	.byte	$05
	.byte	$00
	.byte	$05
	.byte	$04
	.byte	$01
	.byte	$02
	.byte	$06
	.byte	$01
	.byte	$06
	.byte	$05
	.byte	$02
	.byte	$03
	.byte	$07
	.byte	$02
	.byte	$07
	.byte	$06
	.byte	$03
	.byte	$00
	.byte	$04
	.byte	$03
	.byte	$04
	.byte	$07
	.byte	$04
	.byte	$05
	.byte	$09
	.byte	$04
	.byte	$09
	.byte	$08
	.byte	$05
	.byte	$06
	.byte	$0A
	.byte	$05
	.byte	$0A
	.byte	$09
	.byte	$06
	.byte	$07
	.byte	$0B
	.byte	$06
	.byte	$0B
	.byte	$0A
	.byte	$07
	.byte	$04
	.byte	$08
	.byte	$07
	.byte	$08
	.byte	$0B
	.byte	$08
	.byte	$09
	.byte	$0D
	.byte	$08
	.byte	$0D
	.byte	$0C
	.byte	$09
	.byte	$0A
	.byte	$0E
	.byte	$09
	.byte	$0E
	.byte	$0D
	.byte	$0A
	.byte	$0B
	.byte	$0F
	.byte	$0A
	.byte	$0F
	.byte	$0E
	.byte	$0B
	.byte	$08
	.byte	$0C
	.byte	$0B
	.byte	$0C
	.byte	$0F
	.byte	$0C
	.byte	$0D
	.byte	$11
	.byte	$0C
	.byte	$11
	.byte	$10
	.byte	$0D
	.byte	$0E
	.byte	$12
	.byte	$0D
	.byte	$12
	.byte	$11
	.byte	$0E
	.byte	$0F
	.byte	$13
	.byte	$0E
	.byte	$13
	.byte	$12
	.byte	$0F
	.byte	$0C
	.byte	$10
	.byte	$0F
	.byte	$10
	.byte	$13
	.byte	$10
	.byte	$11
	.byte	$15
	.byte	$10
	.byte	$15
	.byte	$14
	.byte	$11
	.byte	$12
	.byte	$16
	.byte	$11
	.byte	$16
	.byte	$15
	.byte	$12
	.byte	$13
	.byte	$17
	.byte	$12
	.byte	$17
	.byte	$16
	.byte	$13
	.byte	$10
	.byte	$14
	.byte	$13
	.byte	$14
	.byte	$17
	.byte	$14
	.byte	$15
	.byte	$19
	.byte	$14
	.byte	$19
	.byte	$18
	.byte	$15
	.byte	$16
	.byte	$1A
	.byte	$15
	.byte	$1A
	.byte	$19
	.byte	$16
	.byte	$17
	.byte	$1B
	.byte	$16
	.byte	$1B
	.byte	$1A
	.byte	$17
	.byte	$14
	.byte	$18
	.byte	$17
	.byte	$18
	.byte	$1B
	.byte	$18
	.byte	$19
	.byte	$1D
	.byte	$18
	.byte	$1D
	.byte	$1C
	.byte	$19
	.byte	$1A
	.byte	$1E
	.byte	$19
	.byte	$1E
	.byte	$1D
	.byte	$1A
	.byte	$1B
	.byte	$1F
	.byte	$1A
	.byte	$1F
	.byte	$1E
	.byte	$1B
	.byte	$18
	.byte	$1C
	.byte	$1B
	.byte	$1C
	.byte	$1F
	.byte	$1C
	.byte	$1D
	.byte	$01
	.byte	$1C
	.byte	$01
	.byte	$00
	.byte	$1D
	.byte	$1E
	.byte	$02
	.byte	$1D
	.byte	$02
	.byte	$01
	.byte	$1E
	.byte	$1F
	.byte	$03
	.byte	$1E
	.byte	$03
	.byte	$02
	.byte	$1F
	.byte	$1C
	.byte	$00
	.byte	$1F
	.byte	$00
	.byte	$03
_pyramid_points:
	.word	$0000
	.word	$0014
	.word	$0000
	.word	$FFEC
	.word	$FFEC
	.word	$FFEC
	.word	$0014
	.word	$FFEC
	.word	$FFEC
	.word	$0014
	.word	$FFEC
	.word	$0014
	.word	$FFEC
	.word	$FFEC
	.word	$0014
_pyramid_tris:
	.byte	$00
	.byte	$02
	.byte	$01
	.byte	$00
	.byte	$03
	.byte	$02
	.byte	$00
	.byte	$04
	.byte	$03
	.byte	$00
	.byte	$01
	.byte	$04
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$01
	.byte	$03
	.byte	$04

.segment	"RODATA"

L0515:
	.byte	$D0,$D2,$D9,$CD,$20,$4C,$4F,$41,$44,$45,$44,$3A,$20,$25,$44,$20
	.byte	$50,$54,$53,$20,$25,$44,$20,$54,$52,$49,$53,$2C,$20,$25,$55,$CB
	.byte	$C2,$20,$46,$52,$45,$45,$0D,$00
L05AD:
	.byte	$32,$4C,$4F,$41,$44,$45,$44,$3A,$20,$25,$44,$20,$50,$54,$53,$20
	.byte	$25,$44,$20,$54,$52,$49,$53,$2C,$20,$25,$55,$CB,$C2,$20,$46,$52
	.byte	$45,$45,$0D,$00
L059E:
	.byte	$31,$4C,$4F,$41,$44,$45,$44,$3A,$20,$25,$44,$20,$50,$54,$53,$20
	.byte	$25,$44,$20,$54,$52,$49,$53,$2C,$20,$25,$55,$CB,$C2,$20,$46,$52
	.byte	$45,$45,$0D,$00
L0542	:=	L0515+5
L0533	:=	L0515+5
L0524	:=	L0515+5
L0601:
	.byte	$0D,$0D,$41,$4C,$4C,$4F,$43,$20,$42,$45,$46,$4F,$52,$45,$20,$43
	.byte	$4C,$45,$41,$4E,$20,$25,$55,$3A,$20,$25,$55,$20,$42,$59,$54,$45
	.byte	$53,$0D,$00
L0509:
	.byte	$C6,$41,$49,$4C,$45,$44,$20,$54,$4F,$20,$53,$41,$56,$45,$20,$54
	.byte	$4F,$52,$52,$4F,$49,$44,$20,$4D,$4F,$44,$45,$4C,$2E,$0D,$00
L0505:
	.byte	$D3,$D5,$C3,$C3,$C5,$D3,$D3,$3A,$20,$54,$4F,$52,$52,$4F,$49,$44
	.byte	$20,$4D,$4F,$44,$45,$4C,$20,$53,$41,$56,$45,$44,$2E,$0D,$00
L04FA:
	.byte	$C6,$41,$49,$4C,$45,$44,$20,$54,$4F,$20,$53,$41,$56,$45,$20,$50
	.byte	$59,$52,$41,$4D,$49,$44,$20,$4D,$4F,$44,$45,$4C,$2E,$0D,$00
L04F6:
	.byte	$D3,$D5,$C3,$C3,$C5,$D3,$D3,$3A,$20,$D0,$59,$52,$41,$4D,$49,$44
	.byte	$20,$4D,$4F,$44,$45,$4C,$20,$53,$41,$56,$45,$44,$2E,$0D,$00
L04CE:
	.byte	$CF,$55,$54,$20,$4F,$46,$20,$4D,$45,$4D,$4F,$52,$59,$20,$46,$4F
	.byte	$52,$20,$54,$4F,$52,$52,$4F,$49,$44,$0D,$00
L04C3:
	.byte	$CF,$55,$54,$20,$4F,$46,$20,$4D,$45,$4D,$4F,$52,$59,$20,$46,$4F
	.byte	$52,$20,$50,$59,$52,$41,$4D,$49,$44,$0D,$00
L0615:
	.byte	$41,$4C,$4C,$4F,$43,$20,$41,$46,$54,$45,$52,$20,$25,$55,$3A,$20
	.byte	$25,$55,$20,$42,$59,$54,$45,$53,$0D,$00
L04EB:
	.byte	$C2,$45,$47,$49,$4E,$4E,$49,$4E,$47,$20,$53,$41,$56,$45,$20,$54
	.byte	$45,$53,$54,$0D,$00
L05B5:
	.byte	$52,$55,$4E,$4E,$49,$4E,$47,$20,$31,$53,$54,$20,$41,$4C,$4C,$4F
	.byte	$43,$00
L057A:
	.byte	$D4,$C5,$D3,$D4,$20,$D0,$C1,$D3,$D3,$C5,$C4,$0D,$00
L0574:
	.byte	$D2,$C5,$CE,$C4,$C5,$D2,$D3,$C3,$C5,$CE,$C5,$0D,$00
L057E:
	.byte	$D4,$C5,$D3,$D4,$20,$C6,$C1,$C9,$CC,$C5,$C4,$0D,$00
L0500:
	.byte	$D4,$CF,$D2,$D2,$CF,$C9,$C4,$2C,$D0,$2C,$D7,$00
L052D:
	.byte	$D4,$CF,$D2,$D2,$CF,$C9,$C4,$2C,$D0,$2C,$D2,$00
L051E	:=	L052D+0
L05A7	:=	L052D+0
L053C	:=	L052D+0
L0570:
	.byte	$D3,$CF,$D2,$D4,$D3,$C3,$C5,$CE,$C5,$0D,$00
L0598:
	.byte	$D0,$D2,$D9,$CD,$2C,$D0,$2C,$D2,$00
L04F1:
	.byte	$D0,$D2,$D9,$CD,$2C,$D0,$2C,$D7,$00
L050F	:=	L0598+0
L061D:
	.byte	$C5,$58,$49,$54,$45,$44,$0D,$00

.segment	"BSS"

_transformed:
	.res	288,$00
_sort_list:
	.res	5396,$00
_foreground_box:
	.res	8,$00
_total_faces:
	.res	1,$00
_rotX:
	.res	2,$00
_rotY:
	.res	2,$00
_rotZ:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ rotate_x (__near__ int *, __near__ int *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_x: near

.segment	"BSS"

L0251:
	.res	4,$00
L0253:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0251
	stx     L0251+1
	ldy     sreg
	sty     L0251+2
	ldy     sreg+1
	sty     L0251+3
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0253
	stx     L0253+1
	ldy     sreg
	sty     L0253+2
	ldy     sreg+1
	sty     L0253+3
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	cpx     #$80
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0257
	ldy     #$00
	ldx     #$01
	lda     #$68
	jsr     addeqysp
L0257:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     L0251+3
	sta     sreg+1
	lda     L0251+2
	sta     sreg
	ldx     L0251+1
	lda     L0251
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0253+3
	sta     sreg+1
	lda     L0253+2
	sta     sreg
	ldx     L0253+1
	lda     L0253
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0261
	dey
L0261:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     L0251+3
	sta     sreg+1
	lda     L0251+2
	sta     sreg
	ldx     L0251+1
	lda     L0251
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0253+3
	sta     sreg+1
	lda     L0253+2
	sta     sreg
	ldx     L0253+1
	lda     L0253
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0268
	dey
L0268:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_y (__near__ int *, __near__ int *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_y: near

.segment	"BSS"

L026A:
	.res	4,$00
L026C:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L026A
	stx     L026A+1
	ldy     sreg
	sty     L026A+2
	ldy     sreg+1
	sty     L026A+3
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L026C
	stx     L026C+1
	ldy     sreg
	sty     L026C+2
	ldy     sreg+1
	sty     L026C+3
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	cpx     #$80
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0270
	ldy     #$00
	ldx     #$01
	lda     #$68
	jsr     addeqysp
L0270:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     L026A+3
	sta     sreg+1
	lda     L026A+2
	sta     sreg
	ldx     L026A+1
	lda     L026A
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L026C+3
	sta     sreg+1
	lda     L026C+2
	sta     sreg
	ldx     L026C+1
	lda     L026C
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L027A
	dey
L027A:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     L026C+3
	sta     sreg+1
	lda     L026C+2
	sta     sreg
	ldx     L026C+1
	lda     L026C
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L026A+3
	sta     sreg+1
	lda     L026A+2
	sta     sreg
	ldx     L026A+1
	lda     L026A
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0281
	dey
L0281:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_z (__near__ int *, __near__ int *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_z: near

.segment	"BSS"

L0283:
	.res	4,$00
L0285:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0283
	stx     L0283+1
	ldy     sreg
	sty     L0283+2
	ldy     sreg+1
	sty     L0283+3
	ldy     #$03
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	sta     L0285
	stx     L0285+1
	ldy     sreg
	sty     L0285+2
	ldy     sreg+1
	sty     L0285+3
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	cpx     #$80
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0289
	ldy     #$00
	ldx     #$01
	lda     #$68
	jsr     addeqysp
L0289:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	lda     L0283+3
	sta     sreg+1
	lda     L0283+2
	sta     sreg
	ldx     L0283+1
	lda     L0283
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0285+3
	sta     sreg+1
	lda     L0285+2
	sta     sreg
	ldx     L0285+1
	lda     L0285
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0293
	dey
L0293:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	lda     L0283+3
	sta     sreg+1
	lda     L0283+2
	sta     sreg
	ldx     L0283+1
	lda     L0283
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L0285+3
	sta     sreg+1
	lda     L0285+2
	sta     sreg
	ldx     L0285+1
	lda     L0285
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L029A
	dey
L029A:	sty     sreg+1
	ldy     #$00
	jsr     staxspidx
	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ sort_scene (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_sort_scene: near

.segment	"BSS"

L029C:
	.res	1,$00
L029D:
	.res	1,$00
L029E:
	.res	1,$00
L029F:
	.res	19,$00

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     L029C
L02A0:	ldx     #$00
	lda     L029C
	jsr     pushax
	ldx     #$00
	lda     _total_faces
	jsr     decax1
	jsr     tosultax
	jne     L02A3
	jmp     L02A1
L02A3:	ldx     #$00
	lda     #$00
	sta     L029E
	ldx     #$00
	lda     #$00
	sta     L029D
L02AA:	ldx     #$00
	lda     L029D
	jsr     pushax
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     L029C
	jsr     tossubax
	jsr     decax1
	jsr     tosultax
	jne     L02AD
	jmp     L02AB
L02AD:	ldx     #$00
	lda     L029D
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$11
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L029D
	jsr     incax1
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$11
	jsr     ldaxidx
	jsr     tosltax
	jeq     L02AC
	lda     #<(L029F)
	ldx     #>(L029F)
	jsr     pushax
	ldx     #$00
	lda     L029D
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     _memcpy
	ldx     #$00
	lda     L029D
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     L029D
	jsr     incax1
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     _memcpy
	ldx     #$00
	lda     L029D
	jsr     incax1
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     #<(L029F)
	ldx     #>(L029F)
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     _memcpy
	ldx     #$00
	lda     #$01
	sta     L029E
L02AC:	ldx     #$00
	inc     L029D
	lda     L029D
	jmp     L02AA
L02AB:	ldx     #$00
	lda     L029E
	jsr     bnega
	jeq     L02A2
	jmp     L02A1
L02A2:	ldx     #$00
	inc     L029C
	lda     L029C
	jmp     L02A0
L02A1:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ delay (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay: near

.segment	"BSS"

L02C5:
	.res	2,$00
L02C6:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldx     #$00
	lda     #$00
	sta     L02C5
	stx     L02C5+1
L02C7:	lda     L02C5
	ldx     L02C5+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosultax
	jne     L02CA
	jmp     L02C8
L02CA:	lda     L02C5
	ldx     L02C5+1
	jsr     mulax3
	jsr     shrax1
	sta     L02C6
	stx     L02C6+1
	inc     L02C5
	bne     L02CF
	inc     L02C5+1
L02CF:	lda     L02C5
	ldx     L02C5+1
	jmp     L02C7
L02C8:	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fill_triangle (int, int, int, int, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_triangle: near

.segment	"BSS"

L02D3:
	.res	2,$00
L02D4:
	.res	2,$00
L02D5:
	.res	2,$00
L02D6:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosgtax
	jeq     L02D7
	ldy     #$09
	jsr     ldaxysp
	sta     L02D3
	stx     L02D3+1
	ldy     #$05
	jsr     ldaxysp
	ldy     #$08
	jsr     staxysp
	lda     L02D3
	ldx     L02D3+1
	ldy     #$04
	jsr     staxysp
	ldy     #$0B
	jsr     ldaxysp
	sta     L02D3
	stx     L02D3+1
	ldy     #$07
	jsr     ldaxysp
	ldy     #$0A
	jsr     staxysp
	lda     L02D3
	ldx     L02D3+1
	ldy     #$06
	jsr     staxysp
L02D7:	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosgtax
	jeq     L02E5
	ldy     #$09
	jsr     ldaxysp
	sta     L02D3
	stx     L02D3+1
	ldy     #$01
	jsr     ldaxysp
	ldy     #$08
	jsr     staxysp
	lda     L02D3
	ldx     L02D3+1
	ldy     #$00
	jsr     staxysp
	ldy     #$0B
	jsr     ldaxysp
	sta     L02D3
	stx     L02D3+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$0A
	jsr     staxysp
	lda     L02D3
	ldx     L02D3+1
	ldy     #$02
	jsr     staxysp
L02E5:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosgtax
	jeq     L02F3
	ldy     #$05
	jsr     ldaxysp
	sta     L02D3
	stx     L02D3+1
	ldy     #$01
	jsr     ldaxysp
	ldy     #$04
	jsr     staxysp
	lda     L02D3
	ldx     L02D3+1
	ldy     #$00
	jsr     staxysp
	ldy     #$07
	jsr     ldaxysp
	sta     L02D3
	stx     L02D3+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$06
	jsr     staxysp
	lda     L02D3
	ldx     L02D3+1
	ldy     #$02
	jsr     staxysp
L02F3:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     toseqax
	jeq     L0301
	jmp     L0304
L0301:	ldy     #$09
	jsr     ldaxysp
	sta     L02D6
	stx     L02D6+1
L0303:	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     tosleax
	jne     L0306
	jmp     L0304
L0306:	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosltax
	jeq     L030C
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D4
	stx     L02D4+1
	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D5
	stx     L02D5+1
	jmp     L031A
L030C:	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     toseqax
	jeq     L031B
	ldy     #$07
	jsr     ldaxysp
	sta     L02D4
	stx     L02D4+1
	jmp     L031F
L031B:	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D4
	stx     L02D4+1
L031F:	ldy     #$0B
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     tossubax
	jsr     axlong
	jsr     tosdiveax
	jsr     tosaddax
	sta     L02D5
	stx     L02D5+1
L031A:	lda     L02D4
	ldx     L02D4+1
	jsr     pushax
	lda     L02D6
	ldx     L02D6+1
	jsr     pushax
	lda     L02D5
	ldx     L02D5+1
	jsr     pushax
	lda     L02D6
	ldx     L02D6+1
	jsr     _tgi_line
	inc     L02D6
	bne     L030B
	inc     L02D6+1
L030B:	lda     L02D6
	ldx     L02D6+1
	jmp     L0303
L0304:	ldy     #$0C
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ render_scene (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_render_scene: near

.segment	"BSS"

L0332:
	.res	1,$00

.segment	"CODE"

	ldx     #$00
	lda     #$00
	sta     L0332
L0333:	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     _total_faces
	jsr     tosultax
	jne     L0336
	jmp     L0334
L0336:	lda     #$00
	jsr     _tgi_setcolor
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$07
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$0B
	jsr     ldaxidx
	jsr     _fill_triangle
	lda     #$01
	jsr     _tgi_setcolor
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$07
	jsr     ldaxidx
	jsr     _tgi_line
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$07
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$0B
	jsr     ldaxidx
	jsr     _tgi_line
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$09
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0332
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     _tgi_line
	ldx     #$00
	inc     L0332
	lda     L0332
	jmp     L0333
L0334:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ add_to_scene (__near__ struct $anon-struct-0018 *, int, int, int, int, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_to_scene: near

.segment	"BSS"

L0368:
	.res	1,$00
L0369:
	.res	2,$00
L036A:
	.res	2,$00
L036B:
	.res	2,$00
L036C:
	.res	2,$00
L036D:
	.res	2,$00
L036E:
	.res	2,$00
L036F:
	.res	2,$00
L0370:
	.res	2,$00
L0371:
	.res	2,$00
L0372:
	.res	2,$00
L0373:
	.res	2,$00
L0374:
	.res	2,$00
L0375:
	.res	2,$00
L0376:
	.res	2,$00
L0377:
	.res	2,$00
L0378:
	.res	2,$00
L0379:
	.res	2,$00
L037A:
	.res	2,$00
L037B:
	.res	2,$00
L037C:
	.res	2,$00
L037D:
	.res	2,$00
L037E:
	.res	4,$00
L037F:
	.res	4,$00
L0380:
	.res	4,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L036F
	stx     L036F+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0B
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0370
	stx     L0370+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0D
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0371
	stx     L0371+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0D
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0372
	stx     L0372+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0373
	stx     L0373+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$0F
	jsr     ldaxidx
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0374
	stx     L0374+1
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0375
	stx     L0375+1
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0376
	stx     L0376+1
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0377
	stx     L0377+1
	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0378
	stx     L0378+1
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L0379
	stx     L0379+1
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	ldx     #$01
	lda     #$68
	jsr     tosmodax
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	sta     L037A
	stx     L037A+1
	ldx     #$00
	lda     #$00
	sta     L0368
L03A5:	ldx     #$00
	lda     L0368
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     tosultax
	jne     L03A8
	jmp     L03A6
L03A8:	ldy     #$0D
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax6
	jsr     tosaddax
	ldy     #$01
	jsr     ldaxidx
	sta     L0369
	stx     L0369+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax6
	jsr     tosaddax
	ldy     #$03
	jsr     ldaxidx
	sta     L036A
	stx     L036A+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax6
	jsr     tosaddax
	ldy     #$05
	jsr     ldaxidx
	sta     L036B
	stx     L036B+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0370
	ldx     L0370+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03BE
	dey
L03BE:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L036F
	ldx     L036F+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0370
	ldx     L0370+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03C3
	dey
L03C3:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	lda     L0369
	ldx     L0369+1
	sta     L036C
	stx     L036C+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0372
	ldx     L0372+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0371
	ldx     L0371+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03CC
	dey
L03CC:	sty     sreg+1
	sta     L0369
	stx     L0369+1
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0372
	ldx     L0372+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0371
	ldx     L0371+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03D1
	dey
L03D1:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	lda     L0369
	ldx     L0369+1
	sta     L036C
	stx     L036C+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0374
	ldx     L0374+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0373
	ldx     L0373+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03DA
	dey
L03DA:	sty     sreg+1
	sta     L0369
	stx     L0369+1
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0373
	ldx     L0373+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0374
	ldx     L0374+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03DF
	dey
L03DF:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	clc
	adc     L0369
	sta     L0369
	txa
	adc     L0369+1
	sta     L0369+1
	tax
	lda     L0369
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$07
	jsr     ldaxidx
	clc
	adc     L036A
	sta     L036A
	txa
	adc     L036A+1
	sta     L036A+1
	tax
	lda     L036A
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$09
	jsr     ldaxidx
	clc
	adc     L036B
	sta     L036B
	txa
	adc     L036B+1
	sta     L036B+1
	tax
	lda     L036B
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0376
	ldx     L0376+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0375
	ldx     L0375+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03EE
	dey
L03EE:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0375
	ldx     L0375+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0376
	ldx     L0376+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03F3
	dey
L03F3:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	lda     L0369
	ldx     L0369+1
	sta     L036C
	stx     L036C+1
	lda     L036B
	ldx     L036B+1
	sta     L036E
	stx     L036E+1
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0378
	ldx     L0378+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0377
	ldx     L0377+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L03FC
	dey
L03FC:	sty     sreg+1
	sta     L0369
	stx     L0369+1
	lda     L036E
	ldx     L036E+1
	jsr     axlong
	jsr     pusheax
	lda     L0378
	ldx     L0378+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0377
	ldx     L0377+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L0401
	dey
L0401:	sty     sreg+1
	sta     L036B
	stx     L036B+1
	lda     L0369
	ldx     L0369+1
	sta     L036C
	stx     L036C+1
	lda     L036A
	ldx     L036A+1
	sta     L036D
	stx     L036D+1
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L037A
	ldx     L037A+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L0379
	ldx     L0379+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L040A
	dey
L040A:	sty     sreg+1
	sta     L0369
	stx     L0369+1
	lda     L036C
	ldx     L036C+1
	jsr     axlong
	jsr     pusheax
	lda     L0379
	ldx     L0379+1
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L036D
	ldx     L036D+1
	jsr     axlong
	jsr     pusheax
	lda     L037A
	ldx     L037A+1
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	txa
	ldx     sreg
	ldy     sreg+1
	sty     sreg
	cpy     #$80
	ldy     #$00
	bcc     L040F
	dey
L040F:	sty     sreg+1
	sta     L036A
	stx     L036A+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	lda     L0369
	ldx     L0369+1
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxspidx
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	lda     L036A
	ldx     L036A+1
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$02
	jsr     staxspidx
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax6
	jsr     tosaddax
	jsr     pushax
	lda     L036B
	ldx     L036B+1
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$04
	jsr     staxspidx
	ldx     #$00
	inc     L0368
	lda     L0368
	jmp     L03A5
L03A6:	ldx     #$00
	lda     #$00
	sta     L0368
L0419:	ldx     #$00
	lda     L0368
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     tosultax
	jne     L041C
	jmp     L041A
L041C:	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax3
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     mulax6
	jsr     tosaddax
	sta     L037B
	stx     L037B+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax3
	jsr     tosaddax
	ldy     #$01
	jsr     ldauidx
	jsr     mulax6
	jsr     tosaddax
	sta     L037C
	stx     L037C+1
	ldy     #$0D
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     L0368
	jsr     mulax3
	jsr     tosaddax
	ldy     #$02
	jsr     ldauidx
	jsr     mulax6
	jsr     tosaddax
	sta     L037D
	stx     L037D+1
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	sta     L037E
	stx     L037E+1
	ldy     sreg
	sty     L037E+2
	ldy     sreg+1
	sty     L037E+3
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$05
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$05
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	sta     L037F
	stx     L037F+1
	ldy     sreg
	sty     L037F+2
	ldy     sreg+1
	sty     L037F+3
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$03
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$01
	jsr     ldaxidx
	jsr     tossubax
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	sta     L0380
	stx     L0380+1
	ldy     sreg
	sty     L0380+2
	ldy     sreg+1
	sty     L0380+3
	lda     L0380+3
	sta     sreg+1
	lda     L0380+2
	sta     sreg
	ldx     L0380+1
	lda     L0380
	lda     sreg+1
	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jeq     L0441
	ldx     #$00
	lda     _total_faces
	ldx     #$00
	lda     #$01
	jne     L0440
L0441:	ldx     #$00
	lda     #$00
	jeq     L0442
L0440:	ldx     #$00
	lda     #$01
L0442:	jeq     L041B
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$03
	jsr     ldaxidx
	ldy     #$02
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037C
	ldx     L037C+1
	ldy     #$03
	jsr     ldaxidx
	ldy     #$06
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037D
	ldx     L037D+1
	ldy     #$01
	jsr     ldaxidx
	ldy     #$08
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037D
	ldx     L037D+1
	ldy     #$03
	jsr     ldaxidx
	ldy     #$0A
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	lda     L037B
	ldx     L037B+1
	ldy     #$05
	jsr     ldaxidx
	jsr     axlong
	jsr     pusheax
	lda     L037C
	ldx     L037C+1
	ldy     #$05
	jsr     ldaxidx
	jsr     axlong
	jsr     tosaddeax
	jsr     pusheax
	lda     L037D
	ldx     L037D+1
	ldy     #$05
	jsr     ldaxidx
	jsr     axlong
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$03
	jsr     tosdiveax
	ldy     #$10
	jsr     staxspidx
	ldx     #$00
	lda     _total_faces
	jsr     pushax
	ldx     #$00
	lda     #$13
	jsr     tosmulax
	clc
	adc     #<(_sort_list)
	tay
	txa
	adc     #>(_sort_list)
	tax
	tya
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	ldy     #$10
	jsr     ldauidx
	ldy     #$12
	jsr     staspidx
	ldx     #$00
	lda     _total_faces
	inc     _total_faces
L041B:	ldx     #$00
	inc     L0368
	lda     L0368
	jmp     L0419
L041A:	ldy     #$0E
	jsr     addysp
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"BSS"

L045F:
	.res	2,$00
L0460:
	.res	2,$00
L0461:
	.res	2,$00
L0462:
	.res	2,$00
L0463:
	.res	2,$00
L0464:
	.res	2,$00
L0465:
	.res	2,$00
L0467:
	.res	2,$00
L0468:
	.res	2,$00
L046A:
	.res	2,$00
L046C:
	.res	2,$00
L046E:
	.res	2,$00
L046F:
	.res	2,$00
L0471:
	.res	2,$00
L0473:
	.res	2,$00
L0475:
	.res	2,$00
L0477:
	.res	2,$00
L0479:
	.res	2,$00
L047B:
	.res	6,$00
L047C:
	.res	6,$00
L047D:
	.res	17,$00
L047E:
	.res	17,$00
L047F:
	.res	17,$00
L0481:
	.res	288,$00
L0483:
	.res	192,$00
L0484:
	.res	6,$00
L0485:
	.res	17,$00
L0487:
	.res	288,$00
L0489:
	.res	192,$00
L048A:
	.res	6,$00

.segment	"CODE"

	ldx     #$00
	lda     #$01
	sta     L0465
	stx     L0465+1
	ldx     #$00
	lda     #$5A
	sta     L0468
	stx     L0468+1
	ldx     #$00
	lda     #$2D
	sta     L046A
	stx     L046A+1
	ldx     #$00
	lda     #$00
	sta     L046C
	stx     L046C+1
	ldx     #$4E
	lda     #$20
	sta     L046F
	stx     L046F+1
	ldx     #$00
	lda     #$00
	sta     L0471
	stx     L0471+1
	ldx     #$00
	lda     #$00
	sta     L0473
	stx     L0473+1
	ldx     #$00
	lda     #$00
	sta     L0475
	stx     L0475+1
	ldx     #$00
	lda     #$00
	sta     L0477
	stx     L0477+1
	ldx     #$00
	lda     #$00
	sta     L0479
	stx     L0479+1
	lda     #<(_torroid_points)
	ldx     #>(_torroid_points)
	sta     L047B
	stx     L047B+1
	lda     #<(_torroid_faces_tri)
	ldx     #>(_torroid_faces_tri)
	sta     L047B+2
	stx     L047B+2+1
	ldx     #$00
	lda     #$20
	sta     L047B+4
	ldx     #$00
	lda     #$40
	sta     L047B+5
	lda     #<(_pyramid_points)
	ldx     #>(_pyramid_points)
	sta     L047C
	stx     L047C+1
	lda     #<(_pyramid_tris)
	ldx     #>(_pyramid_tris)
	sta     L047C+2
	stx     L047C+2+1
	ldx     #$00
	lda     #$05
	sta     L047C+4
	ldx     #$00
	lda     #$06
	sta     L047C+5
	lda     #<(L047B)
	ldx     #>(L047B)
	sta     L047D
	stx     L047D+1
	ldx     #$FF
	lda     #$D8
	sta     L047D+4
	stx     L047D+4+1
	ldx     #$00
	lda     #$00
	sta     L047D+6
	stx     L047D+6+1
	ldx     #$00
	lda     #$00
	sta     L047D+8
	stx     L047D+8+1
	ldx     #$00
	lda     #$00
	sta     L047D+10
	stx     L047D+10+1
	ldx     #$00
	lda     #$00
	sta     L047D+12
	stx     L047D+12+1
	ldx     #$00
	lda     #$00
	sta     L047D+14
	stx     L047D+14+1
	ldx     #$00
	lda     #$00
	sta     L047D+16
	lda     L0473
	ldx     L0473+1
	sta     L047D+2
	stx     L047D+2+1
	lda     #<(L047C)
	ldx     #>(L047C)
	sta     L047E
	stx     L047E+1
	ldx     #$00
	lda     #$00
	sta     L047E+4
	stx     L047E+4+1
	ldx     #$00
	lda     #$00
	sta     L047E+6
	stx     L047E+6+1
	ldx     #$00
	lda     #$00
	sta     L047E+8
	stx     L047E+8+1
	ldx     #$00
	lda     #$5A
	sta     L047E+10
	stx     L047E+10+1
	ldx     #$00
	lda     #$00
	sta     L047E+12
	stx     L047E+12+1
	ldx     #$00
	lda     #$00
	sta     L047E+14
	stx     L047E+14+1
	ldx     #$00
	lda     #$01
	sta     L047E+16
	ldx     #$00
	lda     L047C+4
	jsr     mulax6
	jsr     _malloc
	sta     L0475
	stx     L0475+1
	lda     L0475
	ldx     L0475+1
	jsr     bnegax
	jeq     L04C0
	lda     #<(L04C3)
	ldx     #>(L04C3)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$01
	jmp     L045E
L04C0:	lda     L0475
	ldx     L0475+1
	sta     L047E+2
	stx     L047E+2+1
	ldx     #$00
	lda     L047B+4
	jsr     mulax6
	jsr     _malloc
	sta     L0473
	stx     L0473+1
	lda     L0473
	ldx     L0473+1
	jsr     bnegax
	jeq     L04CB
	lda     #<(L04CE)
	ldx     #>(L04CE)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$01
	jmp     L045E
L04CB:	lda     L0473
	ldx     L0473+1
	sta     L047D+2
	stx     L047D+2+1
	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
	jsr     _tgi_init
	jsr     _tgi_clear
	ldx     #$00
	lda     #$00
	sta     _total_faces
	lda     #<(L047E)
	ldx     #>(L047E)
	jsr     pushax
	ldx     #$00
	lda     #$82
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     pushax
	lda     L0468
	ldx     L0468+1
	jsr     pushax
	lda     L046A
	ldx     L046A+1
	jsr     pushax
	lda     L046C
	ldx     L046C+1
	jsr     _add_to_scene
	jsr     _sort_scene
	jsr     _render_scene
	lda     L047E+2
	ldx     L047E+2+1
	jsr     _free
	lda     L047D+2
	ldx     L047D+2+1
	jsr     _free
	jsr     _tgi_clear
	jsr     _tgi_uninstall
	jsr     _clrscr
	lda     #<(L04EB)
	ldx     #>(L04EB)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$08
	sta     L0467
	stx     L0467+1
	lda     #<(L04F1)
	ldx     #>(L04F1)
	jsr     pushax
	lda     L0467
	ldx     L0467+1
	jsr     pushax
	lda     #<(L047C)
	ldx     #>(L047C)
	jsr     _save_model
	stx     tmp1
	ora     tmp1
	jeq     L04EF
	lda     #<(L04F6)
	ldx     #>(L04F6)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L04F8
L04EF:	lda     #<(L04FA)
	ldx     #>(L04FA)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	sta     L0465
	stx     L0465+1
L04F8:	lda     #<(L0500)
	ldx     #>(L0500)
	jsr     pushax
	lda     L0467
	ldx     L0467+1
	jsr     pushax
	lda     #<(L047B)
	ldx     #>(L047B)
	jsr     _save_model
	stx     tmp1
	ora     tmp1
	jeq     L04FE
	lda     #<(L0505)
	ldx     #>(L0505)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L0507
L04FE:	lda     #<(L0509)
	ldx     #>(L0509)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	sta     L0465
	stx     L0465+1
L0507:	lda     #<(L050F)
	ldx     #>(L050F)
	jsr     pushax
	lda     L0467
	jsr     _load_object
	sta     L0463
	stx     L0463+1
	lda     L0463
	ldx     L0463+1
	txa
	jsr     boolge
	jeq     L0512
	lda     #<(L0515)
	ldx     #>(L0515)
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0512:	lda     #<(L051E)
	ldx     #>(L051E)
	jsr     pushax
	lda     L0467
	jsr     _load_object
	sta     L0463
	stx     L0463+1
	lda     L0463
	ldx     L0463+1
	txa
	jsr     boolge
	jeq     L0521
	lda     #<(L0524)
	ldx     #>(L0524)
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0521:	lda     #<(L052D)
	ldx     #>(L052D)
	jsr     pushax
	lda     L0467
	jsr     _load_object
	sta     L0463
	stx     L0463+1
	lda     L0463
	ldx     L0463+1
	txa
	jsr     boolge
	jeq     L0530
	lda     #<(L0533)
	ldx     #>(L0533)
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0530:	lda     #<(L053C)
	ldx     #>(L053C)
	jsr     pushax
	lda     L0467
	jsr     _load_object
	sta     L0463
	stx     L0463+1
	lda     L0463
	ldx     L0463+1
	txa
	jsr     boolge
	jeq     L053F
	lda     #<(L0542)
	ldx     #>(L0542)
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L053F:	ldx     #$00
	lda     #$00
	sta     _total_faces
	ldx     #$00
	lda     #$00
	sta     L0462
	stx     L0462+1
L054B:	lda     L0462
	ldx     L0462+1
	jsr     pushax
	lda     _object_count
	ldx     _object_count+1
	jsr     tosltax
	jne     L054E
	jmp     L054C
L054E:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$04
	jsr     staxspidx
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$06
	jsr     staxspidx
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$08
	jsr     staxspidx
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$5A
	ldy     #$0A
	jsr     staxspidx
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0C
	jsr     staxspidx
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$0E
	jsr     staxspidx
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$82
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     pushax
	lda     L0468
	ldx     L0468+1
	jsr     pushax
	lda     L046A
	ldx     L046A+1
	jsr     pushax
	lda     L046C
	ldx     L046C+1
	jsr     _add_to_scene
	inc     L0462
	bne     L0553
	inc     L0462+1
L0553:	lda     L0462
	ldx     L0462+1
	jmp     L054B
L054C:	lda     #<(L0570)
	ldx     #>(L0570)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     _sort_scene
	lda     #<(L0574)
	ldx     #>(L0574)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jsr     _render_scene
	lda     L0465
	ora     L0465+1
	jeq     L0577
	lda     #<(L057A)
	ldx     #>(L057A)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L057C
L0577:	lda     #<(L057E)
	ldx     #>(L057E)
	jsr     pushax
	ldy     #$02
	jsr     _printf
L057C:	ldx     #$00
	lda     #$00
	sta     L0461
	stx     L0461+1
	ldx     #$00
	lda     #$0A
	sta     L0460
	stx     L0460+1
	ldx     #$00
	lda     #$00
	sta     L045F
	stx     L045F+1
	jmp     L0588
L0586:	inc     L0461
	bne     L058C
	inc     L0461+1
L058C:	lda     L0461
	ldx     L0461+1
	jsr     _tgi_clear
	ldx     #$00
	lda     #$00
	sta     L045F
	stx     L045F+1
L058E:	lda     L045F
	ldx     L045F+1
	jsr     pushax
	lda     L0460
	ldx     L0460+1
	jsr     tosltax
	jne     L0591
	jmp     L058F
L0591:	lda     #<(L0598)
	ldx     #>(L0598)
	jsr     pushax
	lda     L0467
	jsr     _load_object
	sta     L0463
	stx     L0463+1
	lda     L0463
	ldx     L0463+1
	txa
	jsr     boolge
	jeq     L059B
	lda     #<(L059E)
	ldx     #>(L059E)
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L059B:	lda     #<(L05A7)
	ldx     #>(L05A7)
	jsr     pushax
	lda     L0467
	jsr     _load_object
	sta     L0463
	stx     L0463+1
	lda     L0463
	ldx     L0463+1
	txa
	jsr     boolge
	jeq     L0590
	lda     #<(L05AD)
	ldx     #>(L05AD)
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$04
	jsr     ldauidx
	jsr     pushax
	lda     L0463
	ldx     L0463+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$05
	jsr     ldauidx
	jsr     pushax
	lda     #<(__heapmemavail)
	ldx     #>(__heapmemavail)
	jsr     pushax
	ldy     #$08
	jsr     _printf
L0590:	lda     L045F
	ldx     L045F+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L045F
	stx     L045F+1
	lda     regsave
	ldx     regsave+1
	jmp     L058E
L058F:	lda     #<(L05B5)
	ldx     #>(L05B5)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$4E
	lda     #$20
	sta     L046F
	stx     L046F+1
	jmp     L05BB
L05B9:	lda     L046F
	ldx     L046F+1
	jsr     _malloc
	sta     L046E
	stx     L046E+1
	lda     L046E
	ora     L046E+1
	jeq     L05C0
	lda     L046E
	ldx     L046E+1
	jsr     _free
	jmp     L05BA
L05C0:	lda     L046F
	sec
	sbc     #$00
	sta     L046F
	lda     L046F+1
	sbc     #$04
	sta     L046F+1
	tax
	lda     L046F
L05BB:	lda     L046F
	ldx     L046F+1
	cmp     #$01
	txa
	sbc     #$04
	lda     #$00
	ldx     #$00
	rol     a
	jne     L05B9
L05BA:	jsr     _objectstateprint
	ldx     #$00
	lda     #$00
	sta     L0462
	stx     L0462+1
L05C7:	lda     L0462
	ldx     L0462+1
	jsr     pushax
	lda     _object_count
	ldx     _object_count+1
	jsr     tosltax
	jne     L05CA
	jmp     L05C8
L05CA:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     bnegax
	jeq     L05D0
	jmp     L05C9
L05D0:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L05D3
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxspidx
L05D3:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L05DC
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$00
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L05DF
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxspidx
L05DF:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$02
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	iny
	ora     (ptr1),y
	jeq     L05E8
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	ldy     #$03
	jsr     ldaxidx
	jsr     _free
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxspidx
L05E8:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxspidx
L05DC:	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	ldy     #$01
	jsr     ldaxidx
	jsr     _free
	lda     L0462
	ldx     L0462+1
	jsr     aslax1
	clc
	adc     #<(_objects)
	tay
	txa
	adc     #>(_objects)
	tax
	tya
	jsr     pushax
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxspidx
L05C9:	inc     L0462
	bne     L05CF
	inc     L0462+1
L05CF:	lda     L0462
	ldx     L0462+1
	jmp     L05C7
L05C8:	ldx     #$00
	lda     #$00
	sta     _object_count
	stx     _object_count+1
	lda     L0471
	ldx     L0471+1
	sta     regsave
	stx     regsave+1
	jsr     incax1
	sta     L0471
	stx     L0471+1
	lda     regsave
	ldx     regsave+1
	lda     #<(L0601)
	ldx     #>(L0601)
	jsr     pushax
	lda     L0471
	ldx     L0471+1
	jsr     pushax
	lda     L046F
	ldx     L046F+1
	jsr     pushax
	ldy     #$06
	jsr     _printf
	ldx     #$4E
	lda     #$20
	sta     L046F
	stx     L046F+1
	jmp     L0609
L0607:	lda     L046F
	ldx     L046F+1
	jsr     _malloc
	sta     L046E
	stx     L046E+1
	lda     L046E
	ora     L046E+1
	jeq     L060E
	lda     L046E
	ldx     L046E+1
	jsr     _free
	jmp     L0608
L060E:	lda     L046F
	sec
	sbc     #$00
	sta     L046F
	lda     L046F+1
	sbc     #$04
	sta     L046F+1
	tax
	lda     L046F
L0609:	lda     L046F
	ldx     L046F+1
	cmp     #$01
	txa
	sbc     #$04
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0607
L0608:	lda     #<(L0615)
	ldx     #>(L0615)
	jsr     pushax
	lda     L0471
	ldx     L0471+1
	jsr     pushax
	lda     L046F
	ldx     L046F+1
	jsr     pushax
	ldy     #$06
	jsr     _printf
L0588:	lda     L046F
	ldx     L046F+1
	cmp     #$01
	txa
	sbc     #$04
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0586
	ldx     #$00
	lda     #$00
	sta     $00C6
	jsr     _tgi_uninstall
	lda     #<(L061D)
	ldx     #>(L061D)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	jmp     L045E
L045E:	rts

.endproc

