;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cbm_open
	.import		_cbm_close
	.import		_cbm_read
	.import		_printf
	.export		_format_disk
	.export		_main

.segment	"RODATA"

L0051:
	.byte	$46,$4F,$52,$4D,$41,$54,$54,$49,$4E,$47,$20,$25,$55,$20,$57,$49
	.byte	$54,$48,$20,$4C,$41,$42,$45,$4C,$20,$25,$53,$2E,$2E,$2E,$0D,$00
L004D:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$44,$45,$56,$49,$43,$45,$20,$25,$55
	.byte	$20,$4E,$4F,$54,$20,$50,$52,$45,$53,$45,$4E,$54,$0D,$00
L0062:
	.byte	$53,$54,$41,$54,$55,$53,$3A,$20,$25,$53,$0D,$00
L006A:
	.byte	$49,$54,$57,$4F,$52,$4B,$53,$00
L006C:
	.byte	$30,$31,$00

; ---------------------------------------------------------------
; void __near__ format_disk (unsigned int, __near__ const unsigned char *, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_format_disk: near

.segment	"BSS"

L0008:
	.res	64,$00
L000A:
	.res	64,$00
L000B:
	.res	2,$00
L000C:
	.res	2,$00
L000E:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldx     #$00
	txa
	sta     L000C
	sta     L000C+1
	sta     regsave
	sta     regsave+1
	clc
	adc     #$01
	bcc     L0011
	inx
L0011:	sta     L000C
	stx     L000C+1
	lda     regsave
	clc
	adc     #<(L0008)
	sta     ptr1
	lda     regsave+1
	adc     #>(L0008)
	sta     ptr1+1
	lda     #$4E
	ldy     #$00
	sta     (ptr1),y
	lda     L000C
	ldx     L000C+1
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L0015
	inx
L0015:	sta     L000C
	stx     L000C+1
	lda     regsave
	clc
	adc     #<(L0008)
	sta     ptr1
	lda     regsave+1
	adc     #>(L0008)
	sta     ptr1+1
	lda     #$30
	sta     (ptr1),y
	lda     L000C
	ldx     L000C+1
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L0019
	inx
L0019:	sta     L000C
	stx     L000C+1
	lda     regsave
	clc
	adc     #<(L0008)
	sta     ptr1
	lda     regsave+1
	adc     #>(L0008)
	sta     ptr1+1
	lda     #$3A
	sta     (ptr1),y
	tya
	sta     L000E
	sta     L000E+1
L001B:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L000E
	sta     ptr1
	txa
	adc     L000E+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	beq     L001C
	lda     L000C
	cmp     #$28
	lda     L000C+1
	sbc     #$00
	bvc     L0024
	eor     #$80
L0024:	bpl     L001C
	lda     L000C
	ldx     L000C+1
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L002A
	inx
L002A:	sta     L000C
	stx     L000C+1
	lda     regsave
	clc
	adc     #<(L0008)
	sta     sreg
	lda     regsave+1
	adc     #>(L0008)
	sta     sreg+1
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L000E
	sta     ptr1
	txa
	adc     L000E+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
	inc     L000E
	bne     L001B
	inc     L000E+1
	jmp     L001B
L001C:	lda     L000C
	ldx     L000C+1
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L002F
	inx
L002F:	sta     L000C
	stx     L000C+1
	lda     regsave
	clc
	adc     #<(L0008)
	sta     ptr1
	lda     regsave+1
	adc     #>(L0008)
	sta     ptr1+1
	lda     #$2C
	sta     (ptr1),y
	tya
	sta     L000E
	sta     L000E+1
L0031:	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L000E
	sta     ptr1
	txa
	adc     L000E+1
	sta     ptr1+1
	lda     (ptr1),y
	beq     L0032
	lda     L000C
	cmp     #$3C
	lda     L000C+1
	sbc     #$00
	bvc     L003A
	eor     #$80
L003A:	bpl     L0032
	lda     L000C
	ldx     L000C+1
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L0040
	inx
L0040:	sta     L000C
	stx     L000C+1
	lda     regsave
	clc
	adc     #<(L0008)
	sta     sreg
	lda     regsave+1
	adc     #>(L0008)
	sta     sreg+1
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L000E
	sta     ptr1
	txa
	adc     L000E+1
	sta     ptr1+1
	lda     (ptr1),y
	sta     (sreg),y
	inc     L000E
	bne     L0031
	inc     L000E+1
	jmp     L0031
L0032:	lda     #<(L0008)
	clc
	adc     L000C
	sta     ptr1
	lda     #>(L0008)
	adc     L000C+1
	sta     ptr1+1
	tya
	sta     (ptr1),y
	jsr     decsp3
	lda     #$0F
	ldy     #$02
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	lda     #$0F
	dey
	sta     (sp),y
	lda     #<(L0008)
	ldx     #>(L0008)
	jsr     _cbm_open
	cmp     #$00
	beq     L0046
	lda     #<(L004D)
	ldx     #>(L004D)
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$04
	jsr     _printf
	jmp     incsp6
L0046:	lda     #<(L0051)
	ldx     #>(L0051)
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$09
	jsr     pushwysp
	ldy     #$06
	jsr     _printf
	jsr     decsp3
	lda     #$0F
	ldy     #$02
	sta     (sp),y
	lda     #<(L000A)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L000A)
	sta     (sp),y
	ldx     #$00
	lda     #$3F
	jsr     _cbm_read
	sta     L000B
	stx     L000B+1
	cmp     #$01
	txa
	sbc     #$00
	bvs     L005D
	eor     #$80
L005D:	bpl     L005B
	lda     #<(L000A)
	clc
	adc     L000B
	sta     ptr1
	lda     #>(L000A)
	adc     L000B+1
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #<(L0062)
	ldx     #>(L0062)
	jsr     pushax
	lda     #<(L000A)
	ldx     #>(L000A)
	jsr     pushax
	ldy     #$04
	jsr     _printf
L005B:	lda     #$0F
	jsr     _cbm_close
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	lda     #$08
	ldy     #$02
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #<(L006A)
	ldy     #$00
	sta     (sp),y
	iny
	lda     #>(L006A)
	sta     (sp),y
	lda     #<(L006C)
	ldx     #>(L006C)
	jsr     _format_disk
	ldx     #$00
	txa
	rts

.endproc

