;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_putchar
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp4
	ldx     #$00
	txa
L002F:	jsr     stax0sp
	cmp     #$15
	txa
	sbc     #$00
	bvc     L000A
	eor     #$80
L000A:	asl     a
L002A:	bcc     L002A
	ldx     #$00
	txa
L002E:	ldy     #$02
	jsr     staxysp
	cmp     #$15
	txa
	sbc     #$00
	bvc     L0013
	eor     #$80
L0013:	asl     a
	ldx     #$00
	bcc     L0029
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     tosmoda0
	cpx     #$00
	bne     L0015
	cmp     #$00
	bne     L002D
	lda     #$A6
	jmp     L0028
L0015:	ldx     #$00
L002D:	lda     #$A0
L0028:	jsr     _putchar
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	jmp     L002E
L0029:	lda     #$0A
	jsr     _putchar
	ldx     #$00
	lda     #$0D
	jsr     _putchar
	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	jmp     L002F

.endproc

