;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.import		_putchar
	.import		_waitvsync
	.import		_strlen
	.import		_memcpy
	.import		_memset
	.export		_QrTinyWriteNumeric
	.export		_QrTinyWriteAlphanumeric
	.export		_QrTinyWrite8Bit
	.export		_QrTinyGenerate
	.export		_QrTinyModuleGet
	.export		_delay
	.export		_main

.segment	"DATA"

_eccDivisors:
	.addr	_eccDivisorsMedium
	.addr	_eccDivisorsLow
	.addr	_eccDivisorsHigh
	.addr	_eccDivisorsQuartile

.segment	"RODATA"

_eccDivisorsMedium:
	.byte	$D8
	.byte	$C2
	.byte	$9F
	.byte	$6F
	.byte	$C7
	.byte	$5E
	.byte	$5F
	.byte	$71
	.byte	$9D
	.byte	$C1
_eccDivisorsLow:
	.byte	$7F
	.byte	$7A
	.byte	$9A
	.byte	$A4
	.byte	$0B
	.byte	$44
	.byte	$75
_eccDivisorsHigh:
	.byte	$77
	.byte	$42
	.byte	$53
	.byte	$78
	.byte	$77
	.byte	$16
	.byte	$C5
	.byte	$53
	.byte	$F9
	.byte	$29
	.byte	$8F
	.byte	$86
	.byte	$55
	.byte	$35
	.byte	$7D
	.byte	$63
	.byte	$4F
_eccDivisorsQuartile:
	.byte	$89
	.byte	$49
	.byte	$E3
	.byte	$11
	.byte	$B1
	.byte	$11
	.byte	$34
	.byte	$0D
	.byte	$2E
	.byte	$2B
	.byte	$53
	.byte	$84
	.byte	$78
_g_exp:
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$10
	.byte	$20
	.byte	$40
	.byte	$80
	.byte	$1D
	.byte	$3A
	.byte	$74
	.byte	$E8
	.byte	$CD
	.byte	$87
	.byte	$13
	.byte	$26
	.byte	$4C
	.byte	$98
	.byte	$2D
	.byte	$5A
	.byte	$B4
	.byte	$75
	.byte	$EA
	.byte	$C9
	.byte	$8F
	.byte	$03
	.byte	$06
	.byte	$0C
	.byte	$18
	.byte	$30
	.byte	$60
	.byte	$C0
	.byte	$9D
	.byte	$27
	.byte	$4E
	.byte	$9C
	.byte	$25
	.byte	$4A
	.byte	$94
	.byte	$35
	.byte	$6A
	.byte	$D4
	.byte	$B5
	.byte	$77
	.byte	$EE
	.byte	$C1
	.byte	$9F
	.byte	$23
	.byte	$46
	.byte	$8C
	.byte	$05
	.byte	$0A
	.byte	$14
	.byte	$28
	.byte	$50
	.byte	$A0
	.byte	$5D
	.byte	$BA
	.byte	$69
	.byte	$D2
	.byte	$B9
	.byte	$6F
	.byte	$DE
	.byte	$A1
	.byte	$5F
	.byte	$BE
	.byte	$61
	.byte	$C2
	.byte	$99
	.byte	$2F
	.byte	$5E
	.byte	$BC
	.byte	$65
	.byte	$CA
	.byte	$89
	.byte	$0F
	.byte	$1E
	.byte	$3C
	.byte	$78
	.byte	$F0
	.byte	$FD
	.byte	$E7
	.byte	$D3
	.byte	$BB
	.byte	$6B
	.byte	$D6
	.byte	$B1
	.byte	$7F
	.byte	$FE
	.byte	$E1
	.byte	$DF
	.byte	$A3
	.byte	$5B
	.byte	$B6
	.byte	$71
	.byte	$E2
	.byte	$D9
	.byte	$AF
	.byte	$43
	.byte	$86
	.byte	$11
	.byte	$22
	.byte	$44
	.byte	$88
	.byte	$0D
	.byte	$1A
	.byte	$34
	.byte	$68
	.byte	$D0
	.byte	$BD
	.byte	$67
	.byte	$CE
	.byte	$81
	.byte	$1F
	.byte	$3E
	.byte	$7C
	.byte	$F8
	.byte	$ED
	.byte	$C7
	.byte	$93
	.byte	$3B
	.byte	$76
	.byte	$EC
	.byte	$C5
	.byte	$97
	.byte	$33
	.byte	$66
	.byte	$CC
	.byte	$85
	.byte	$17
	.byte	$2E
	.byte	$5C
	.byte	$B8
	.byte	$6D
	.byte	$DA
	.byte	$A9
	.byte	$4F
	.byte	$9E
	.byte	$21
	.byte	$42
	.byte	$84
	.byte	$15
	.byte	$2A
	.byte	$54
	.byte	$A8
	.byte	$4D
	.byte	$9A
	.byte	$29
	.byte	$52
	.byte	$A4
	.byte	$55
	.byte	$AA
	.byte	$49
	.byte	$92
	.byte	$39
	.byte	$72
	.byte	$E4
	.byte	$D5
	.byte	$B7
	.byte	$73
	.byte	$E6
	.byte	$D1
	.byte	$BF
	.byte	$63
	.byte	$C6
	.byte	$91
	.byte	$3F
	.byte	$7E
	.byte	$FC
	.byte	$E5
	.byte	$D7
	.byte	$B3
	.byte	$7B
	.byte	$F6
	.byte	$F1
	.byte	$FF
	.byte	$E3
	.byte	$DB
	.byte	$AB
	.byte	$4B
	.byte	$96
	.byte	$31
	.byte	$62
	.byte	$C4
	.byte	$95
	.byte	$37
	.byte	$6E
	.byte	$DC
	.byte	$A5
	.byte	$57
	.byte	$AE
	.byte	$41
	.byte	$82
	.byte	$19
	.byte	$32
	.byte	$64
	.byte	$C8
	.byte	$8D
	.byte	$07
	.byte	$0E
	.byte	$1C
	.byte	$38
	.byte	$70
	.byte	$E0
	.byte	$DD
	.byte	$A7
	.byte	$53
	.byte	$A6
	.byte	$51
	.byte	$A2
	.byte	$59
	.byte	$B2
	.byte	$79
	.byte	$F2
	.byte	$F9
	.byte	$EF
	.byte	$C3
	.byte	$9B
	.byte	$2B
	.byte	$56
	.byte	$AC
	.byte	$45
	.byte	$8A
	.byte	$09
	.byte	$12
	.byte	$24
	.byte	$48
	.byte	$90
	.byte	$3D
	.byte	$7A
	.byte	$F4
	.byte	$F5
	.byte	$F7
	.byte	$F3
	.byte	$FB
	.byte	$EB
	.byte	$CB
	.byte	$8B
	.byte	$0B
	.byte	$16
	.byte	$2C
	.byte	$58
	.byte	$B0
	.byte	$7D
	.byte	$FA
	.byte	$E9
	.byte	$CF
	.byte	$83
	.byte	$1B
	.byte	$36
	.byte	$6C
	.byte	$D8
	.byte	$AD
	.byte	$47
	.byte	$8E
	.byte	$01
_g_log:
	.byte	$00
	.byte	$00
	.byte	$01
	.byte	$19
	.byte	$02
	.byte	$32
	.byte	$1A
	.byte	$C6
	.byte	$03
	.byte	$DF
	.byte	$33
	.byte	$EE
	.byte	$1B
	.byte	$68
	.byte	$C7
	.byte	$4B
	.byte	$04
	.byte	$64
	.byte	$E0
	.byte	$0E
	.byte	$34
	.byte	$8D
	.byte	$EF
	.byte	$81
	.byte	$1C
	.byte	$C1
	.byte	$69
	.byte	$F8
	.byte	$C8
	.byte	$12
	.byte	$4C
	.byte	$71
	.byte	$05
	.byte	$8A
	.byte	$65
	.byte	$2F
	.byte	$E1
	.byte	$24
	.byte	$0F
	.byte	$A6
	.byte	$35
	.byte	$9A
	.byte	$8E
	.byte	$92
	.byte	$F0
	.byte	$17
	.byte	$82
	.byte	$45
	.byte	$1D
	.byte	$B5
	.byte	$C2
	.byte	$7D
	.byte	$6A
	.byte	$27
	.byte	$F9
	.byte	$B9
	.byte	$C9
	.byte	$94
	.byte	$13
	.byte	$62
	.byte	$4D
	.byte	$54
	.byte	$72
	.byte	$3D
	.byte	$06
	.byte	$BC
	.byte	$8B
	.byte	$62
	.byte	$66
	.byte	$48
	.byte	$30
	.byte	$5E
	.byte	$E2
	.byte	$58
	.byte	$25
	.byte	$0A
	.byte	$10
	.byte	$85
	.byte	$A7
	.byte	$88
	.byte	$36
	.byte	$D0
	.byte	$9B
	.byte	$CE
	.byte	$8F
	.byte	$76
	.byte	$93
	.byte	$7B
	.byte	$F1
	.byte	$D7
	.byte	$18
	.byte	$5A
	.byte	$83
	.byte	$3B
	.byte	$46
	.byte	$40
	.byte	$1E
	.byte	$3A
	.byte	$B6
	.byte	$93
	.byte	$C3
	.byte	$48
	.byte	$7E
	.byte	$6E
	.byte	$6B
	.byte	$3A
	.byte	$28
	.byte	$AB
	.byte	$FA
	.byte	$87
	.byte	$BA
	.byte	$3D
	.byte	$CA
	.byte	$5E
	.byte	$95
	.byte	$9F
	.byte	$14
	.byte	$21
	.byte	$63
	.byte	$2B
	.byte	$4E
	.byte	$0F
	.byte	$55
	.byte	$11
	.byte	$73
	.byte	$7A
	.byte	$3E
	.byte	$53
	.byte	$07
	.byte	$70
	.byte	$BD
	.byte	$75
	.byte	$8C
	.byte	$82
	.byte	$63
	.byte	$0D
	.byte	$67
	.byte	$4A
	.byte	$49
	.byte	$20
	.byte	$31
	.byte	$12
	.byte	$5F
	.byte	$18
	.byte	$E3
	.byte	$79
	.byte	$59
	.byte	$77
	.byte	$26
	.byte	$12
	.byte	$0B
	.byte	$7C
	.byte	$11
	.byte	$A2
	.byte	$86
	.byte	$20
	.byte	$A8
	.byte	$1D
	.byte	$89
	.byte	$17
	.byte	$37
	.byte	$B4
	.byte	$D1
	.byte	$53
	.byte	$9C
	.byte	$BC
	.byte	$CF
	.byte	$51
	.byte	$90
	.byte	$72
	.byte	$77
	.byte	$AA
	.byte	$94
	.byte	$1D
	.byte	$7C
	.byte	$88
	.byte	$F2
	.byte	$1D
	.byte	$D8
	.byte	$6A
	.byte	$19
	.byte	$AC
	.byte	$5B
	.byte	$5E
	.byte	$84
	.byte	$1D
	.byte	$3C
	.byte	$1D
	.byte	$47
	.byte	$6A
	.byte	$41
	.byte	$12
	.byte	$1F
	.byte	$2D
	.byte	$3B
	.byte	$1D
	.byte	$B7
	.byte	$97
	.byte	$94
	.byte	$1D
	.byte	$C4
	.byte	$17
	.byte	$49
	.byte	$EC
	.byte	$7F
	.byte	$0C
	.byte	$6F
	.byte	$F6
	.byte	$6C
	.byte	$A1
	.byte	$3B
	.byte	$52
	.byte	$29
	.byte	$9D
	.byte	$AC
	.byte	$1D
	.byte	$FB
	.byte	$98
	.byte	$88
	.byte	$52
	.byte	$BB
	.byte	$14
	.byte	$3E
	.byte	$5D
	.byte	$CB
	.byte	$5D
	.byte	$5F
	.byte	$05
	.byte	$96
	.byte	$1D
	.byte	$A0
	.byte	$51
	.byte	$15
	.byte	$ED
	.byte	$22
	.byte	$1D
	.byte	$64
	.byte	$70
	.byte	$2C
	.byte	$1D
	.byte	$4F
	.byte	$1D
	.byte	$10
	.byte	$1D
	.byte	$56
	.byte	$1D
	.byte	$12
	.byte	$1D
	.byte	$74
	.byte	$1D
	.byte	$7B
	.byte	$1D
	.byte	$3F
	.byte	$1D
	.byte	$54
	.byte	$00
_qrmod3:
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
	.byte	$00
	.byte	$01
	.byte	$02
_qrcode_ecc_block_codewords:
	.byte	$0A
	.byte	$07
	.byte	$11
	.byte	$0D
L06AA:
	.byte	$47,$45,$4E,$45,$52,$41,$54,$49,$4E,$47,$20,$53,$50,$52,$49,$54
	.byte	$45,$20,$25,$44,$00
L063A:
	.byte	$53,$50,$52,$49,$54,$45,$33,$54,$45,$58,$54,$00
L063C:
	.byte	$53,$50,$52,$49,$54,$45,$34,$54,$45,$58,$54,$00
L063E:
	.byte	$53,$50,$52,$49,$54,$45,$35,$54,$45,$58,$54,$00
L0640:
	.byte	$53,$50,$52,$49,$54,$45,$36,$54,$45,$58,$54,$00
L0642:
	.byte	$53,$50,$52,$49,$54,$45,$37,$54,$45,$58,$54,$00
L0644:
	.byte	$53,$50,$52,$49,$54,$45,$38,$54,$45,$58,$54,$00
L0635:
	.byte	$53,$50,$52,$49,$54,$45,$31,$54,$45,$58,$54,$00
L0638:
	.byte	$53,$50,$52,$49,$54,$45,$32,$54,$45,$58,$54,$00

; ---------------------------------------------------------------
; unsigned int __near__ QrTinyWriteNumeric (__near__ void *, unsigned int, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyWriteNumeric: near

.segment	"BSS"

L0427:
	.res	1,$00
L0428:
	.res	2,$00
L0429:
	.res	1,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	sta     L0429
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$01
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$04
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L0429
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$0A
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	jmp     L043A
L077D:	lda     L0429
	cmp     #$04
	bcc     L077E
	lda     #$03
	jmp     L077F
L077E:	lda     L0429
L077F:	sta     L0427
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$30
	bcs     L0444
	dex
L0444:	sta     L0428
	stx     L0428+1
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L0446
	inx
L0446:	jsr     stax0sp
	lda     L0427
	cmp     #$02
	jcc     L0447
	lda     L0428
	ldx     L0428+1
	jsr     mulax10
	sta     sreg
	stx     sreg+1
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$30
	bcs     L044C
	dex
L044C:	clc
	adc     sreg
	sta     L0428
	txa
	adc     sreg+1
	sta     L0428+1
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L044E
	inx
L044E:	jsr     stax0sp
	lda     L0427
	cmp     #$03
	bcc     L044F
	lda     L0428
	ldx     L0428+1
	jsr     mulax10
	sta     sreg
	stx     sreg+1
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldx     #$00
	lda     (ptr1),y
	sec
	sbc     #$30
	bcs     L0454
	dex
L0454:	clc
	adc     sreg
	sta     L0428
	txa
	adc     sreg+1
	sta     L0428+1
	iny
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L0456
	inx
L0456:	jsr     stax0sp
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L0428
	ldy     #$00
	sta     (sp),y
	iny
	lda     L0428+1
	sta     (sp),y
	lda     #$0A
	jmp     L0781
L044F:	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L0428
	ldy     #$00
	sta     (sp),y
	iny
	lda     L0428+1
	sta     (sp),y
	lda     #$07
	jmp     L0781
L0447:	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L0428
	ldy     #$00
	sta     (sp),y
	iny
	lda     L0428+1
	sta     (sp),y
	lda     #$04
L0781:	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	lda     L0427
	eor     #$FF
	sec
	adc     L0429
	sta     L0429
L043A:	lda     L0429
	jne     L077D
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ QrTinyWriteAlphanumeric (__near__ void *, unsigned int, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyWriteAlphanumeric: near

.segment	"BSS"

L04A3:
	.res	1,$00
L04A6:
	.res	1,$00
L04A8:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	sta     L04A3
	sta     L04A6
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$02
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$04
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L04A3
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$09
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	jmp     L0782
L04B5:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L04BC
	inx
L04BC:	jsr     stax0sp
	ldy     #$00
	lda     (regsave),y
	jsr     _QrGetAlphanumericVal
	sta     L04A8
	stx     L04A8+1
	lda     L04A6
	cmp     #$02
	bcc     L04BD
	lda     L04A8
	ldx     L04A8+1
	jsr     pushax
	lda     #$2D
	jsr     tosumula0
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L04C3
	inx
L04C3:	jsr     staxysp
	ldy     #$00
	lda     (regsave),y
	jsr     _QrGetAlphanumericVal
	jsr     tosaddax
	sta     L04A8
	stx     L04A8+1
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L04A8
	ldy     #$00
	sta     (sp),y
	iny
	lda     L04A8+1
	sta     (sp),y
	lda     #$0B
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	lda     L04A6
	sec
	sbc     #$02
	sta     L04A6
	jmp     L0782
L04BD:	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L04A8
	ldy     #$00
	sta     (sp),y
	iny
	lda     L04A8+1
	sta     (sp),y
	lda     #$06
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	dec     L04A6
L0782:	lda     L04A6
	jne     L04B5
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ QrTinyWrite8Bit (__near__ void *, unsigned int, __near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyWrite8Bit: near

.segment	"BSS"

L04D7:
	.res	1,$00
L04DA:
	.res	1,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _strlen
	sta     L04D7
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     #$04
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$04
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L04D7
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$08
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	lda     #$00
	sta     L04DA
L0784:	lda     L04DA
	cmp     L04D7
	bcs     L04E8
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$09
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$02
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     L04DA
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	ldy     #$00
	sta     (sp),y
	iny
	lda     #$00
	sta     (sp),y
	lda     #$08
	jsr     _QrTinyBufferAppend
	ldy     #$02
	jsr     addeqysp
	inc     L04DA
	jmp     L0784
L04E8:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ QrTinyGenerate (__near__ unsigned char *, unsigned int, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyGenerate: near

.segment	"BSS"

L05A0:
	.res	2,$00
L05A1:
	.res	2,$00
L05A2:
	.res	2,$00
L05A3:
	.res	2,$00
L05AC:
	.res	2,$00
L05B0:
	.res	2,$00
L05B3:
	.res	2,$00
L05BA:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	eor     #$12
	txa
	eor     #$54
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	and     #$03
	sta     L05A3
	stx     L05A3+1
	lda     #<(_qrcode_ecc_block_codewords)
	clc
	adc     L05A3
	tay
	lda     #>(_qrcode_ecc_block_codewords)
	adc     L05A3+1
	tax
	tya
	ldy     #$00
	jsr     ldaidx
	ldx     #$00
	cmp     #$80
	bcc     L05AF
	dex
L05AF:	sta     L05AC
	stx     L05AC+1
	lda     L05A3
	ldx     L05A3+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(_eccDivisors)
	sta     ptr1
	lda     tmp1
	adc     #>(_eccDivisors)
	sta     ptr1+1
	iny
	lda     (ptr1),y
	sta     L05B0+1
	dey
	lda     (ptr1),y
	sta     L05B0
	lda     #$1A
	sec
	sbc     L05AC
	pha
	tya
	sbc     L05AC+1
	tax
	pla
	jsr     shlax3
	sta     L05B3
	stx     L05B3+1
	sec
	ldy     #$02
	sbc     (sp),y
	sta     L05BA
	txa
	iny
	sbc     (sp),y
	tax
	stx     L05BA+1
	cpx     #$80
	bcc     L0786
	ldx     #$00
	txa
	jmp     incsp6
L0786:	lda     (sp),y
	sta     L05A0+1
	dey
	lda     (sp),y
	sta     L05A0
	lda     L05B3
	sec
	sbc     L05A0
	pha
	lda     L05B3+1
	sbc     L05A0+1
	tax
	pla
	sta     L05A1
	stx     L05A1+1
	cmp     #$05
	txa
	sbc     #$00
	bcc     L05C3
	ldx     #$00
	lda     #$04
	sta     L05A1
	stx     L05A1+1
L05C3:	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L05A0
	ldy     #$02
	sta     (sp),y
	iny
	lda     L05A0+1
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	iny
	sta     (sp),y
	lda     L05A1
	jsr     _QrTinyBufferAppend
	clc
	adc     L05A0
	sta     L05A0
	txa
	adc     L05A0+1
	sta     L05A0+1
	lda     #$08
	jsr     pusha0
	lda     L05A0
	and     #$07
	jsr     tossuba0
	ldx     #$00
	and     #$07
	sta     L05A2
	stx     L05A2+1
	lda     L05B3
	sec
	sbc     L05A0
	pha
	lda     L05B3+1
	sbc     L05A0+1
	tax
	pla
	sta     L05A1
	stx     L05A1+1
	sec
	sbc     L05A2
	sta     tmp1
	txa
	sbc     L05A2+1
	ora     tmp1
	bcc     L05D3
	beq     L05D3
	lda     L05A2+1
	sta     L05A1+1
	lda     L05A2
	sta     L05A1
L05D3:	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L05A0
	ldy     #$02
	sta     (sp),y
	iny
	lda     L05A0+1
	sta     (sp),y
	lda     #$00
	tay
	sta     (sp),y
	iny
	jmp     L078F
L05DD:	lda     L05A1
	cmp     #$11
	lda     L05A1+1
	sbc     #$00
	bcc     L05E4
	ldx     #$00
	lda     #$10
	sta     L05A1
	stx     L05A1+1
L05E4:	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L05A0
	ldy     #$02
	sta     (sp),y
	iny
	lda     L05A0+1
	sta     (sp),y
	lda     #$10
	sec
	sbc     L05A1
	pha
	lda     #$00
	sbc     L05A1+1
	pla
	tay
	lda     #$11
	ldx     #$EC
	jsr     shraxy
	ldy     #$00
	sta     (sp),y
	iny
	txa
L078F:	sta     (sp),y
	lda     L05A1
	jsr     _QrTinyBufferAppend
	clc
	adc     L05A0
	sta     L05A0
	txa
	adc     L05A0+1
	sta     L05A0+1
	lda     L05B3
	sec
	sbc     L05A0
	pha
	lda     L05B3+1
	sbc     L05A0+1
	tax
	pla
	sta     L05A1
	stx     L05A1+1
	cpx     #$00
	jne     L05DD
	cmp     #$00
	jne     L05DD
	jsr     decsp6
	ldy     #$0B
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$04
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	lda     L05B3
	ldx     L05B3+1
	jsr     shrax3
	ldy     #$03
	sta     (sp),y
	lda     L05B0
	ldy     #$01
	sta     (sp),y
	iny
	lda     L05B0+1
	sta     (sp),y
	lda     L05AC
	ldy     #$00
	sta     (sp),y
	ldy     #$0D
	jsr     pushwysp
	lda     #$D0
	jsr     pusha0
	lda     L05AC
	ldx     L05AC+1
	jsr     shlax3
	jsr     tossubax
	jsr     shrax3
	jsr     tosaddax
	jsr     _QrTinyRSRemainder
	ldx     #$00
	lda     #$01
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ QrTinyModuleGet (__near__ unsigned char *, unsigned int, int, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyModuleGet: near

.segment	"BSS"

L05FC:
	.res	1,$00
L05FD:
	.res	2,$00
L0605:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     _QrTinyIdentifyModule
	sta     L05FD
	stx     L05FD+1
	cpx     #$FF
	jne     L0618
	cmp     #$FF
	jne     L0618
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     _QrTinyIdentifyIndex
	sta     L0605
	stx     L0605+1
	lda     L0605
	ldx     L0605+1
	jsr     asrax3
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	lda     L0605
	and     #$07
	tay
	lda     #$01
	jsr     aslaxy
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	beq     L060F
	ldx     #$00
	lda     #$01
	jmp     L0611
L060F:	tax
L0611:	sta     L05FD
	stx     L05FD+1
	jsr     decsp3
	ldy     #$08
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     #$01
	sta     (sp),y
	iny
	txa
	sta     (sp),y
	ldy     #$05
	lda     (sp),y
	ldy     #$00
	sta     (sp),y
	ldy     #$03
	lda     (sp),y
	jsr     _QrTinyCalculateMask
	sta     L05FC
	lda     L05FC
	beq     L0618
	lda     L05FD
	ldx     L05FD+1
	eor     #$01
	sta     L05FD
	stx     L05FD+1
L0618:	lda     L05FD
	ldx     L05FD+1
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ QrTinyBufferAppend (__near__ unsigned char *, unsigned int, unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyBufferAppend: near

.segment	"BSS"

L033F:
	.res	1,$00
L0340:
	.res	1,$00
L0341:
	.res	2,$00

.segment	"CODE"

	jsr     pusha
	lda     #$00
	sta     L033F
	tax
L0792:	lda     L033F
	ldy     #$00
	cmp     (sp),y
	jcs     L0794
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     shrax3
	clc
	ldy     #$05
	adc     (sp),y
	sta     L0341
	txa
	iny
	adc     (sp),y
	sta     L0341+1
	lda     #$07
	jsr     pusha0
	ldy     #$05
	lda     (sp),y
	and     #$07
	jsr     tossuba0
	sta     L0340
	ldx     #$00
	lda     (sp,x)
	sec
	sbc     #$01
	bcs     L0791
	dex
	sec
L0791:	sbc     L033F
	pha
	txa
	sbc     #$00
	pla
	tay
	lda     #$01
	ldx     #$00
	jsr     aslaxy
	ldy     #$01
	and     (sp),y
	pha
	txa
	iny
	and     (sp),y
	sta     tmp1
	pla
	ora     tmp1
	beq     L0350
	lda     L0341
	ldx     L0341+1
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     ptr1
	ldy     L0340
	lda     #$01
L0796:	asl     a
	dey
	bpl     L0796
	ror     a
	ora     ptr1
	jmp     L0795
L0350:	lda     L0341
	ldx     L0341+1
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     ptr1
	ldy     L0340
	lda     #$01
L0797:	asl     a
	dey
	bpl     L0797
	ror     a
	eor     #$FF
	and     ptr1
L0795:	ldy     #$00
	jsr     staspidx
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     #$01
	bcc     L035D
	inx
L035D:	jsr     staxysp
	ldx     #$00
	inc     L033F
	jmp     L0792
L0794:	lda     (sp),y
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; int __near__ QrTinyIdentifyModule (unsigned char, unsigned char, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyIdentifyModule: near

.segment	"BSS"

L0360:
	.res	1,$00
L0361:
	.res	1,$00
L0362:
	.res	1,$00
L0374:
	.res	1,$00
L037C:
	.res	1,$00
L0384:
	.res	1,$00
L038C:
	.res	1,$00
L0394:
	.res	1,$00

.segment	"CODE"

	jsr     pushax
	lda     #$FF
	sta     L0362
	ldy     #$03
	lda     (sp),y
	cmp     #$15
	bcs     L079D
	dey
	lda     (sp),y
	cmp     #$15
	bcc     L0364
L079D:	ldx     #$00
	txa
	jmp     incsp4
L0364:	iny
	lda     (sp),y
	cmp     #$07
	bcs     L07C8
	dey
	lda     (sp),y
	cmp     #$07
	bcc     L07A8
	iny
L07C8:	lda     (sp),y
	cmp     #$0E
	bcc     L07C9
	dey
	lda     (sp),y
	cmp     #$07
	bcc     L07A8
	iny
L07C9:	lda     (sp),y
	cmp     #$07
	jcs     L07CA
	dey
	lda     (sp),y
	cmp     #$0E
	bcc     L0368
L07A8:	iny
	lda     (sp),y
	cmp     #$0E
	bcc     L07AA
	sec
	sbc     #$0E
	jmp     L07AB
L07AA:	lda     (sp),y
L07AB:	sta     L0374
	dey
	lda     (sp),y
	cmp     #$0E
	bcc     L07AD
	sec
	sbc     #$0E
	jmp     L07AE
L07AD:	lda     (sp),y
L07AE:	sta     L037C
	lda     L0374
	cmp     #$04
	ldx     #$00
	bcc     L07AF
	lda     L0374
	sec
	sbc     #$03
	jmp     L07B0
L07AF:	lda     #$03
	sec
	sbc     L0374
L07B0:	sta     L0384
	lda     L037C
	cmp     #$04
	bcc     L07B1
	sec
	sbc     #$03
	jmp     L07B2
L07B1:	lda     #$03
	sec
	sbc     L037C
L07B2:	sta     L038C
	lda     L0384
	sec
	sbc     L038C
	bcc     L07B3
	beq     L07B3
	lda     L0384
	jmp     L07B5
L07B3:	lda     L038C
L07B5:	sta     L0394
	and     #$01
	bne     L07CC
	jmp     incsp4
L07CC:	lda     #$01
	jmp     incsp4
L0368:	iny
L07CA:	lda     (sp),y
	cmp     #$06
	beq     L07B8
	dey
	lda     (sp),y
	cmp     #$06
	bne     L03A1
L07B8:	ldy     #$02
	lda     (sp),y
	iny
	eor     (sp),y
	ldx     #$00
	and     #$01
	beq     L07B9
	txa
	jmp     incsp4
L07B9:	lda     #$01
	jmp     incsp4
L03A1:	iny
	lda     (sp),y
	jsr     pusha0
	ldy     #$05
	lda     (sp),y
	cmp     #$06
	lda     #$00
	bcc     L03B1
	lda     #$01
L03B1:	jsr     tossuba0
	sta     L0360
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	cmp     #$06
	lda     #$00
	bcc     L03B9
	lda     #$01
L03B9:	jsr     tossuba0
	sta     L0361
	ldy     #$03
	lda     (sp),y
	cmp     #$08
	bne     L07BE
	dey
	lda     (sp),y
	cmp     #$0D
	bne     L07BE
	ldx     #$00
	lda     #$01
	jmp     incsp4
L07BE:	lda     L0360
	cmp     #$08
	bcs     L03C0
	lda     L0361
	cmp     #$08
	bcs     L03C0
	lda     #$07
	sec
	sbc     L0360
	clc
	adc     L0361
	cmp     #$80
	bcc     L03D7
	jmp     L03D7
L03C0:	ldy     #$03
	lda     (sp),y
	cmp     #$08
	bne     L03C8
	dey
	lda     (sp),y
	cmp     #$0D
	bcc     L07CB
	sec
	sbc     #$07
	cmp     #$80
	bcc     L03D7
	jmp     L03D7
L03C8:	dey
L07CB:	lda     (sp),y
	cmp     #$08
	bne     L07C5
	iny
	lda     (sp),y
	cmp     #$0D
	bcc     L07C5
	lda     #$14
	sec
	sbc     (sp),y
	cmp     #$80
L03D7:	sta     L0362
L07C5:	ldx     L0362
	bmi     L03D8
	ldy     #$01
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	ldy     L0362
	lda     ptr1
	ldx     ptr1+1
	jsr     shraxy
	ldx     #$00
	and     #$01
	beq     L035F
	lda     #$01
	jmp     incsp4
L03D8:	ldx     #$FF
	txa
L035F:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ QrTinyRSRemainder (const unsigned char *, unsigned char, const unsigned char *, unsigned char, unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyRSRemainder: near

.segment	"BSS"

L03E4:
	.res	1,$00
L03E5:
	.res	1,$00
L03E6:
	.res	1,$00
L03E7:
	.res	1,$00

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     L03E4
	tax
L07D3:	lda     L03E4
	ldy     #$02
	cmp     (sp),y
	txa
	bcs     L07D9
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L03E4
	bcc     L07CD
	inx
L07CD:	sta     ptr1
	stx     ptr1+1
	tya
	sta     (ptr1),y
	tax
	inc     L03E4
	jmp     L07D3
L07D9:	sta     L03E4
L07D5:	lda     L03E4
	ldy     #$05
	cmp     (sp),y
	txa
	sbc     #$00
	bcc     L07DA
	jmp     incsp8
L07DA:	ldy     #$07
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     L03E4
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	sta     ptr1+1
	dey
	lda     (sp),y
	sta     ptr1
	lda     (ptr1,x)
	jsr     tosxora0
	sta     L03E6
	lda     #$00
	sta     L03E5
L07D6:	lda     L03E5
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L0406
	ldx     #$FF
L0406:	jsr     tosicmp
	bcs     L0400
	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L03E5
	bcc     L07CF
	inx
L07CF:	sta     sreg
	stx     sreg+1
	ldx     #$00
	lda     L03E5
	clc
	adc     #$01
	bcc     L07D2
	inx
	clc
L07D2:	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	dey
	lda     (ptr1),y
	sta     (sreg),y
	inc     L03E5
	jmp     L07D6
L0400:	ldx     #$00
	ldy     #$02
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L040F
	dex
L040F:	clc
	ldy     #$00
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	tax
	lda     L03E6
	beq     L07D8
	ldy     L03E6
	lda     _g_log,y
	sta     L03E7
	stx     L03E5
L07D7:	lda     L03E5
	ldy     #$02
	cmp     (sp),y
	bcs     L07D8
	dey
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	clc
	adc     L03E5
	bcc     L07D0
	inx
L07D0:	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	lda     L03E7
	jsr     pusha0
	ldy     #$0A
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	ldy     L03E5
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1),y
	sta     ptr1
	lda     #$00
	clc
	adc     #>(_g_log)
	sta     ptr1+1
	ldy     #<(_g_log)
	lda     (ptr1),y
	jsr     tosadda0
	jsr     pushax
	lda     #$FF
	jsr     tosumoda0
	sta     ptr1
	txa
	clc
	adc     #>(_g_exp)
	sta     ptr1+1
	ldy     #<(_g_exp)
	lda     (ptr1),y
	jsr     tosxora0
	ldy     #$00
	jsr     staspidx
	ldx     #$00
	inc     L03E5
	jmp     L07D7
L07D8:	inc     L03E4
	jmp     L07D5

.endproc

; ---------------------------------------------------------------
; int __near__ QrGetAlphanumericVal (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrGetAlphanumericVal: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	cmp     #$30
	bcc     L07DF
	cmp     #$3A
	bcs     L07DF
	ldx     #$00
	lda     (sp),y
	sec
	sbc     #$30
	bcc     L07F4
	jmp     incsp1
L07F4:	dex
	jmp     incsp1
L07DF:	lda     (sp),y
	cmp     #$C1
	bcc     L07E4
	cmp     #$DB
	bcs     L07E4
	ldx     #$00
	lda     (sp),y
	sec
	sbc     #$C1
	bcs     L047A
	dex
L047A:	clc
	adc     #$0A
	bcc     L046E
	inx
	jmp     incsp1
L07E4:	lda     (sp),y
	cmp     #$41
	ldx     #$00
	bcc     L07E9
	lda     (sp),y
	cmp     #$5B
	bcs     L07E9
	sec
	sbc     #$41
	bcs     L0481
	dex
L0481:	clc
	adc     #$0A
	bcc     L046E
	inx
	jmp     incsp1
L07E9:	lda     (sp),y
	cmp     #$20
	beq     L07EA
	cmp     #$24
	beq     L07EB
	cmp     #$25
	beq     L07EC
	cmp     #$2A
	beq     L07ED
	cmp     #$2B
	beq     L07EE
	cmp     #$2D
	beq     L07EF
	cmp     #$2E
	beq     L07F0
	cmp     #$2F
	beq     L07F1
	cmp     #$3A
	beq     L07F2
	jmp     L07F3
L07EA:	lda     #$24
	jmp     incsp1
L07EB:	lda     #$25
	jmp     incsp1
L07EC:	lda     #$26
	jmp     incsp1
L07ED:	lda     #$27
	jmp     incsp1
L07EE:	lda     #$28
	jmp     incsp1
L07EF:	lda     #$29
	jmp     incsp1
L07F0:	lda     #$2A
	jmp     incsp1
L07F1:	lda     #$2B
	jmp     incsp1
L07F2:	lda     #$2C
	jmp     incsp1
L07F3:	txa
L046E:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned int __near__ QrTinyIdentifyIndex (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyIdentifyIndex: near

.segment	"BSS"

L050D:
	.res	1,$00
L0515:
	.res	1,$00
L051D:
	.res	1,$00
L0520:
	.res	1,$00
L0522:
	.res	1,$00
L0525:
	.res	1,$00
L0528:
	.res	1,$00
L0529:
	.res	1,$00

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	cmp     #$06
	lda     #$00
	bcc     L0513
	lda     #$01
L0513:	jsr     tossuba0
	sta     L050D
	ldx     #$00
	lda     (sp,x)
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	cmp     #$06
	lda     #$00
	bcc     L051B
	lda     #$01
L051B:	jsr     tossuba0
	sta     L0515
	lda     L050D
	lsr     a
	and     #$01
	sta     L051D
	lda     L050D
	and     #$01
	sta     L0520
	lda     #$09
	jsr     pusha0
	lda     L050D
	lsr     a
	jsr     tossuba0
	sta     L0522
	lda     #$04
	jsr     pusha0
	lda     L0515
	lsr     a
	lsr     a
	jsr     tossuba0
	sta     L0525
	ldx     #$00
	lda     L0522
	cmp     #$04
	bcs     L07FC
	lda     L051D
	beq     L07FB
	lda     L0522
	jsr     mulax3
	clc
	adc     L0525
	jmp     L0531
L07FB:	lda     L0522
	jsr     mulax3
	clc
	adc     #$02
	bcc     L0534
	inx
L0534:	sec
	sbc     L0525
	pha
	txa
	sbc     #$00
	pla
L0531:	ldx     #$00
	jmp     L07F8
L07FC:	lda     L0522
	cmp     #$06
	bcs     L07FE
	lda     L051D
	beq     L07FD
	lda     L0522
	sec
	sbc     #$04
	bcs     L053F
	dex
L053F:	jsr     mulax5
	clc
	adc     L0525
	jmp     L0540
L07FD:	lda     L0522
	sec
	sbc     #$04
	bcs     L0544
	dex
L0544:	jsr     mulax5
	clc
	adc     #$04
	bcc     L0545
	inx
L0545:	sec
	sbc     L0525
	pha
	txa
	sbc     #$00
	pla
L0540:	clc
	adc     #$0C
	ldx     #$00
	jmp     L07F8
L07FE:	lda     L0522
	clc
	adc     #$16
	sec
	sbc     #$06
L07F8:	sta     L0528
	lda     L051D
	beq     L07FF
	txa
	jmp     L0553
L07FF:	lda     #$03
L0553:	sta     ptr1
	lda     L0515
	and     #$03
	eor     ptr1
	asl     a
	clc
	adc     L0520
	sta     L0529
	lda     L0528
	jsr     shlax3
	sta     ptr1
	stx     ptr1+1
	lda     L0529
	ora     ptr1
	ldx     ptr1+1
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ QrTinyCalculateMask (unsigned int, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_QrTinyCalculateMask: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	eor     #$12
	txa
	eor     #$54
	lsr     a
	lsr     a
	ldx     #$00
	and     #$07
	beq     L0564
	cmp     #$01
	beq     L056A
	cmp     #$02
	beq     L056F
	cmp     #$03
	beq     L0574
	cmp     #$04
	beq     L0578
	cmp     #$05
	beq     L0580
	cmp     #$06
	jeq     L0587
	cmp     #$07
	jeq     L0590
	jmp     L0804
L0564:	dey
	lda     (sp),y
	clc
	dey
	adc     (sp),y
	and     #$01
	jsr     booleq
	jmp     incsp4
L056A:	lda     (sp,x)
	and     #$01
	jsr     booleq
	jmp     incsp4
L056F:	dey
	lda     (sp),y
	tay
	lda     _qrmod3,y
	jsr     booleq
	jmp     incsp4
L0574:	dey
	lda     (sp),y
	clc
	dey
	adc     (sp),y
	bcc     L0801
	inx
L0801:	sta     ptr1
	txa
	clc
	adc     #>(_qrmod3)
	sta     ptr1+1
	ldy     #<(_qrmod3)
	lda     (ptr1),y
	jsr     booleq
	jmp     incsp4
L0578:	lda     (sp,x)
	lsr     a
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	lda     #$03
	jsr     tosudiva0
	jsr     tosaddax
	and     #$01
	jsr     booleq
	jmp     incsp4
L0580:	lda     (sp,x)
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	jsr     tosumula0
	and     #$01
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$05
	lda     (sp),y
	jsr     tosumula0
	sta     ptr1
	txa
	clc
	adc     #>(_qrmod3)
	sta     ptr1+1
	ldy     #<(_qrmod3)
	lda     (ptr1),y
	jsr     tosadda0
	cpx     #$00
	bne     L0585
	cmp     #$00
L0585:	jsr     booleq
	jmp     incsp4
L0587:	lda     (sp,x)
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	jsr     tosumula0
	and     #$01
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$05
	lda     (sp),y
	jsr     tosumula0
	sta     ptr1
	txa
	clc
	adc     #>(_qrmod3)
	sta     ptr1+1
	ldy     #<(_qrmod3)
	lda     (ptr1),y
	jsr     tosadda0
	and     #$01
	jsr     booleq
	jmp     incsp4
L0590:	lda     (sp,x)
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	jsr     tosumula0
	sta     ptr1
	txa
	clc
	adc     #>(_qrmod3)
	sta     ptr1+1
	ldy     #<(_qrmod3)
	lda     (ptr1),y
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	clc
	dey
	adc     (sp),y
	and     #$01
	clc
	adc     ptr1
	and     #$01
	jsr     booleq
	jmp     incsp4
L0804:	txa
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ delay (unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay: near

.segment	"BSS"

L061E:
	.res	2,$00
L061F:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldx     #$00
	lda     #$01
	sta     L061F
	stx     L061F+1
	txa
	sta     L061E
	sta     L061E+1
L0621:	lda     L061E
	ldy     #$00
	cmp     (sp),y
	lda     L061E+1
	iny
	sbc     (sp),y
	bcs     L0622
	lda     L061F
	ldx     L061F+1
	jsr     mulax3
	sta     L061F
	stx     L061F+1
	inc     L061E
	bne     L0621
	inc     L061E+1
	jmp     L0621
L0622:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0636:
	.addr	L0635
	.addr	L0638
	.addr	L063A
	.addr	L063C
	.addr	L063E
	.addr	L0640
	.addr	L0642
	.addr	L0644
L0649:
	.word	$001E
	.word	$003C
	.word	$005A
	.word	$0078
	.word	$0096
	.word	$00B4
	.word	$00D2
	.word	$00F0
L0655:
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DC
	.byte	$DC

.segment	"BSS"

L062D:
	.res	1,$00
L0632:
	.res	63,$00
L0634:
	.res	16,$00
L0648:
	.res	16,$00
L0654:
	.res	8,$00
L065F:
	.res	1,$00
L0667:
	.res	26,$00
L0668:
	.res	2,$00
L066A:
	.res	2,$00
L066B:
	.res	1,$00
L066C:
	.res	2,$00
L066D:
	.res	2,$00
L066E:
	.res	2,$00
L066F:
	.res	2,$00
L0671:
	.res	1,$00
L0673:
	.res	2,$00
L0675:
	.res	2,$00
L0677:
	.res	2,$00
L06D7:
	.res	2,$00
L06DF:
	.res	2,$00
L06E4:
	.res	2,$00

.segment	"CODE"

	lda     #$00
	sta     L062D
	ldy     #$0F
L0646:	lda     L0636,y
	sta     L0634,y
	dey
	bpl     L0646
	ldy     #$0F
L0652:	lda     L0649,y
	sta     L0648,y
	dey
	bpl     L0652
	ldy     #$07
L065E:	lda     L0655,y
	sta     L0654,y
	dey
	bpl     L065E
	ldx     #$77
	lda     #$C4
	sta     L0668
	stx     L0668+1
	lda     #$00
	sta     L066F
	sta     L066F+1
	sta     L0671
	sta     L0673
	sta     L0673+1
	sta     L0675
	sta     L0675+1
	sta     L0677
	sta     L0677+1
	lda     #$05
	sta     $D027
	lda     #$02
	sta     $D028
	lda     #$01
	sta     $D029
	lda     #$07
	sta     $D02A
	lda     #$09
	sta     $D02B
	lda     #$00
	sta     $D02C
	lda     #$03
	sta     $D02D
	lda     #$04
	sta     $D02E
	lda     #$00
	sta     $D015
L069C:	lda     L066F
	cmp     #$08
	lda     L066F+1
	sbc     #$00
	bvc     L06A2
	eor     #$80
L06A2:	jpl     L06A0
	ldx     #$04
	lda     #$00
	jsr     pushax
	lda     #$20
	jsr     pusha0
	ldx     #$03
	lda     #$E8
	jsr     _memset
	ldx     #$00
	lda     #$13
	jsr     _putchar
	lda     #<(L06AA)
	ldx     #>(L06AA)
	jsr     pushax
	lda     L066F
	ldx     L066F+1
	clc
	adc     #$01
	bcc     L06AD
	inx
L06AD:	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldy     #$3E
	lda     #$00
L06B3:	sta     L0632,y
	dey
	bpl     L06B3
	lda     #$00
	sta     L066A
	sta     L066A+1
	jsr     decsp4
	lda     #<(L0667)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0667)
	sta     (sp),y
	lda     L066A
	ldy     #$00
	sta     (sp),y
	iny
	lda     L066A+1
	sta     (sp),y
	lda     L066F
	ldx     L066F+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(L0634)
	sta     ptr1
	lda     tmp1
	adc     #>(L0634)
	sta     ptr1+1
	lda     (ptr1),y
	tax
	dey
	lda     (ptr1),y
	jsr     _QrTinyWriteAlphanumeric
	clc
	adc     L066A
	sta     L066A
	txa
	adc     L066A+1
	sta     L066A+1
	jsr     decsp4
	lda     #<(L0667)
	ldy     #$02
	sta     (sp),y
	iny
	lda     #>(L0667)
	sta     (sp),y
	lda     L066A
	ldy     #$00
	sta     (sp),y
	iny
	lda     L066A+1
	sta     (sp),y
	lda     L0668
	ldx     L0668+1
	jsr     _QrTinyGenerate
	sta     L066B
	lda     L066B
	jeq     L06C4
	lda     #$00
	sta     L066C
	sta     L066C+1
L06C3:	lda     L066C
	cmp     #$15
	lda     L066C+1
	sbc     #$00
	bvc     L06CA
	eor     #$80
L06CA:	jpl     L06C4
	lda     #$00
	sta     L066D
	sta     L066D+1
L06CD:	lda     L066D
	cmp     #$15
	lda     L066D+1
	sbc     #$00
	bvc     L06D4
	eor     #$80
L06D4:	jpl     L06C5
	jsr     decsp6
	lda     #<(L0667)
	ldy     #$04
	sta     (sp),y
	iny
	lda     #>(L0667)
	sta     (sp),y
	lda     L0668
	ldy     #$02
	sta     (sp),y
	iny
	lda     L0668+1
	sta     (sp),y
	lda     L066D
	ldy     #$00
	sta     (sp),y
	iny
	lda     L066D+1
	sta     (sp),y
	lda     L066C
	ldx     L066C+1
	jsr     _QrTinyModuleGet
	sta     L06D7
	stx     L06D7+1
	lda     L06D7
	ora     L06D7+1
	beq     L06CF
	lda     L066C
	ldx     L066C+1
	jsr     mulax3
	jsr     pushax
	lda     L066D
	ldx     L066D+1
	jsr     asrax3
	jsr     tosaddax
	sta     L06DF
	stx     L06DF+1
	lda     #$07
	jsr     pusha0
	lda     L066D
	ldx     L066D+1
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     tosmoda0
	jsr     tossubax
	sta     L06E4
	stx     L06E4+1
	lda     #<(L0632)
	clc
	adc     L06DF
	tay
	lda     #>(L0632)
	adc     L06DF+1
	tax
	tya
	jsr     pushax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     ptr1
	ldy     L06E4
	lda     #$01
L0811:	asl     a
	dey
	bpl     L0811
	ror     a
	ora     ptr1
	ldy     #$00
	jsr     staspidx
L06CF:	lda     L066D
	ldx     L066D+1
	clc
	adc     #$01
	bcc     L06D6
	inx
L06D6:	sta     L066D
	stx     L066D+1
	jmp     L06CD
L06C5:	lda     L066C
	ldx     L066C+1
	clc
	adc     #$01
	bcc     L06CC
	inx
L06CC:	sta     L066C
	stx     L066C+1
	jmp     L06C3
L06C4:	lda     L066F
	ldx     L066F+1
	jsr     aslax4
	jsr     aslax2
	pha
	txa
	clc
	adc     #$38
	tax
	pla
	jsr     pushax
	lda     #<(L0632)
	ldx     #>(L0632)
	jsr     pushax
	ldx     #$00
	lda     #$3F
	jsr     _memcpy
	lda     L066F
	clc
	adc     #$F8
	sta     ptr1
	lda     L066F+1
	adc     #$07
	sta     ptr1+1
	lda     L066F
	ldx     L066F+1
	jsr     aslax4
	jsr     aslax2
	pha
	txa
	clc
	adc     #$38
	tax
	pla
	jsr     asrax4
	jsr     asrax2
	ldy     #$00
	sta     (ptr1),y
	lda     L066F
	ldx     L066F+1
	stx     tmp1
	asl     a
	rol     tmp1
	sta     sreg
	lda     tmp1
	clc
	adc     #$D0
	sta     sreg+1
	lda     L066F
	ldx     L066F+1
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     tmp1
	clc
	adc     #>(L0648)
	sta     ptr1+1
	ldy     #<(L0648)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	lda     L066F
	ldx     L066F+1
	stx     tmp1
	asl     a
	rol     tmp1
	sta     sreg
	lda     tmp1
	clc
	adc     #$D0
	sta     sreg+1
	lda     #<(L0654)
	sta     ptr1
	lda     #>(L0654)
	clc
	adc     L066F+1
	sta     ptr1+1
	ldy     L066F
	lda     (ptr1),y
	ldy     #$01
	sta     (sreg),y
	ldy     L066F
	lda     #$01
L0812:	asl     a
	dey
	bpl     L0812
	ror     a
	ora     $D015
	sta     $D015
	lda     L066F
	ldx     L066F+1
	clc
	adc     #$01
	bcc     L0707
	inx
L0707:	sta     L066F
	stx     L066F+1
	jmp     L070F
L06A0:	ldx     #$04
	lda     #$00
	jsr     pushax
	lda     #$20
	jsr     pusha0
	ldx     #$03
	lda     #$E8
	jsr     _memset
	lda     L0673
	ldx     L0673+1
	clc
	adc     #$01
	bcc     L070E
	inx
L070E:	sta     L0673
	stx     L0673+1
	lda     L0673
	cmp     #$3C
	lda     L0673+1
	sbc     #$00
	bvs     L0711
	eor     #$80
L0711:	jpl     L070F
	ldx     #$00
	txa
	sta     L0673
	sta     L0673+1
	lda     L0671
	bne     L080B
	lda     L062D
	asl     a
	bcc     L0808
	inx
	clc
L0808:	adc     #<(L0648)
	sta     ptr1
	txa
	adc     #>(L0648)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	sta     L0675+1
	dey
	lda     (ptr1),y
	sta     L0675
	ldy     L062D
	lda     #$00
	sta     L0677+1
	lda     L0654,y
	sta     L0677
	ldx     #$00
	lda     L062D
	asl     a
	bcc     L0809
	inx
	clc
L0809:	adc     #<(L0648)
	sta     ptr1
	txa
	adc     #>(L0648)
	sta     ptr1+1
	lda     #$50
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
	ldy     L062D
	lda     #$50
	sta     L0654,y
	lda     #$00
	sta     $D017
	sta     $D01D
	ldy     L062D
	lda     #$01
L0813:	asl     a
	dey
	bpl     L0813
	ror     a
	ora     $D017
	sta     $D017
	ldy     L062D
	lda     #$01
L0814:	asl     a
	dey
	bpl     L0814
	ror     a
	ora     $D01D
	sta     $D01D
	jmp     L0741
L080B:	lda     L062D
	asl     a
	bcc     L080A
	inx
	clc
L080A:	adc     #<(L0648)
	sta     ptr1
	txa
	adc     #>(L0648)
	sta     ptr1+1
	lda     L0675
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     L0675+1
	sta     (ptr1),y
	ldy     L062D
	lda     L0677
	sta     L0654,y
	lda     #$00
	sta     $D017
	sta     $D01D
	inc     L062D
	lda     L062D
	cmp     #$08
	bcc     L0741
	lda     #$00
	sta     L062D
L0741:	lda     L0671
	jsr     bnega
	sta     L0671
L070F:	jsr     _waitvsync
	lda     #$00
	sta     L066E
	sta     L066E+1
L0748:	lda     L066E
	cmp     #$08
	lda     L066E+1
	sbc     #$00
	bvc     L074F
	eor     #$80
L074F:	asl     a
	lda     #$00
	bcc     L080D
	lda     L066E
	ldx     L066E+1
	stx     tmp1
	asl     a
	rol     tmp1
	sta     sreg
	lda     tmp1
	clc
	adc     #$D0
	sta     sreg+1
	lda     L066E
	ldx     L066E+1
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     tmp1
	clc
	adc     #>(L0648)
	sta     ptr1+1
	ldy     #<(L0648)
	lda     (ptr1),y
	ldy     #$00
	sta     (sreg),y
	lda     L066E
	ldx     L066E+1
	stx     tmp1
	asl     a
	rol     tmp1
	sta     sreg
	lda     tmp1
	clc
	adc     #$D0
	sta     sreg+1
	lda     #<(L0654)
	sta     ptr1
	lda     #>(L0654)
	clc
	adc     L066E+1
	sta     ptr1+1
	ldy     L066E
	lda     (ptr1),y
	ldy     #$01
	sta     (sreg),y
	lda     L066E
	ldx     L066E+1
	clc
	adc     #$01
	bcc     L0751
	inx
L0751:	sta     L066E
	stx     L066E+1
	jmp     L0748
L080D:	sta     $D010
	sta     L066E
	sta     L066E+1
L075F:	lda     L066E
	cmp     #$08
	lda     L066E+1
	sbc     #$00
	bvc     L0766
	eor     #$80
L0766:	bpl     L080E
	lda     L066E
	ldx     L066E+1
	stx     tmp1
	asl     a
	rol     tmp1
	clc
	adc     #<(L0648)
	sta     ptr1
	lda     tmp1
	adc     #>(L0648)
	sta     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	and     #$01
	beq     L0761
	ldy     L066E
	lda     #$01
L0815:	asl     a
	dey
	bpl     L0815
	ror     a
	ora     $D010
	sta     $D010
L0761:	lda     L066E
	ldx     L066E+1
	clc
	adc     #$01
	bcc     L0768
	inx
L0768:	sta     L066E
	stx     L066E+1
	jmp     L075F
L080E:	lda     $D01F
	sta     L065F
	and     #$01
	beq     L080F
	lda     #$07
	jmp     L0810
L080F:	lda     #$05
L0810:	sta     $D027
	jmp     L069C

.endproc

