;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.import		_tgi_static_stddrv
	.import		_tgi_install
	.import		_tgi_init
	.import		_tgi_clear
	.import		_tgi_setcolor
	.import		_tgi_setpixel
	.import		_tgi_line
	.import		_tgi_bar
	.import		_kbhit
	.import		_cgetc
	.import		_bordercolor
	.export		_alphabet
	.export		_findcharindex
	.export		_drawchar
	.export		_drawstring
	.export		_drawWrappedString
	.export		_toggle_clear
	.export		_x0
	.export		_y0
	.export		_z0
	.export		_x1
	.export		_y1
	.export		_z1
	.export		_x2
	.export		_y2
	.export		_z2
	.export		_x3
	.export		_y3
	.export		_z3
	.export		_x4
	.export		_y4
	.export		_z4
	.export		_x5
	.export		_y5
	.export		_z5
	.export		_x6
	.export		_y6
	.export		_z6
	.export		_x7
	.export		_y7
	.export		_z7
	.export		_rotX
	.export		_rotY
	.export		_rotZ
	.export		_rotate_x
	.export		_rotate_y
	.export		_rotate_z
	.export		_draw_cube
	.export		_itoa_custom
	.export		_msgcat
	.export		_main

.segment	"DATA"

_toggle_clear:
	.byte	$00
_x0:
	.dword	$FFFFFFCE
_y0:
	.dword	$FFFFFFCE
_z0:
	.dword	$FFFFFFCE
_x1:
	.dword	$00000032
_y1:
	.dword	$FFFFFFCE
_z1:
	.dword	$FFFFFFCE
_x2:
	.dword	$00000032
_y2:
	.dword	$00000032
_z2:
	.dword	$FFFFFFCE
_x3:
	.dword	$FFFFFFCE
_y3:
	.dword	$00000032
_z3:
	.dword	$FFFFFFCE
_x4:
	.dword	$FFFFFFCE
_y4:
	.dword	$FFFFFFCE
_z4:
	.dword	$00000032
_x5:
	.dword	$00000032
_y5:
	.dword	$FFFFFFCE
_z5:
	.dword	$00000032
_x6:
	.dword	$00000032
_y6:
	.dword	$00000032
_z6:
	.dword	$00000032
_x7:
	.dword	$FFFFFFCE
_y7:
	.dword	$00000032
_z7:
	.dword	$00000032
_rotX:
	.word	$0000
_rotY:
	.word	$0000
_rotZ:
	.word	$0000

.segment	"RODATA"

_sine:
	.word	$0000
	.word	$00AE
	.word	$015C
	.word	$020B
	.word	$02B9
	.word	$0367
	.word	$0415
	.word	$04C2
	.word	$056F
	.word	$061C
	.word	$06C8
	.word	$0774
	.word	$081F
	.word	$08C9
	.word	$0973
	.word	$0A1C
	.word	$0AC4
	.word	$0B6B
	.word	$0C12
	.word	$0CB7
	.word	$0D5C
	.word	$0DFF
	.word	$0EA2
	.word	$0F43
	.word	$0FE3
	.word	$1082
	.word	$1120
	.word	$11BC
	.word	$1257
	.word	$12F0
	.word	$1388
	.word	$141E
	.word	$14B3
	.word	$1546
	.word	$15D8
	.word	$1668
	.word	$16F6
	.word	$1782
	.word	$180D
	.word	$1895
	.word	$191C
	.word	$19A1
	.word	$1A23
	.word	$1AA4
	.word	$1B23
	.word	$1B9F
	.word	$1C19
	.word	$1C92
	.word	$1D07
	.word	$1D7B
	.word	$1DEC
	.word	$1E5B
	.word	$1EC8
	.word	$1F32
	.word	$1F9A
	.word	$2000
	.word	$2062
	.word	$20C3
	.word	$2120
	.word	$217C
	.word	$21D4
	.word	$222A
	.word	$227D
	.word	$22CE
	.word	$231C
	.word	$2367
	.word	$23AF
	.word	$23F5
	.word	$2438
	.word	$2478
	.word	$24B5
	.word	$24EF
	.word	$2527
	.word	$255B
	.word	$258D
	.word	$25BB
	.word	$25E7
	.word	$2610
	.word	$2635
	.word	$2658
	.word	$2678
	.word	$2695
	.word	$26AF
	.word	$26C5
	.word	$26D9
	.word	$26E9
	.word	$26F7
	.word	$2702
	.word	$270A
	.word	$270E
	.word	$2710
	.word	$270E
	.word	$270A
	.word	$2702
	.word	$26F7
	.word	$26E9
	.word	$26D9
	.word	$26C5
	.word	$26AF
	.word	$2695
	.word	$2678
	.word	$2658
	.word	$2635
	.word	$2610
	.word	$25E7
	.word	$25BB
	.word	$258D
	.word	$255B
	.word	$2527
	.word	$24EF
	.word	$24B5
	.word	$2478
	.word	$2438
	.word	$23F5
	.word	$23AF
	.word	$2367
	.word	$231C
	.word	$22CE
	.word	$227D
	.word	$222A
	.word	$21D4
	.word	$217C
	.word	$2120
	.word	$20C3
	.word	$2062
	.word	$2000
	.word	$1F9A
	.word	$1F32
	.word	$1EC8
	.word	$1E5B
	.word	$1DEC
	.word	$1D7B
	.word	$1D07
	.word	$1C92
	.word	$1C19
	.word	$1B9F
	.word	$1B23
	.word	$1AA4
	.word	$1A23
	.word	$19A1
	.word	$191C
	.word	$1895
	.word	$180D
	.word	$1782
	.word	$16F6
	.word	$1668
	.word	$15D8
	.word	$1546
	.word	$14B3
	.word	$141E
	.word	$1388
	.word	$12F0
	.word	$1257
	.word	$11BC
	.word	$1120
	.word	$1082
	.word	$0FE3
	.word	$0F43
	.word	$0EA2
	.word	$0DFF
	.word	$0D5C
	.word	$0CB7
	.word	$0C12
	.word	$0B6B
	.word	$0AC4
	.word	$0A1C
	.word	$0973
	.word	$08C9
	.word	$081F
	.word	$0774
	.word	$06C8
	.word	$061C
	.word	$056F
	.word	$04C2
	.word	$0415
	.word	$0367
	.word	$02B9
	.word	$020B
	.word	$015C
	.word	$00AE
	.word	$0000
	.word	$FF52
	.word	$FEA4
	.word	$FDF5
	.word	$FD47
	.word	$FC99
	.word	$FBEB
	.word	$FB3E
	.word	$FA91
	.word	$F9E4
	.word	$F938
	.word	$F88C
	.word	$F7E1
	.word	$F737
	.word	$F68D
	.word	$F5E4
	.word	$F53C
	.word	$F495
	.word	$F3EE
	.word	$F349
	.word	$F2A4
	.word	$F201
	.word	$F15E
	.word	$F0BD
	.word	$F01D
	.word	$EF7E
	.word	$EEE0
	.word	$EE44
	.word	$EDA9
	.word	$ED10
	.word	$EC78
	.word	$EBE2
	.word	$EB4D
	.word	$EABA
	.word	$EA28
	.word	$E998
	.word	$E90A
	.word	$E87E
	.word	$E7F3
	.word	$E76B
	.word	$E6E4
	.word	$E65F
	.word	$E5DD
	.word	$E55C
	.word	$E4DD
	.word	$E461
	.word	$E3E7
	.word	$E36E
	.word	$E2F9
	.word	$E285
	.word	$E214
	.word	$E1A5
	.word	$E138
	.word	$E0CE
	.word	$E066
	.word	$E000
	.word	$DF9E
	.word	$DF3D
	.word	$DEE0
	.word	$DE84
	.word	$DE2C
	.word	$DDD6
	.word	$DD83
	.word	$DD32
	.word	$DCE4
	.word	$DC99
	.word	$DC51
	.word	$DC0B
	.word	$DBC8
	.word	$DB88
	.word	$DB4B
	.word	$DB11
	.word	$DAD9
	.word	$DAA5
	.word	$DA73
	.word	$DA45
	.word	$DA19
	.word	$D9F0
	.word	$D9CB
	.word	$D9A8
	.word	$D988
	.word	$D96B
	.word	$D951
	.word	$D93B
	.word	$D927
	.word	$D917
	.word	$D909
	.word	$D8FE
	.word	$D8F6
	.word	$D8F2
	.word	$D8F0
	.word	$D8F2
	.word	$D8F6
	.word	$D8FE
	.word	$D909
	.word	$D917
	.word	$D927
	.word	$D93B
	.word	$D951
	.word	$D96B
	.word	$D988
	.word	$D9A8
	.word	$D9CB
	.word	$D9F0
	.word	$DA19
	.word	$DA45
	.word	$DA73
	.word	$DAA5
	.word	$DAD9
	.word	$DB11
	.word	$DB4B
	.word	$DB88
	.word	$DBC8
	.word	$DC0B
	.word	$DC51
	.word	$DC99
	.word	$DCE4
	.word	$DD32
	.word	$DD83
	.word	$DDD6
	.word	$DE2C
	.word	$DE84
	.word	$DEE0
	.word	$DF3D
	.word	$DF9E
	.word	$E000
	.word	$E066
	.word	$E0CE
	.word	$E138
	.word	$E1A5
	.word	$E214
	.word	$E285
	.word	$E2F9
	.word	$E36E
	.word	$E3E7
	.word	$E461
	.word	$E4DD
	.word	$E55C
	.word	$E5DD
	.word	$E65F
	.word	$E6E4
	.word	$E76B
	.word	$E7F3
	.word	$E87E
	.word	$E90A
	.word	$E998
	.word	$EA28
	.word	$EABA
	.word	$EB4D
	.word	$EBE2
	.word	$EC78
	.word	$ED10
	.word	$EDA9
	.word	$EE44
	.word	$EEE0
	.word	$EF7E
	.word	$F01D
	.word	$F0BD
	.word	$F15E
	.word	$F201
	.word	$F2A4
	.word	$F349
	.word	$F3EE
	.word	$F495
	.word	$F53C
	.word	$F5E4
	.word	$F68D
	.word	$F737
	.word	$F7E1
	.word	$F88C
	.word	$F938
	.word	$F9E4
	.word	$FA91
	.word	$FB3E
	.word	$FBEB
	.word	$FC99
	.word	$FD47
	.word	$FDF5
	.word	$FEA4
	.word	$FF52
_cosine:
	.word	$2710
	.word	$270E
	.word	$270A
	.word	$2702
	.word	$26F7
	.word	$26E9
	.word	$26D9
	.word	$26C5
	.word	$26AF
	.word	$2695
	.word	$2678
	.word	$2658
	.word	$2635
	.word	$2610
	.word	$25E7
	.word	$25BB
	.word	$258D
	.word	$255B
	.word	$2527
	.word	$24EF
	.word	$24B5
	.word	$2478
	.word	$2438
	.word	$23F5
	.word	$23AF
	.word	$2367
	.word	$231C
	.word	$22CE
	.word	$227D
	.word	$222A
	.word	$21D4
	.word	$217C
	.word	$2120
	.word	$20C3
	.word	$2062
	.word	$2000
	.word	$1F9A
	.word	$1F32
	.word	$1EC8
	.word	$1E5B
	.word	$1DEC
	.word	$1D7B
	.word	$1D07
	.word	$1C92
	.word	$1C19
	.word	$1B9F
	.word	$1B23
	.word	$1AA4
	.word	$1A23
	.word	$19A1
	.word	$191C
	.word	$1895
	.word	$180D
	.word	$1782
	.word	$16F6
	.word	$1668
	.word	$15D8
	.word	$1546
	.word	$14B3
	.word	$141E
	.word	$1388
	.word	$12F0
	.word	$1257
	.word	$11BC
	.word	$1120
	.word	$1082
	.word	$0FE3
	.word	$0F43
	.word	$0EA2
	.word	$0DFF
	.word	$0D5C
	.word	$0CB7
	.word	$0C12
	.word	$0B6B
	.word	$0AC4
	.word	$0A1C
	.word	$0973
	.word	$08C9
	.word	$081F
	.word	$0774
	.word	$06C8
	.word	$061C
	.word	$056F
	.word	$04C2
	.word	$0415
	.word	$0367
	.word	$02B9
	.word	$020B
	.word	$015C
	.word	$00AE
	.word	$0000
	.word	$FF52
	.word	$FEA4
	.word	$FDF5
	.word	$FD47
	.word	$FC99
	.word	$FBEB
	.word	$FB3E
	.word	$FA91
	.word	$F9E4
	.word	$F938
	.word	$F88C
	.word	$F7E1
	.word	$F737
	.word	$F68D
	.word	$F5E4
	.word	$F53C
	.word	$F495
	.word	$F3EE
	.word	$F349
	.word	$F2A4
	.word	$F201
	.word	$F15E
	.word	$F0BD
	.word	$F01D
	.word	$EF7E
	.word	$EEE0
	.word	$EE44
	.word	$EDA9
	.word	$ED10
	.word	$EC78
	.word	$EBE2
	.word	$EB4D
	.word	$EABA
	.word	$EA28
	.word	$E998
	.word	$E90A
	.word	$E87E
	.word	$E7F3
	.word	$E76B
	.word	$E6E4
	.word	$E65F
	.word	$E5DD
	.word	$E55C
	.word	$E4DD
	.word	$E461
	.word	$E3E7
	.word	$E36E
	.word	$E2F9
	.word	$E285
	.word	$E214
	.word	$E1A5
	.word	$E138
	.word	$E0CE
	.word	$E066
	.word	$E000
	.word	$DF9E
	.word	$DF3D
	.word	$DEE0
	.word	$DE84
	.word	$DE2C
	.word	$DDD6
	.word	$DD83
	.word	$DD32
	.word	$DCE4
	.word	$DC99
	.word	$DC51
	.word	$DC0B
	.word	$DBC8
	.word	$DB88
	.word	$DB4B
	.word	$DB11
	.word	$DAD9
	.word	$DAA5
	.word	$DA73
	.word	$DA45
	.word	$DA19
	.word	$D9F0
	.word	$D9CB
	.word	$D9A8
	.word	$D988
	.word	$D96B
	.word	$D951
	.word	$D93B
	.word	$D927
	.word	$D917
	.word	$D909
	.word	$D8FE
	.word	$D8F6
	.word	$D8F2
	.word	$D8F0
	.word	$D8F2
	.word	$D8F6
	.word	$D8FE
	.word	$D909
	.word	$D917
	.word	$D927
	.word	$D93B
	.word	$D951
	.word	$D96B
	.word	$D988
	.word	$D9A8
	.word	$D9CB
	.word	$D9F0
	.word	$DA19
	.word	$DA45
	.word	$DA73
	.word	$DAA5
	.word	$DAD9
	.word	$DB11
	.word	$DB4B
	.word	$DB88
	.word	$DBC8
	.word	$DC0B
	.word	$DC51
	.word	$DC99
	.word	$DCE4
	.word	$DD32
	.word	$DD83
	.word	$DDD6
	.word	$DE2C
	.word	$DE84
	.word	$DEE0
	.word	$DF3D
	.word	$DF9E
	.word	$E000
	.word	$E066
	.word	$E0CE
	.word	$E138
	.word	$E1A5
	.word	$E214
	.word	$E285
	.word	$E2F9
	.word	$E36E
	.word	$E3E7
	.word	$E461
	.word	$E4DD
	.word	$E55C
	.word	$E5DD
	.word	$E65F
	.word	$E6E4
	.word	$E76B
	.word	$E7F3
	.word	$E87E
	.word	$E90A
	.word	$E998
	.word	$EA28
	.word	$EABA
	.word	$EB4D
	.word	$EBE2
	.word	$EC78
	.word	$ED10
	.word	$EDA9
	.word	$EE44
	.word	$EEE0
	.word	$EF7E
	.word	$F01D
	.word	$F0BD
	.word	$F15E
	.word	$F201
	.word	$F2A4
	.word	$F349
	.word	$F3EE
	.word	$F495
	.word	$F53C
	.word	$F5E4
	.word	$F68D
	.word	$F737
	.word	$F7E1
	.word	$F88C
	.word	$F938
	.word	$F9E4
	.word	$FA91
	.word	$FB3E
	.word	$FBEB
	.word	$FC99
	.word	$FD47
	.word	$FDF5
	.word	$FEA4
	.word	$FF52
	.word	$0000
	.word	$00AE
	.word	$015C
	.word	$020B
	.word	$02B9
	.word	$0367
	.word	$0415
	.word	$04C2
	.word	$056F
	.word	$061C
	.word	$06C8
	.word	$0774
	.word	$081F
	.word	$08C9
	.word	$0973
	.word	$0A1C
	.word	$0AC4
	.word	$0B6B
	.word	$0C12
	.word	$0CB7
	.word	$0D5C
	.word	$0DFF
	.word	$0EA2
	.word	$0F43
	.word	$0FE3
	.word	$1082
	.word	$1120
	.word	$11BC
	.word	$1257
	.word	$12F0
	.word	$1388
	.word	$141E
	.word	$14B3
	.word	$1546
	.word	$15D8
	.word	$1668
	.word	$16F6
	.word	$1782
	.word	$180D
	.word	$1895
	.word	$191C
	.word	$19A1
	.word	$1A23
	.word	$1AA4
	.word	$1B23
	.word	$1B9F
	.word	$1C19
	.word	$1C92
	.word	$1D07
	.word	$1D7B
	.word	$1DEC
	.word	$1E5B
	.word	$1EC8
	.word	$1F32
	.word	$1F9A
	.word	$2000
	.word	$2062
	.word	$20C3
	.word	$2120
	.word	$217C
	.word	$21D4
	.word	$222A
	.word	$227D
	.word	$22CE
	.word	$231C
	.word	$2367
	.word	$23AF
	.word	$23F5
	.word	$2438
	.word	$2478
	.word	$24B5
	.word	$24EF
	.word	$2527
	.word	$255B
	.word	$258D
	.word	$25BB
	.word	$25E7
	.word	$2610
	.word	$2635
	.word	$2658
	.word	$2678
	.word	$2695
	.word	$26AF
	.word	$26C5
	.word	$26D9
	.word	$26E9
	.word	$26F7
	.word	$2702
	.word	$270A
	.word	$270E
_alphabet:
	.word	$000F
	.word	$0009
	.word	$000F
	.word	$0009
	.word	$0008
	.word	$000E
	.word	$000A
	.word	$000E
	.word	$000F
	.word	$0008
	.word	$0008
	.word	$000F
	.word	$000E
	.word	$0009
	.word	$0009
	.word	$000E
	.word	$000F
	.word	$000E
	.word	$0008
	.word	$000F
	.word	$000F
	.word	$000E
	.word	$0008
	.word	$0008
	.word	$000F
	.word	$0008
	.word	$0009
	.word	$000F
	.word	$0008
	.word	$0008
	.word	$000F
	.word	$0009
	.word	$0004
	.word	$0004
	.word	$0004
	.word	$0004
	.word	$0004
	.word	$0004
	.word	$0004
	.word	$000C
	.word	$000A
	.word	$000C
	.word	$000A
	.word	$0009
	.word	$0008
	.word	$0008
	.word	$0008
	.word	$000F
	.word	$0009
	.word	$000F
	.word	$0009
	.word	$0009
	.word	$0009
	.word	$000D
	.word	$000B
	.word	$0009
	.word	$000F
	.word	$0009
	.word	$0009
	.word	$000F
	.word	$000F
	.word	$0009
	.word	$000E
	.word	$0008
	.word	$000F
	.word	$0009
	.word	$000F
	.word	$0001
	.word	$000E
	.word	$0009
	.word	$000C
	.word	$000A
	.word	$000F
	.word	$0008
	.word	$0001
	.word	$000F
	.word	$000F
	.word	$0004
	.word	$0004
	.word	$0004
	.word	$0009
	.word	$0009
	.word	$0009
	.word	$000F
	.word	$0009
	.word	$0005
	.word	$0003
	.word	$0001
	.word	$0009
	.word	$0009
	.word	$0009
	.word	$0006
	.word	$0000
	.word	$000A
	.word	$0004
	.word	$000A
	.word	$0009
	.word	$0006
	.word	$0002
	.word	$0002
	.word	$000F
	.word	$0004
	.word	$0002
	.word	$000F
	.word	$0006
	.word	$000A
	.word	$000A
	.word	$000C
	.word	$0002
	.word	$0006
	.word	$0002
	.word	$0002
	.word	$0006
	.word	$0002
	.word	$0004
	.word	$0006
	.word	$0006
	.word	$0003
	.word	$0001
	.word	$0006
	.word	$0005
	.word	$0007
	.word	$0001
	.word	$0001
	.word	$0006
	.word	$0004
	.word	$0002
	.word	$0006
	.word	$0004
	.word	$0006
	.word	$0005
	.word	$0003
	.word	$0007
	.word	$0005
	.word	$0001
	.word	$0001
	.word	$0007
	.word	$0005
	.word	$0007
	.word	$0007
	.word	$0006
	.word	$0005
	.word	$0003
	.word	$0001
	.word	$0000
	.word	$0000
	.word	$0004
	.word	$0008
	.word	$0000
	.word	$0000
	.word	$0006
	.word	$0006
	.word	$0001
	.word	$0002
	.word	$0004
	.word	$0008
	.word	$0001
	.word	$0002
	.word	$0004
	.word	$0008
L0555:
	.byte	$C3,$D5,$C2,$C5,$20,$D2,$CF,$D4,$C1,$D4,$C5,$20,$D3,$D0,$C1,$C3
	.byte	$C5,$20,$C2,$C1,$D2,$20,$D4,$CF,$C7,$C7,$CC,$C5,$D3,$20,$D3,$C3
	.byte	$D2,$C5,$C5,$CE,$20,$D7,$C9,$D0,$C5,$20,$C1,$C6,$D4,$C5,$D2,$20
	.byte	$C5,$C1,$C3,$C8,$20,$D2,$CF,$D4,$C1,$D4,$C9,$CF,$CE,$20,$00
L0553:
	.byte	$C4,$C5,$C2,$D5,$C7,$20,$CD,$CF,$C4,$C5,$20,$2D,$20,$50,$41,$49
	.byte	$4E,$54,$49,$4E,$47,$20,$48,$41,$4C,$46,$20,$4F,$46,$20,$53,$43
	.byte	$52,$45,$45,$4E,$20,$54,$4F,$20,$43,$4C,$45,$41,$52,$2C,$20,$49
	.byte	$54,$53,$20,$53,$4C,$4F,$57,$00
L03BB:
	.byte	$43,$48,$41,$52,$41,$43,$54,$45,$52,$20,$27,$25,$43,$27,$20,$4E
	.byte	$4F,$54,$20,$46,$4F,$55,$4E,$44,$0D,$00

; ---------------------------------------------------------------
; int __near__ findcharindex (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_findcharindex: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	cmp     #$C1
	bcc     L05F9
	cmp     #$DB
	bcs     L05F9
	ldx     #$00
	lda     (sp),y
	ldy     #$C1
	jsr     decaxy
	jmp     incsp1
L05F9:	lda     (sp),y
	cmp     #$30
	bcc     L05FE
	cmp     #$3A
	bcs     L05FE
	ldx     #$00
	lda     (sp),y
	ldy     #$30
	jsr     decaxy
	ldy     #$1A
	jsr     incaxy
	jmp     incsp1
L05FE:	lda     (sp),y
	cmp     #$2C
	bne     L0600
	ldx     #$00
	lda     #$24
	jmp     incsp1
L0600:	lda     (sp),y
	cmp     #$2E
	bne     L0602
	ldx     #$00
	lda     #$25
	jmp     incsp1
L0602:	lda     (sp),y
	cmp     #$2F
	bne     L038D
	ldx     #$00
	lda     #$26
	jmp     incsp1
L038D:	ldx     #$FF
	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ drawchar (unsigned char, unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawchar: near

.segment	"CODE"

	jsr     pusha
	lda     #$04
	jsr     pusha0
	jsr     decsp2
	ldy     #$07
	lda     (sp),y
	jsr     _findcharindex
	jsr     stax0sp
	cpx     #$FF
	bne     L0606
	cmp     #$FF
	jeq     L0397
L0606:	jsr     ldax0sp
	jsr     aslax3
	clc
	adc     #<(_alphabet)
	tay
	txa
	adc     #>(_alphabet)
	tax
	tya
	jsr     pushax
	jsr     decsp8
	ldx     #$00
	txa
L060A:	ldy     #$04
	jsr     staxysp
	ldy     #$0C
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bvc     L0603
	eor     #$80
L0603:	jpl     L039D
	ldx     #$00
	txa
L0609:	ldy     #$06
	jsr     staxysp
	ldy     #$0C
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bvc     L0604
	eor     #$80
L0604:	bpl     L03A5
	ldy     #$09
	jsr     ldaxysp
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$0D
	jsr     ldaxysp
	jsr     decax1
	sec
	ldy     #$06
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	pla
	tay
	lda     #$01
	ldx     #$00
	jsr     aslaxy
	and     ptr1
	pha
	txa
	and     ptr1+1
	sta     tmp1
	pla
	ora     tmp1
	beq     L03A6
	ldy     #$07
	jsr     ldaxysp
	clc
	ldy     #$0F
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$02
	jsr     staxysp
	ldy     #$05
	jsr     ldaxysp
	clc
	ldy     #$0E
	adc     (sp),y
	bcc     L0605
	inx
L0605:	jsr     stax0sp
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	jsr     _tgi_setpixel
L03A6:	ldy     #$07
	jsr     ldaxysp
	jsr     incax1
	jmp     L0609
L03A5:	ldy     #$09
	jsr     ldaxysp
	jsr     incax2
	ldy     #$08
	jsr     staxysp
	ldy     #$05
	jsr     ldaxysp
	jsr     incax1
	jmp     L060A
L039D:	ldy     #$0A
	jsr     addysp
	jmp     incsp8
L0397:	lda     #<(L03BB)
	ldx     #>(L03BB)
	jsr     pushax
	ldy     #$09
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _printf
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ drawstring (__near__ const unsigned char *, unsigned int, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawstring: near

.segment	"CODE"

	jsr     pusha
	jmp     L03C1
L03BF:	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	jsr     _drawchar
	ldy     #$01
	ldx     #$00
	lda     #$05
	jsr     addeqysp
	ldy     #$04
	jsr     ldaxysp
	jsr     incax1
	ldy     #$03
	jsr     staxysp
L03C1:	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L03BF
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ drawWrappedString (__near__ const unsigned char *, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawWrappedString: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	ldy     #$0A
	jsr     pushwysp
	jsr     push0
	ldy     #$14
	jsr     subysp
	ldy     #$1D
	lda     (sp),y
	jsr     pusha0
	jmp     L03D1
L060B:	lda     #$05
	ldy     #$1C
	jsr     staxysp
	ldy     #$1A
	jsr     staxysp
	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$20
	jne     L03D7
	lda     #$02
	jsr     leaa0sp
	ldy     #$16
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     pushw0sp
	ldy     #$1B
	jsr     pushwysp
	ldy     #$21
	jsr     ldaxysp
	jsr     tosumulax
	jsr     tosaddax
	jsr     pushax
	ldy     #$21
	lda     (sp),y
	jsr     pusha0
	ldy     #$24
	lda     (sp),y
	jsr     pusha0
	ldy     #$23
	jsr     ldaxysp
	jsr     tosumulax
	jsr     tosaddax
	jsr     tosicmp
	bcc     L03DC
	beq     L03DC
	ldy     #$1E
	clc
	lda     #$07
	adc     (sp),y
	sta     (sp),y
	iny
	lda     (sp),y
	ldx     #$00
	jsr     stax0sp
L03DC:	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$22
	lda     (sp),y
	jsr     _drawstring
	ldy     #$19
	jsr     pushwysp
	ldy     #$1F
	jsr     ldaxysp
	jsr     tosumulax
	jsr     incax3
	jsr     addeq0sp
	ldx     #$00
	txa
	jmp     L060D
L03D7:	lda     #$02
	jsr     leaa0sp
	ldy     #$16
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$24
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     staspidx
	ldy     #$17
	jsr     ldaxysp
	jsr     incax1
L060D:	ldy     #$16
	jsr     staxysp
	ldy     #$21
	ldx     #$00
	lda     #$01
	jsr     addeqysp
L03D1:	ldy     #$22
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jne     L060B
	ldy     #$16
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L03F2
	lda     #$02
	jsr     leaa0sp
	dey
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     pushw0sp
	ldy     #$19
	jsr     ldaxysp
	jsr     mulax7
	jsr     tosaddax
	jsr     pushax
	ldy     #$21
	lda     (sp),y
	jsr     pusha0
	ldy     #$24
	lda     (sp),y
	jsr     mulax7
	jsr     tosaddax
	jsr     tosicmp
	bcc     L03F8
	beq     L03F8
	ldy     #$1E
	clc
	lda     #$07
	adc     (sp),y
	sta     (sp),y
	iny
	lda     (sp),y
	ldx     #$00
	jsr     stax0sp
L03F8:	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldy     #$05
	jsr     pushwysp
	ldy     #$22
	lda     (sp),y
	jsr     _drawstring
L03F2:	ldy     #$23
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_x (__near__ long *, __near__ long *, long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_x: near

.segment	"CODE"

	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$09
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$11
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	jsr     pusheax
	ldx     #$27
	lda     #$00
	lda     #$10
	jsr     tosdiv0ax
	ldy     #$00
	jsr     steaxspidx
	ldy     #$0F
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$27
	lda     #$00
	lda     #$10
	jsr     tosdiv0ax
	ldy     #$00
	jsr     steaxspidx
	ldy     #$10
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_y (__near__ long *, __near__ long *, long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_y: near

.segment	"CODE"

	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$09
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$11
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$27
	lda     #$00
	lda     #$10
	jsr     tosdiv0ax
	ldy     #$00
	jsr     steaxspidx
	ldy     #$0F
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     negeax
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$27
	lda     #$00
	lda     #$10
	jsr     tosdiv0ax
	ldy     #$00
	jsr     steaxspidx
	ldy     #$10
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ rotate_z (__near__ long *, __near__ long *, long)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_rotate_z: near

.segment	"CODE"

	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$09
	jsr     ldaxysp
	jsr     ldeaxi
	jsr     pusheax
	ldy     #$11
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     tossubeax
	jsr     pusheax
	ldx     #$27
	lda     #$00
	lda     #$10
	jsr     tosdiv0ax
	ldy     #$00
	jsr     steaxspidx
	ldy     #$0F
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_sine)
	tay
	txa
	adc     #>(_sine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     pusheax
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$15
	jsr     ldeaxysp
	jsr     aslax1
	clc
	adc     #<(_cosine)
	tay
	txa
	adc     #>(_cosine)
	tax
	tya
	jsr     ldaxi
	jsr     axlong
	jsr     tosmuleax
	jsr     tosaddeax
	jsr     pusheax
	ldx     #$27
	lda     #$00
	lda     #$10
	jsr     tosdiv0ax
	ldy     #$00
	jsr     steaxspidx
	ldy     #$10
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ draw_cube (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_cube: near

.segment	"CODE"

	lda     _x0+3
	sta     sreg+1
	lda     _x0+2
	sta     sreg
	ldx     _x0+1
	lda     _x0
	jsr     pusheax
	lda     _y0+3
	sta     sreg+1
	lda     _y0+2
	sta     sreg
	ldx     _y0+1
	lda     _y0
	jsr     pusheax
	lda     _z0+3
	sta     sreg+1
	lda     _z0+2
	sta     sreg
	ldx     _z0+1
	lda     _z0
	jsr     pusheax
	lda     _x1+3
	sta     sreg+1
	lda     _x1+2
	sta     sreg
	ldx     _x1+1
	lda     _x1
	jsr     pusheax
	lda     _y1+3
	sta     sreg+1
	lda     _y1+2
	sta     sreg
	ldx     _y1+1
	lda     _y1
	jsr     pusheax
	lda     _z1+3
	sta     sreg+1
	lda     _z1+2
	sta     sreg
	ldx     _z1+1
	lda     _z1
	jsr     pusheax
	lda     _x2+3
	sta     sreg+1
	lda     _x2+2
	sta     sreg
	ldx     _x2+1
	lda     _x2
	jsr     pusheax
	lda     _y2+3
	sta     sreg+1
	lda     _y2+2
	sta     sreg
	ldx     _y2+1
	lda     _y2
	jsr     pusheax
	lda     _z2+3
	sta     sreg+1
	lda     _z2+2
	sta     sreg
	ldx     _z2+1
	lda     _z2
	jsr     pusheax
	lda     _x3+3
	sta     sreg+1
	lda     _x3+2
	sta     sreg
	ldx     _x3+1
	lda     _x3
	jsr     pusheax
	lda     _y3+3
	sta     sreg+1
	lda     _y3+2
	sta     sreg
	ldx     _y3+1
	lda     _y3
	jsr     pusheax
	lda     _z3+3
	sta     sreg+1
	lda     _z3+2
	sta     sreg
	ldx     _z3+1
	lda     _z3
	jsr     pusheax
	lda     _x4+3
	sta     sreg+1
	lda     _x4+2
	sta     sreg
	ldx     _x4+1
	lda     _x4
	jsr     pusheax
	lda     _y4+3
	sta     sreg+1
	lda     _y4+2
	sta     sreg
	ldx     _y4+1
	lda     _y4
	jsr     pusheax
	lda     _z4+3
	sta     sreg+1
	lda     _z4+2
	sta     sreg
	ldx     _z4+1
	lda     _z4
	jsr     pusheax
	lda     _x5+3
	sta     sreg+1
	lda     _x5+2
	sta     sreg
	ldx     _x5+1
	lda     _x5
	jsr     pusheax
	lda     _y5+3
	sta     sreg+1
	lda     _y5+2
	sta     sreg
	ldx     _y5+1
	lda     _y5
	jsr     pusheax
	lda     _z5+3
	sta     sreg+1
	lda     _z5+2
	sta     sreg
	ldx     _z5+1
	lda     _z5
	jsr     pusheax
	lda     _x6+3
	sta     sreg+1
	lda     _x6+2
	sta     sreg
	ldx     _x6+1
	lda     _x6
	jsr     pusheax
	lda     _y6+3
	sta     sreg+1
	lda     _y6+2
	sta     sreg
	ldx     _y6+1
	lda     _y6
	jsr     pusheax
	lda     _z6+3
	sta     sreg+1
	lda     _z6+2
	sta     sreg
	ldx     _z6+1
	lda     _z6
	jsr     pusheax
	lda     _x7+3
	sta     sreg+1
	lda     _x7+2
	sta     sreg
	ldx     _x7+1
	lda     _x7
	jsr     pusheax
	lda     _y7+3
	sta     sreg+1
	lda     _y7+2
	sta     sreg
	ldx     _y7+1
	lda     _y7
	jsr     pusheax
	lda     _z7+3
	sta     sreg+1
	lda     _z7+2
	sta     sreg
	ldx     _z7+1
	lda     _z7
	jsr     pusheax
	lda     #$58
	jsr     leaa0sp
	jsr     pushax
	lda     #$56
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$5C
	jsr     leaa0sp
	jsr     pushax
	lda     #$56
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$5C
	jsr     leaa0sp
	jsr     pushax
	lda     #$5A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$4C
	jsr     leaa0sp
	jsr     pushax
	lda     #$4A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$50
	jsr     leaa0sp
	jsr     pushax
	lda     #$4A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$50
	jsr     leaa0sp
	jsr     pushax
	lda     #$4E
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$40
	jsr     leaa0sp
	jsr     pushax
	lda     #$3E
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$44
	jsr     leaa0sp
	jsr     pushax
	lda     #$3E
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$44
	jsr     leaa0sp
	jsr     pushax
	lda     #$42
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$34
	jsr     leaa0sp
	jsr     pushax
	lda     #$32
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$38
	jsr     leaa0sp
	jsr     pushax
	lda     #$32
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$38
	jsr     leaa0sp
	jsr     pushax
	lda     #$36
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$28
	jsr     leaa0sp
	jsr     pushax
	lda     #$26
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$2C
	jsr     leaa0sp
	jsr     pushax
	lda     #$26
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$2C
	jsr     leaa0sp
	jsr     pushax
	lda     #$2A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$1C
	jsr     leaa0sp
	jsr     pushax
	lda     #$1A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$20
	jsr     leaa0sp
	jsr     pushax
	lda     #$1A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$20
	jsr     leaa0sp
	jsr     pushax
	lda     #$1E
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$10
	jsr     leaa0sp
	jsr     pushax
	lda     #$0E
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$14
	jsr     leaa0sp
	jsr     pushax
	lda     #$0E
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$14
	jsr     leaa0sp
	jsr     pushax
	lda     #$12
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     axulong
	jsr     _rotate_x
	lda     #$08
	jsr     leaa0sp
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     axulong
	jsr     _rotate_y
	lda     #$08
	jsr     leaa0sp
	jsr     pushax
	lda     #$06
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     axulong
	jsr     _rotate_z
	lda     _toggle_clear
	beq     L04BF
	lda     #$00
	jsr     _tgi_setcolor
	lda     #$05
	jsr     pusha0
	jsr     pusha0
	lda     #$BE
	jsr     pusha0
	jsr     _tgi_bar
	lda     #$01
	jsr     _tgi_setcolor
L04BF:	ldy     #$5F
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$5D
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$57
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$55
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$53
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$51
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$4B
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$49
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$47
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$45
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$3F
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$3D
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$3B
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$39
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$63
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$61
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$2F
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$2D
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$27
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$25
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$23
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$21
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$1B
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$19
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$17
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$15
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$0F
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$0B
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$09
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$33
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$31
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$5F
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$5D
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$33
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$31
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$53
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$51
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$27
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$25
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$47
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$45
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$1B
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$19
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$3B
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$39
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$0F
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	ldy     #$64
	jsr     inceaxy
	jsr     _tgi_line
	ldy     #$60
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ itoa_custom (int, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_itoa_custom: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	jsr     decsp6
	ldy     #$0A
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0511
	jsr     pushwysp
	ldy     #$09
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$08
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     #$30
	ldy     #$00
	sta     (ptr1),y
	jmp     L0510
L060F:	jsr     ldaxysp
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     tosmoda0
	ldy     #$04
	jsr     staxysp
	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$08
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	jsr     ldaxysp
	ldy     #$30
	jsr     incaxy
	ldy     #$00
	sta     (ptr1),y
	ldy     #$0D
	jsr     pushwysp
	lda     #$0A
	jsr     tosdiva0
	ldy     #$0A
	jsr     staxysp
L0511:	ldy     #$0A
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L060F
L0510:	ldy     #$07
	jsr     ldaxysp
	clc
	ldy     #$08
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	tax
	ldy     #$02
	jsr     staxysp
	ldy     #$07
	jsr     ldaxysp
	jsr     decax1
	jsr     stax0sp
	jmp     L0524
L0522:	ldy     #$03
	jsr     ldaxysp
	clc
	ldy     #$08
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	clc
	ldy     #$09
	adc     (sp),y
	sta     sreg
	txa
	iny
	adc     (sp),y
	sta     sreg+1
	ldy     #$02
	jsr     ldaxysp
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
	ldy     #$02
	jsr     ldaxysp
	clc
	ldy     #$09
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	ldy     #$04
	jsr     ldaxysp
	jsr     incax1
	ldy     #$03
	jsr     staxysp
	ldy     #$02
	jsr     ldaxysp
	jsr     decax1
	ldy     #$01
	jsr     staxysp
	jsr     incsp1
L0524:	ldy     #$03
	jsr     ldaxysp
	ldy     #$00
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bvc     L060E
	eor     #$80
L060E:	jmi     L0522
	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ msgcat (__near__ unsigned char *, int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_msgcat: near

.segment	"BSS"

L0533:
	.res	40,$00

.segment	"CODE"

	jsr     pushax
	jsr     push0
	ldy     #$0A
	jsr     subysp
	jsr     push0
	ldy     #$11
	jsr     pushwysp
	lda     #$04
	jsr     leaa0sp
	jsr     _itoa_custom
	jmp     L053C
L053A:	lda     #<(L0533)
	ldy     #$0C
	clc
	adc     (sp),y
	sta     sreg
	lda     #>(L0533)
	iny
	adc     (sp),y
	sta     sreg+1
	jsr     ldaxysp
	clc
	ldy     #$10
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
	ldy     #$0D
	jsr     ldaxysp
	jsr     incax1
	ldy     #$0C
	jsr     staxysp
L053C:	ldy     #$0D
	jsr     ldaxysp
	clc
	ldy     #$10
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L053A
	jmp     L0546
L0544:	ldy     #$0D
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$0C
	jsr     staxysp
	lda     regsave
	clc
	adc     #<(L0533)
	tay
	lda     regsave+1
	adc     #>(L0533)
	tax
	tya
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	clc
	adc     #$04
	bcc     L054D
	inx
	clc
L054D:	adc     sp
	sta     ptr1
	txa
	adc     sp+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     staspidx
L0546:	lda     #$02
	jsr     leaa0sp
	ldy     #$00
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	dey
	lda     (ptr1),y
	bne     L0544
	lda     #<(L0533)
	ldy     #$0C
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(L0533)
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	lda     #<(L0533)
	ldx     #>(L0533)
	ldy     #$12
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"RODATA"

L0559:
	.byte	$D8,$D8,$20,$D2,$CF,$D4,$C1,$D4,$C9,$CF,$CE,$20,$2D,$20,$00
	.res	5,$00
L055D:
	.byte	$D9,$D9,$20,$D2,$CF,$D4,$C1,$D4,$C9,$CF,$CE,$20,$2D,$20,$00
	.res	5,$00
L0561:
	.byte	$DA,$DA,$20,$D2,$CF,$D4,$C1,$D4,$C9,$CF,$CE,$20,$2D,$20,$00
	.res	5,$00

.segment	"CODE"

	lda     #<(L0553)
	ldx     #>(L0553)
	jsr     pushax
	lda     #<(L0555)
	ldx     #>(L0555)
	jsr     pushax
	ldy     #$18
	jsr     subysp
	ldy     #$13
L055A:	lda     L0559,y
	sta     (sp),y
	dey
	bpl     L055A
	ldy     #$14
	jsr     subysp
	ldy     #$13
L055E:	lda     L055D,y
	sta     (sp),y
	dey
	bpl     L055E
	ldy     #$14
	jsr     subysp
	ldy     #$13
L0562:	lda     L0561,y
	sta     (sp),y
	dey
	bpl     L0562
	jsr     decsp2
	lda     #<(_tgi_static_stddrv)
	ldx     #>(_tgi_static_stddrv)
	jsr     _tgi_install
	jsr     _tgi_init
	jsr     _tgi_clear
	lda     #$01
	jsr     _tgi_setcolor
	ldx     #$00
	lda     #$0F
	sta     _rotX
	stx     _rotX+1
	lda     #$6E
	sta     _rotY
	stx     _rotY+1
	lda     #$55
	sta     _rotZ
	stx     _rotZ+1
	ldy     #$45
	jsr     pushwysp
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$0E
	jsr     _drawWrappedString
	lda     #$2A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     _msgcat
	jsr     stax0sp
	jsr     pushax
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$90
	jsr     _drawWrappedString
	lda     #$16
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     _msgcat
	jsr     stax0sp
	jsr     pushax
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$96
	jsr     _drawWrappedString
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     _msgcat
	jsr     stax0sp
	jsr     pushax
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$9C
	jsr     _drawWrappedString
L058F:	lda     _toggle_clear
	cmp     #$01
	bne     L0593
	lda     #$06
	jsr     _bordercolor
	ldy     #$3F
	sta     (sp),y
	ldy     #$47
	jsr     pushwysp
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$0E
	jsr     _drawWrappedString
L0593:	ldy     #$40
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	lda     _toggle_clear
	bne     L059F
	lda     #$02
	jsr     _bordercolor
	ldy     #$3F
	sta     (sp),y
L059F:	ldy     #$41
	jsr     ldaxysp
	cmp     #$06
	txa
	sbc     #$00
	bvs     L05A6
	eor     #$80
L05A6:	bpl     L05A4
	ldx     #$00
	txa
	ldy     #$40
	jsr     staxysp
L05A4:	jsr     _kbhit
	tax
	beq     L05AE
	jsr     _tgi_clear
	jsr     _cgetc
	ldy     #$3E
	sta     (sp),y
	cmp     #$20
	bne     L05AE
	lda     _toggle_clear
	jsr     bnega
	sta     _toggle_clear
L05AE:	lda     #$01
	jsr     _tgi_setcolor
	lda     #$0D
	clc
	adc     _rotX
	sta     _rotX
	bcc     L05B6
	inc     _rotX+1
L05B6:	lda     _rotX
	cmp     #$67
	lda     _rotX+1
	sbc     #$01
	bcc     L05B7
	lda     #$00
	sta     _rotX
	sta     _rotX+1
	lda     #$0D
	clc
	adc     _rotY
	sta     _rotY
	bcc     L05BD
	inc     _rotY+1
L05BD:	jsr     _tgi_clear
	jsr     pushw0sp
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$90
	jsr     _drawWrappedString
	lda     #$16
	jsr     leaa0sp
	jsr     pushax
	lda     _rotY
	ldx     _rotY+1
	jsr     _msgcat
	jsr     stax0sp
	jsr     pushax
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$96
	jsr     _drawWrappedString
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	lda     _rotZ
	ldx     _rotZ+1
	jsr     _msgcat
	jsr     stax0sp
	jsr     pushax
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$9C
	jsr     _drawWrappedString
L05B7:	lda     _rotY
	cmp     #$67
	lda     _rotY+1
	sbc     #$01
	bcc     L05D6
	lda     #$00
	sta     _rotY
	sta     _rotY+1
	lda     #$0D
	clc
	adc     _rotZ
	sta     _rotZ
	bcc     L05D6
	inc     _rotZ+1
L05D6:	lda     _rotZ
	cmp     #$67
	lda     _rotZ+1
	sbc     #$01
	lda     #$00
	bcc     L0610
	sta     _rotZ
	sta     _rotZ+1
L0610:	jsr     _tgi_setcolor
	ldx     #$01
	lda     #$04
	jsr     pushax
	lda     #$90
	jsr     pusha0
	ldx     #$01
	lda     #$18
	jsr     pushax
	dex
	lda     #$93
	jsr     _tgi_bar
	lda     #$01
	jsr     _tgi_setcolor
	lda     #$2A
	jsr     leaa0sp
	jsr     pushax
	lda     _rotX
	ldx     _rotX+1
	jsr     _msgcat
	jsr     stax0sp
	jsr     pushax
	lda     #$14
	jsr     pusha
	lda     #$C8
	jsr     pusha
	lda     #$90
	jsr     _drawWrappedString
	jsr     _draw_cube
	jmp     L058F

.endproc

